### ISSUE TITLE
[Request] Tagged version release

### ISSUE THREAD

**Issue by molaeiali** [ProtonMail/proton-bridge#10]
Can we have version tagged releases to be able to download tar.gz source-code of each version?

**Comment by A6GibKm** [comment]
I would be also great to have automatic builds for such tags.

**Comment by mKoonrad** [comment]
> I would be also great to have automatic builds for such tags.

Builds for all ProtonMail and ProtonVPN apps in GitHub should be great. In most cases code on GitHub isn't up-to-date.

**Comment by horejsek** [comment]
Hi. All new releases from now on are going to be tagged here on GitHub as well.

**Comment by molaeiali** [comment]
@horejsek @jameshoulahan 
I see the tagged version is v1.2.7-beta.3, and a notice on the application that 1.2.7 is out, should I build 1.2.7 from this tagged version or it is a beta and I should not do that for Arch Linux AUR?

**Comment by horejsek** [comment]
@molaeiali For live version please use published v1.2.7-live.1. We are sorry for delay. :-)

**Comment by molaeiali** [comment]
thanks

**Comment by molaeiali** [comment]
Hey Proton Team

As I'm maintaining some of your AUR packages on Arch Linux, I would be grateful if you made release tags like actual releases in GitHub, not just a tag. I mean something like your Android Project for example https://github.com/ProtonMail/proton-mail-android/releases

Because then I can watch the project for Release notifications and get an email each time a new release is published, right now, I have no way to realize that and have to check the page from time to time or run a custom script myself to check it.

If it's not possible to do this, then can you show me some alternative way to get notified on this?

Thanks

@horejsek
