### ISSUE TITLE
Recently released versions are not tagged as required

### ISSUE THREAD

**Issue by kortschak** [ProtonMail/proton-bridge#107]
## Expected Behavior

Given that the bridge is released under the GPL there should be adequate Installation Information for the provided releases. This would minimally include the commits or tags for the released versions.

## Current Behavior

There is no tag for versions after 1.3.3 and the sha for 1.4.5 (ae1578a5e2) does not exist in the tree AFAICS (I did not check this for 1.4.4).

## Possible Solution

Tag releases.

## Steps to Reproduce

1. Checkout latest commit
2. Run `git tag`
3. Notice no tags with semver >v1.3.3

## Context (Environment)

I was intending to investigate #106 with the version of the bridge that is running, but cannot with certainty.

## Detailed Description

Follow GPL licensing requirements.

## Possible Implementation

Tag releases correctly.

**Comment by Spixmaster** [comment]
One of the developers already stated that the missing tag will be added in the future. https://github.com/ProtonMail/proton-bridge/issues/100#issuecomment-713521984
Although, I really do not understand why tagging takes so much time. The comment took more time than tagging.

**Comment by jameshoulahan** [comment]
Missing commits and tags have been pushed. Apologies for the delays; we aim to change our release process to ensure that, going forward, all tags and commits are pushed beforehand.

**Comment by kortschak** [comment]
Thanks
