### ISSUE TITLE
Naming of COPYING.md breaks pkg.go.dev documentation rendering

### ISSUE THREAD

**Issue by kortschak** [ProtonMail/proton-bridge#109]
Currently the versioned documentation of  ProtonMail/proton-bridge is broken by the choice if versioning approach that does not conform to the rest of the Go ecosystem (#100), but even if that is corrected, the communities documentation system will not work correctly because of the existence of the COPYING.md file which the pkg.go.dev license detection system sees as a LICENSE file that it cannot understand (and so rejects — see https://pkg.go.dev/license-policy). Given that the file is for human consumption and merely reiterates the GPL license and shows licenses that are incorporated in the compiled product, the name of the file could be changed to LICENSES.md or THIRD_PARTY_LICENSES.md or something that gets across the required information without confusing the mechanical lawyer at pkg.go.dev.

**Comment by kortschak** [comment]
See golang/go#42175

**Comment by andrzejsza** [comment]
thanks for highlighting. this is now changed - COPYING.md to COPYING_NOTES.md

**Comment by kortschak** [comment]
Thanks.

**Comment by kortschak** [comment]
Note that package documentation is still not available since 1.3.3 because of #100. See https://pkg.go.dev/github.com/ProtonMail/proton-bridge/?tab=versions
