### ISSUE TITLE
missing dependency: libsecret-1-dev

### ISSUE THREAD

**Issue by omicron-b** [ProtonMail/proton-bridge#11]
on Debian Testing, `make run` fails with the following message:

```
# command-line-arguments
/usr/lib/go-1.14/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lsecret-1
collect2: error: ld returned 1 exit status

make: *** [Makefile:191: run-nogui-cli] Error 2
```

**Comment by exander77** [comment]
Yes, this affected me too, I have completely forgotten after the fact.

**Comment by A6GibKm** [comment]
Also `libGL.so` is missing for `make build`

**Comment by jameshoulahan** [comment]
The associated MR has been merged and will appear in this repository soon. Closing issue.
