### ISSUE TITLE
Credentials not found switching from plasma workspace to plasma-wayland workspace

### ISSUE THREAD

**Issue by mattiaverga** [ProtonMail/proton-bridge#110]
On Fedora 33 with bridge v1.4.4_6cbc11a75d user credentials are not found when switching from KDE plasma (Xorg) session to KDE plasma-wayland session.

## Expected Behavior
Bridge should maintain settings and account when switching DE.

## Current Behavior
Bridge doesn't found user credentials under plasma-wayland for an account created under plasma (Xorg).

## Steps to Reproduce
1. Install F33 with KDE
2. Login in a plasma (Xorg) session, install bridge from protonmail RPMs and add a user account to bridge
3. Close session and login the same user into a plasma-wayland session
4. Run bridge, it starts without any account

Logs under plasma-wayland shows:
```
{"level":"warning","msg":"Bridge version: v1.4.4_6cbc11a75d linux","pkg":"config","time":"2020-10-25T13:49:46+01:00"}
{"level":"error","msg":"No keychain! Pass: pass not initialized: exec: \"pass\": executable file not found in $PATH: , secretService: Error 24 while listing from secretservice library: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached","pkg":"bridgeUtils/keychain","time":"2020-10-25T13:50:12+01:00"}
{"level":"error","msg":"Could not get credentials store: no keychain management installed on this system","pkg":"main","time":"2020-10-25T13:50:12+01:00"}
{"error":"no keychain management installed on this system","level":"error","msg":"Store is unusable","pkg":"credentials","time":"2020-10-25T13:50:12+01:00"}
{"error":"no keychain management installed on this system","level":"error","msg":"Could not load all users from credentials store","pkg":"users","time":"2020-10-25T13:50:12+01:00"}
```

**Comment by jameshoulahan** [comment]
Hi there, this is most likely caused by an ongoing gnome-keyring bug https://gitlab.gnome.org/GNOME/gnome-keyring/-/issues/19 -- I don't think there's anything we as Bridge can do unfortunately
