### ISSUE TITLE
protonmail-bridge depends on ttf-dejavu; however ttf-dejavu is not installable (Debian testing)

### ISSUE THREAD

**Issue by thekix** [ProtonMail/proton-bridge#111]
Hi,

the package ttf-dejavu is moved to fonts-dejavu in Debian testing/sid. The dependencies should be updated.

```
root@xxxx:/home/kix/Downloads# LANG=C dpkg -i protonmail-bridge_1.4.5-1_amd64.deb 
(Reading database ... 345868 files and directories currently installed.)
Preparing to unpack protonmail-bridge_1.4.5-1_amd64.deb ...
Unpacking protonmail-bridge (1.4.5-1) over (1.4.5-1) ...
dpkg: dependency problems prevent configuration of protonmail-bridge:
 protonmail-bridge depends on ttf-dejavu; however:
  Package ttf-dejavu is not installed.

dpkg: error processing package protonmail-bridge (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mime-support (3.64) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 protonmail-bridge
root@xxxx:/home/kix/Downloads# 
```

To solve the problem, you can implement something like this in debian/Depends:

```
Depends: qt5-default, libqt5designer5, libqt5multimediawidgets5, libqt5quickwidgets5, libpulse-mainloop-glib0, libsecret-1-0, ttf-dejavu|fonts-dejavu
```

Best regards,
kix

**Comment by Desttro** [comment]
Same issue for Ubuntu 20.10 (groovy):

```
user@PC:~/Downloads$ sudo apt install ./protonmail-bridge_1.4.5-1_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'protonmail-bridge' instead of './protonmail-bridge_1.4.5-1_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 protonmail-bridge : Depends: ttf-dejavu but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by thekix** [comment]
Hi @Desttro 

the workaround is download these packages and install manually. You need `ttf-dejavu`, `ttf-dejavu-extra` and `ttf-dejavu-core`. These packages do not include files, only metadata, so there is no other dependencies or conflicts.

Cheers,
kix

**Comment by Desttro** [comment]
Hello,
I have tried, but there is no package like this for "groovy" - Ubuntu 20.10

user@PC:~$ sudo apt install ttf-dejavu ttf-dejavu-extra ttf-dejavu-core
[sudo] password for user:
Reading package lists... Done
Building dependency tree      
Reading state information... Done
Package ttf-dejavu-core is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package ttf-dejavu is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ttf-dejavu' has no installation candidate
E: Unable to locate package ttf-dejavu-extra
E: Package 'ttf-dejavu-core' has no installation candidate
user@PC:~$



‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
úterý, říjen 27, 2020 8:56 AM, Rodolfo García Peñas <notifications@github.com> napsal:

**Comment by thekix** [comment]
Hello,

use this packages (from Debian sid):

- https://packages.debian.org/sid/ttf-dejavu
- https://packages.debian.org/sid/ttf-dejavu-core
- https://packages.debian.org/sid/ttf-dejavu-extra

Download using the "all" Architecture and then select a mirror. After download the packages, install them using `dpkg`

```
dpkg -i download-folder/ttf-dejavu-extra_2.37-1_all.deb
...
```

Regards,
kix

**Comment by Desttro** [comment]
Hello, now it works, thank you for a quick support!


‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
úterý, říjen 27, 2020 11:10 AM, Rodolfo García Peñas <notifications@github.com> napsal:

**Comment by thekix** [comment]
Thanks! :+1: 

I am just a user ;-)

**Comment by cmonyuk** [comment]
Same issue, but for qt5-default: https://packages.debian.org/buster/qt5-default

"This package should not be used for building Debian packages. Take a look at https://qt-kde-team.pages.debian.net/packagingqtbasedstuff.html for more information."

**Comment by thekix** [comment]
Issue still in version 1.5.0-1

**Comment by andrzejsza** [comment]
@thekix could you try 1.5.2? this should be fixed there.

**Comment by andrzejsza** [comment]
assuming it is - let us know if otherwise!

**Comment by thekix** [comment]
Hi @andrzejsza 

sorry about the delay. Yes, now all is ok. Thanks a lot!
