### ISSUE TITLE
Claims capability IMAP4REV1, but does not support NOT and OR operatitions defined in RFC3501

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#113]
Especially NOT is critical to filter emails in searches, for example, `NOT DELETED`. It seems to be known as Bridge checks for `NOT` and `OR` and issues error.

**Comment by andrzejsza** [comment]
this is a known issue - we will be looking into supporting a broader range of imap protocol in the future - I know it sounds vague, but will keep you posted on the progress.

**Comment by andrzejsza** [comment]
both of those are now supported with V3.
