### ISSUE TITLE
Initial UID ordering in Bridge should be based on message Date

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#114]
After setting up Bridge, the UIDs in my Send folder are completely incoherent in combined mode. Last 100 UIDs does not correspond to the last 100 messages in any way. As UIDs are fully synthesized by the bridge I recommend sorting them by message Date.

**Comment by andrzejsza** [comment]
yes, the UIDs are based on when the message was downloaded from the server, not sent or receive date. since we are doing it in parallel, there is no easy way to be more coherent but also no point, as the client will use the date.

**Comment by exander77** [comment]
@andrzejsza There is an expectation in a lot of implementations that last `n` UIDs will pull the last `n` messages.

**Comment by andrzejsza** [comment]
can you share some examples of where would this be beneficial? again, we think that doing it in parallel allows for some good performance benefit and happy to pay the cost of UIDs to appear incoherent (although they are not, as they do follow the logic that was intended).
