### ISSUE TITLE
Prevent proton-bridge gui from grabbing focus

### ISSUE THREAD

**Issue by marc0der** [ProtonMail/proton-bridge#115]
When the proton-bridge is out of date on a system, it periodically forcefully comes to the foreground when minimised and takes focus in the window manager. This is a terribly disruptive, and a horrible UX.

## Expected Behavior
Keep the bridge minimised in the tray, but show the red dot as it currently does. No need to bring it to the foreground.

## Current Behavior
It jumps into focus while using another program.

## Possible Solution
Don't let it come to the foreground.

## Context (Environment)
My installation of proton-bridge is handled by my package manager on Arch Linux. When a new update comes available in the AUR, I simply update it and it makes its way onto my system. No need to pester me that it is out of date because I can do nothing about it unless it becomes available on the AUR.

**Comment by exander77** [comment]
I think it was already reported here. In my opinion, this is a Windows Manager responsibility. The application asks the Windows Manager for a focus to inform a user about the important thing. Windows Manager is what allows it. If the Windows Manager allows any application to grab focus anytime, then well...

**Comment by andrzejsza** [comment]
thanks for your comments @marc0der. we are working on both new updates and significant changes to the GUI. UX (including not stealing the focus) is main consideration for both of those projects. Since that's already in our pipeline, let me close this issue.

**Comment by chrisamow** [comment]
Did this get deferred past visibility?  At the very least, there should be an option to work around this (if it is technically ruled a window manager problem)
It has become annoying almost to the point of unusability.

**Comment by exander77** [comment]
@chrisamow In my opinion, this is a windows manager issue. If it allows any window to grab focus arbitrarily, I would even call it a security issue.

**Comment by chrisamow** [comment]
> @chrisamow In my opinion, this is a windows manager issue. If it allows any window to grab focus arbitrarily, I would even call it a security issue.

I understand that position.  But it would seem there are multiple windows managers showing this behavior and most people are not in a position to chase that down until window manager fixes can be put in.  Given it's impact, having an option to turn off the notification completely would be a workaround that doesn't require hardcoding a hack as a windows manager workaround.  This is an extreme dissatisfier constantly having my workspace switched out from under me just because of the protonmail bridge UI which I have hidden in general anyway.

**Comment by marc0der** [comment]
@exander77 Unfortunately, I have now uninstalled the protonmail bridge due to the terrible UX. It is almost a year later, and nothing has been done about this. Funnily enough, none of my other apps has such an issue, so I tend to think that this app is at fault.

**Comment by exander77** [comment]
@marc0der Your logic is flawed. Everybody implementing a workaround does not mean that it is a correct solution and it also does not prevent your focus to be grabbed by a new application (like Proton-Bridge) that does not offer this option.

Issue of focus-grabbing has been reported numerous times into various Windows Managers for Linux, on Windows and on MacOS. I cannot imagine my Android app stealing focus (only phone app is allowed this under normal circumstances). I use Xfce on Linux and it has various options regarding focus-grabbing though they could really improve this as well. Windows Manager developers should adopt Android like permissions for focus-grabbing and other non-standard behaviour. Not to mention that behaviour like automatic Startup, focus Grabbing etc. should be configured in a single place, not in each application separately.

**Comment by marc0der** [comment]
@exander77 nope, it's your logic that is flawed. The situation is actually simple: regardless of your ideology about GUIs and that you are right and everyone else is wrong, nobody really cares. People care about one thing, user experience. In this day and age, you have a few moments to impress your users. If you don't, the outcome is straightforward. You get cancelled.

@andrzejsza I'm very disappointed that this issue was closed without any proper follow-up or resolution. Also that ProtonMail condones this sort of harsh opinionated communication.

Already uninstalled, now unsubscribed, goodbye.
