### ISSUE TITLE
Protonmail Bridge Should Distributed Checksums With Releases

### ISSUE THREAD

**Issue by bonedaddy** [ProtonMail/proton-bridge#116]
# Background

Initially reported this to the `bridge@protonmail.com` support email but received no response so figured I would open this here.

# Issue

The official release channels for the protonmail bridge do not distribute checksums along with the actual updated software. This is pretty basic practice for distributing software, and pretty much all software is distributed with downloadable checksums. It's trivial to add in the release workflow, and goes along way to ensuring that downloads weren't compromised.

**Comment by paultheastronomer** [comment]
I agree with @bonedaddy on this.

You can verify bridge and the the Import-Export app by following the instructions for verifying the rpm file of the Bridge app with the same GPG key "bridge_pubkey.gpg".

The ProtonMail Bridge and import-export RPM packages are both signed using rpm –sign.

For verifying both you can use the bridge public key: bridge_pubkey.gpg which can be found [here](https://protonmail.com/download/bridge_pubkey.gpg) or on [this page](https://protonmail.com/support/knowledge-base/verifying-bridge-package/).

To import the Bridge app’s public key to your keyring, use the following instructions:

`sudo rpm --import bridge_pubkey.gpg`

To check the .rpm file run:

`rpm --checksig protonmail-bridge-1.2.6-1.x86_64.rpm`

or in the case of the import-export app

`rpm --checksig protonmail-import-export-app-1.1.2-1.x86_64.rpm `

(be aware that the version numbering needs changing to the lastest version in the above commands)

The successful result should look like this:

`protonmail-bridge-1.2.6-1.x86_64.rpm: digests signatures OK`

**Comment by andrzejsza** [comment]
as @paultheastronomer pointed out, signatures seem like a much more reliable verification method. we could add the checksums but not sure how this would improve the security?

**Comment by andrzejsza** [comment]
yes, we really don't see the point of adding those. much better verification method is described above + more info here: https://protonmail.com/support/knowledge-base/verifying-bridge-package/
