### ISSUE TITLE
Sentry reporting logs IP address

### ISSUE THREAD

**Issue by sneak** [ProtonMail/proton-bridge#117]
## Expected Behavior

My IP address is not logged using ProtonMail services, as is advertised on ProtonMail.com.

## Current Behavior

In a crash, my IP address is logged to a third party, the bug analytics company Sentry.

## Possible Solution

Obtain opt-in consent on first launch of Bridge for Sentry error reporting before loading Sentry code.

**Comment by jameshoulahan** [comment]
Hi @sneak, thanks for contacting us.

In the event of a crash, the bridge will send a crash dump to our self-hosted sentry instance. The data collected is anonymised and no data is kept that could be used to personally identify you.

For more information, please see the "Native Applications" section of our [privacy policy](https://protonmail.com/privacy-policy), which also makes mention of our self-hosted sentry instance.

**Comment by sneak** [comment]
@jameshoulahan Thank you, that's great news.   The DSNSentry value is not included in this repository, however:

https://github.com/ProtonMail/proton-bridge/blob/bfdfc81d65dacde57538def61af70195ca397b02/pkg/constants/constants.go#L33

Considering that it's not secret (it's distributed in the application sent to users), perhaps it could be committed to this repository to clear up any ambiguity?  It would have prevented this report, for example.

**Comment by jameshoulahan** [comment]
It's not exactly a secret, you're right, but we don't want to make it too easy for it to be abused. The DSN contains authentication information and looks like this: `https://<token>:<token>@api.protonmail.ch/reports/sentry/<product>`. Perhaps we could supply just the tokens at build time and commit the rest of the DSN to the repository.

On the other hand, things like this are what are holding us back from truly reproducible builds. It would be awesome if users could build bridge themselves from the code in this repository and get a bit-for-bit identical result to the official builds they can download from our website. Any thoughts?
