### ISSUE TITLE
Inline PGP only when using Bridge

### ISSUE THREAD

**Issue by kausban** [ProtonMail/proton-bridge#124]
## Expected Behavior
Emails sent should follow the settings set in: External PGP settings > Default PGP Scheme.
Using PGP/MIME or Inline PGP

## Current Behavior
All emails sent use inline PGP format. PGP/MIME used to work previously at least.

## Possible Solution
PGP/MIME used to work previously at least. Revert?

## Steps to Reproduce
1. Set External PGP settings > Sign external messages: Enable
    Set External PGP settings > Default PGP Scheme: PGP/MIME
2. Send email to non ProtonMail test address.
3. See email on recipient's inbox.
4. Also happens with PGP encrypted email that are sent to contacts with enabled public keys.

## Context (Environment)
Noticed it recently with 1.4.5 (on GNU/Linux). Not sure when this started happening. Defnitely behaved correctly in the past though.

**Comment by jameshoulahan** [comment]
Hi, yes, this was indeed a bug that snuck into v1.4.5 -- PGP/Inline was accidentally used for *all* plaintext messages. It has already been fixed for the upcoming v1.5.0 release.
