### ISSUE TITLE
Folders containing / are not shown in Thunderbird and Evolution

### ISSUE THREAD

**Issue by Spixmaster** [ProtonMail/proton-bridge#125]
# Problem
I have the following folders:

* geld/arbeit
* geld/keys
* geld/käufe
* geld/steuer

None of them are shown in either Thunderbird or Evolution.

## Possible reprodution
The folders were shown in Thunderbird when the display still worked like this:
* geld\
  * arbeit
  * keys
  * käufe
  * steuer

I tried to rename "geld\" to "geld".

# Solution
I solved the issue by reinstalling protonmail-bridge, deleteing ~/.config/protonmail and removing my account and login again in ProtonMail.
However, this should not have happened.

**Comment by Spixmaster** [comment]
I solved the issue by reinstalling protonmail-bridge, deleteing ~/.config/protonmail and removing my account and login again in ProtonMail.
However, this should not have happened.

**Comment by andrzejsza** [comment]
agree that this should not have happened. we are working on the full support for subfolders. in the meantime, if you run into more problems, please contact support.

**Comment by dsommers** [comment]
I'm willing to help test out full subfolder support.  This is one feature holding back migrating to ProtonMail.  I could not find any other issues more appropriate related to subfolders.  And I have the exact same issue as described here.

https://twitter.com/DavidSommerseth/status/1335709467615391744

**Comment by andrzejsza** [comment]
yes, thanks for this @dsommers. we'll get in touch once we have beta ready for testing! issue described here is definitely one of the biggest challenges - since IMAP uses `/` as hierarchy delimiter, we don't have many options of how to allow both - full subfolders support and `/` in folders' names.
