### ISSUE TITLE
New parser summary

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#127]
@jameshoulahan  After running new parser and filtering duplicities, I have the following results:

```
     77 failed to create new parser: multipart: boundary is empty
```
Reported as: https://github.com/ProtonMail/proton-bridge/issues/121

```
     10 failed to create new parser: encoding error: unhandled encoding "8t"
```
Cases of unknown encoding (already mentioned somewhere).

```
      34 failed to parse message header: failed to parse to: error parsing rfc5322 input: no viable alternative at input
      4 failed to parse message header: failed to parse from: error parsing rfc5322 input: no viable alternative at input
      4 failed to parse message header: failed to parse date: error parsing rfc5322 input: mismatched input
      1 failed to parse message header: failed to parse cc: error parsing rfc5322 input: no viable alternative at input
```
Special cases not parsed by the new parser.

```
      6 failed to collect attachments: mime: invalid media parameter
```
Reported as: https://github.com/ProtonMail/proton-bridge/issues/126

```
     1 failed to collect attachments: mime: duplicate parameter name
```
Duplicate charset in attachment `Content-Type`.

```
      3 failed to create new parser: quotedprintable: invalid unescaped byte 0x11 in body
      1 failed to create new parser: quotedprintable: invalid unescaped byte 0x1c in body
      1 failed to create new parser: quotedprintable: invalid bytes after =: ""
      3 failed to create new parser: illegal base64 data at input byte 0
      2 failed to create new parser: illegal base64 data at input byte 5
      1 failed to create new parser: illegal base64 data at input byte 452
      1 failed to create new parser: illegal base64 data at input byte 420
```
Invalid characters in encoded data (quoted-printable, base64).

```
      3 failed to create new parser: unexpected EOF
      2 failed to create new parser: multipart: NextPart: EOF
      2 failed to parse message header: can not get encoding for '' (or '')
      1 failed to collect attachments: mime: invalid media parameter: Fwd
      1 failed to collect attachments: can not get encoding for '' (or '')
```
So far not investigated.

**Comment by exander77** [comment]
@jameshoulahan I am currently running your branch with fixes:

**1. Comments after `angle-addr` not processed as the display name. You already know about this and We will see, I am just noting it here.**

**2. Still procudes `"=?utf-8?Q??="` display name. You already know about this and We will see, I am just noting it here.**

**3. Spaces are swallowed in non-quoted, non-encoded `display-name`.**

Example:
```
Mgr. Somebody Somewhere <somebody@somewhere.com>
```
Becomes:
```
"Mgr.Somebody Somewhere" <somebody@somewhere.com>
```
Probably related to a period in the end? And it is interpreted as a dotted atom? It probably affects all titles and other words ending with a period if they are unencoded. Currently, this is the biggest issue I see.

This also relates to those `@` symbols We have added and you asked about them. Example:
```
Somebody @ Somewhere <somebody@somewhere.com>
```
Becomes:
```
"Somebody@Somewhere" <somebody@somewhere.com>
```
As it also affects also the other case, I suggest joining consecutive unencoded segments with space.

**Comment by jameshoulahan** [comment]
> 3. Spaces are swallowed in non-quoted, non-encoded display-name, most probably when a period is the last symbol.

This is the result of trying to best support things like `first.last <user@domain.com>`. It gets parsed as three separate `word`s: `first`, `.`, `last`. This happens because of the definition of `obs-phrase` as `word *(word / "." / CFWS)`. Originally, I did as you suggested, and joined all parts of an `obs-phrase` with a space. However, you raised the concern that `first.last` was being rendered as `first . last`, which I agreed wasn't good, so I stopped joining `.` with space. But now I see that approach doesn't work in all cases either. The same applies to `@`; I treat them identically.

I think the best approach is to simply pick one rule and follow it in all cases. Join all parts with spaces? Join everything except `.` / `@` with spaces? Not sure. If users want their addresses rendered properly, they shouldn't use obsolete phrases 🤷

**Comment by exander77** [comment]
@jameshoulahan 
Maybe `CFWS` should be translated into a single space in obsolete if no encoding is used? There are so many strange cases.

Yes, you are right, `undisclosed-recipients` should not be inside `angle-addr`. So that's probably it.

I will move issues related to new parser into that new repository and will leave here only things which relate the rest of the parsing.

**Comment by exander77** [comment]
Finally got to actually remigrate all emails
```
     77 failed to create new parser: multipart: boundary is empty: unknown-subject
     24 failed to create new parser: unexpected EOF: unknown-subject
     10 failed to create new parser: encoding error: unhandled encoding "8t": unknown-subject
      7 failed to parse message header: failed to parse to: error parsing rfc5322 input: no viable alternative at input <grouped>
      7 failed to create new parser: illegal base64 data at input <grouped>
      7 failed to create new parser: encoding error: unhandled encoding "Hexa": unknown-subject
      5 failed to parse message header: failed to parse from: error parsing rfc5322 input: no viable alternative at input <grouped>
      5 failed to collect attachments: mime: invalid media parameter: <grouped>
      4 failed to create new parser: message: malformed MIME header line: <grouped>
      3 failed to create new parser: quotedprintable: invalid unescaped byte 0x11 in body: unknown-subject
      2 failed to parse message header: failed to parse date: error parsing rfc5322 input: mismatched input '-' expecting {<EOF>, '?', '?', ' ', '('}: <subject>
      2 failed to parse message header: can not get encoding for '' (or ''): unknown-subject
      1 failed to parse message header: failed to parse date: error parsing rfc5322 input: mismatched input 's' expecting ',': <subject>
      1 failed to parse message header: failed to parse date: error parsing rfc5322 input: mismatched input '+' expecting <EOF>: <subject>
      1 failed to parse message header: failed to parse cc: error parsing rfc5322 input: no viable alternative at input <grouped>
      1 failed to create new parser: quotedprintable: invalid bytes after =: "": unknown-subject
      1 failed to create new parser: multipart: NextPart: EOF: unknown-subject
      1 failed to collect attachments: can not get encoding for '' (or ''): <subject>
```

**Comment by andrzejsza** [comment]
thanks for the summary, but it's easier for us to keep the issues separately. it's clear that the main problem is with #121 badly parses Content-Type boundary, so we'll pick it up there. to manage expectations - we won't be able to put much more resource into the I-E app parser any time soon.
