### ISSUE TITLE
protonmail-bridge depends on qt5-default which is being removed

### ISSUE THREAD

**Issue by JulienPalard** [ProtonMail/proton-bridge#129]
On Debian Bullseye, since a few hours, protonmail-bridge can no longer be installed:

    protonmail-bridge : Depends: qt5-default which is a virtual package and is not provided by any available package

Looks like [qt5-default is being dropped](https://tracker.debian.org/media/packages/q/qtbase-opensource-src/changelog-5.15.1dfsg-2):

>  * Remove qt5-default. Nowadays it's not needed as Qt 5 is the only Qt version
>    in Debian and it brought more problems than solutions.

Related to https://github.com/ProtonMail/proton-bridge/issues/111#issuecomment-724148238

**Comment by waterkip** [comment]
Perhaps change the deps to be dependent on: one of these: qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools

**Comment by jameshoulahan** [comment]
Thanks for pointing this out. We'll make sure to update our dependencies asap!

**Comment by JulienPalard** [comment]
For the user reading this issue, it also happen in 1.5.0.

**Comment by Xanatos00** [comment]
Same issue with 1.5.2-1

**Comment by JulienPalard** [comment]
@jameshoulahan can you please reopen this issue until it is fixed? (strange to have to ask for that) so subscribers of this issue can have a notification when it's actually fixed?

**Comment by jameshoulahan** [comment]
Sure, apologies

**Comment by waterkip** [comment]
I've looked into it and it seems the dependency is just a build-dependency. I've build the bridge from the git repo in Docker and ran it on a clean netinstall of Debian. It seems the only real dependencies are: libqt5designer5 libqt5multimediawidgets5 libqt5quickwidgets5 libpulse-mainloop-glib0 libsecret-1-0 fonts-dejavu

I cannot find the debian dir in the repo, so I cannot create a pull request.

For those who want to install it, this is how you can build and install it from the git repo:
```
GOPATH=${GOPATH:-$HOME/go}"
PATH="${PATH}:${GOPATH}/bin"

apt-get install -y --no-install-recommends gcc golang-go make \
    libglvnd-dev libsecret-1-dev git ca-certificates qt5-qmake g++

make prepare-vendor build

apt-get install -y --no-install-recommends libqt5designer5 libqt5multimediawidgets5 \
    libqt5quickwidgets5 libpulse-mainloop-glib0 libsecret-1-0 fonts-dejavu

mkdir -p /opt/protonmail
tar zxvf bridge_linux_a50266cdc0.tgz --directory /opt/protonmail
```

**Comment by andrzejsza** [comment]
this is now fixed and deployed in the most recent beta (1.5.4).

**Comment by waterkip** [comment]
Could you tell me where I can donwload the beta?

**Comment by andrzejsza** [comment]
in this case, easier to wait for the new live which will be out in a few minutes.
for future referent though:

https://protonmail.com/download/beta/Bridge-Installer.exe
https://protonmail.com/download/beta/Bridge-Installer.dmg
https://protonmail.com/download/beta/PKGBUILD

and for those two you need to know the version:
https://protonmail.com/download/beta/protonmail-bridge_1.5.4-1_amd64.deb
https://protonmail.com/download/beta/protonmail-bridge-1.5.4-1.x86_64.rpm

**Comment by Xanatos00** [comment]
Well done.
Thanks to all contributors.
