### ISSUE TITLE
Illegal base64 data

### ISSUE THREAD

**Issue by mesca** [ProtonMail/proton-bridge#132]
## Expected Behavior

I should be able to fetch all messages.

## Current Behavior

Base64 decoding fail on some messages: 

```
DEBU[Nov 18 18:01:52.884] KLDO5 FETCH 1:2 (UID RFC822.SIZE)             loc="127.0.0.1:1143" pkg=imap/client rem="127.0.0.1:60916"
INFO[Nov 18 18:01:52.884] Pausing event loop                            pause=true pkg=store user="[USER_ID]"
DEBU[Nov 18 18:01:52.885] Requesting  GET /mail/v4/messages/[META_ID]  pkg=pmapi userID="[USER_ID]"
ERRO[Nov 18 18:01:53.274] list message build: illegal base64 data at input byte 46  cmd=ListMessages metaID="[META_ID]" pkg=imap
```

## Steps to Reproduce

* Launch the bridge with: ``protonmail-bridge --cli --log-level debug-client``.
* Send an IMAP4 ``FETCH`` command.

## Context (Environment)

I am trying to backup my emails on a Linux server (Debian), using the latest version of the Protonmail bridge.

**Comment by jameshoulahan** [comment]
Hi @mesca and thanks for the report. The error comes from within the `(*imapMailbox).buildMessage(...)` method and can only originate in `(*Message).Decrypt(...)` (such an error may also come from `(*Attachment).Decrypt(...)` but your logs don't show that we have fetched the encrypted attachment yet). 

The only way this base64 error could happen within `(*Message).Decrypt(...)` is if the message is a legacy message.

Could you perhaps let me know how old this message is (i.e. how long it's been on proton servers for)? That would help me confirm my suspicion.

**Comment by mesca** [comment]
I had two messages in my `Sent` folders, one from Apr 2014, the other from Jan 2020. Both failed. All other messages seem to have been fetched successfully, including messages as far as 2014.

**Comment by andrzejsza** [comment]
a year later - we had no other reports like this and so decided not to change the approach - go-message will try to decode anything it sees which is base64 or quoted-printable. if it can't, it returns an error, so this works as expected.
