### ISSUE TITLE
Import-Export tool - migrate each message only once

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#134]
I already mentioned it somewhere, but the Import-Export tool does not detect if the same message is not present multiple times and thus downloads it, parsers it and uploads it several times. The server does not duplicate it, but I am currently remigrating my messages with latest Import-Export toot and it is going to take a really long time, as I am migrating around 140k messages instead of around 60k.

The error reports also look worse as it reports much more errors then there are actually failed messages because if a message fails and is present multiple times, it fails each time. And all of these failures are counted.

**Comment by exander77** [comment]
@jameshoulahan I would also report here about speed, it took around 13.5 hours to migrate 140k emails. So overall 0.35s per email. If some `Message-Id` deduplication was introduced, it would significantly reduce total time.

**Comment by jameshoulahan** [comment]
Hi @exander77, local message deduplication is something we are already actively scoping out as a potential upcoming feature. Thanks for the feedback, this helps us gauge customer impact.

Regarding speed, that's not too bad I suppose. I estimate the slow antlr runtime of the date/address parser contributes to maybe ~0.1s per email. We have timing metrics in the debug-level logs with individual measurements for things like `load`, `fetch`, `parse`, `encrypt`, `upload` etc. I wonder what the average `parse` duration is.

**Comment by exander77** [comment]
> Hi @exander77, local message deduplication is something we are already actively scoping out as a potential upcoming feature. Thanks for the feedback, this helps us gauge customer impact.
> 
> Regarding speed, that's not too bad I suppose. I estimate the slow antlr runtime of the date/address parser contributes to maybe ~0.1s per email. We have timing metrics in the debug-level logs with individual measurements for things like `load`, `fetch`, `parse`, `encrypt`, `upload` etc. I wonder what the average `parse` duration is.

If you give me info on how to get these stats, I can rerun to see how it performs.

Btw, it would be good If either all or failed messages could be passed to third party application like `reformime`, this is how `imapsync` does it, `reformime` could fix a lot of these failed messages, by removing some of the problems.

**Comment by jameshoulahan** [comment]
You should be able to run the application with `-l debug` to get those log messages.

**Comment by andrzejsza** [comment]
hi @exander77 . so there are to separate issues here:
- as @jameshoulahan pointed out, we consider the speed acceptable, so won't be looking into imrovements there;
- as for your main point - skipping dups. we agree it would be a good improvement, but are not planning to look into in the nearest future.
with the above in mind, I'll close this ticket.
