### ISSUE TITLE
Application does not advertise third party licenses as required

### ISSUE THREAD

**Issue by kortschak** [ProtonMail/proton-bridge#135]
The bridge has a dependency on a variety of third party packages licensed under a variety of license including LGPL, BSD-3 and MIT. All three (depending on the definition of "software" in the MIT license) require that a copy of the license notice be provided with copies of the application. This is not done; the application *does* point to the package names, but does not provide or link to the license documents or notices.

I've raised this internally since before 1.4 with the intention that it be resolved quietly. This hasn't happened, so I am filing this publicly now.

**Comment by andrzejsza** [comment]
Thanks for raising this again. As licence users we believe to be transparent about our dependencies as per:
https://github.com/ProtonMail/proton-bridge/blob/master/COPYING.md
To make sure that there are no misunderstandings, we will add relevant information about GPLv3 to Bridge's GUI.

**Comment by andrzejsza** [comment]
We've just added the information about the licence to Bridge's GUI (the footer of the `help` tab) and that's now live in the recent beta (1.5.4).

**Comment by kortschak** [comment]
Thanks.
