### ISSUE TITLE
ProtonMail Bridge corrupts mail headers containg "Autocrypt" headers

### ISSUE THREAD

**Issue by dsommers** [ProtonMail/proton-bridge#138]
When copying mails from an existing IMAP server in Thunderbird to a ProtonMail account via ProtonMail bridge, mails are corrupted if the mail headers contains a larger "Autocrypt:" header.

## Steps to Reproduce
1.  Send an e-mail to a "normal" unencrypted server providing IMAP access from Thunderbird with Engimail configured and Autocrypt enabled.
2. Verify that the sent mail contains a header line like this:

        Autocrypt: addr=john.doe@example.net; keydata=
              [...large base64 blob...]

   My `Autocrypt` headers contains 72 lines of base64 encoded data, roughly 5kiB

3.  Ensure ProtonMail Bridge is configured and setup properly in Thunderbird
4.  Copy this mail (I've seen this in mails from the "Sent" folder) to an ProtonMail folder 
5.  Observe the mail stored in ProtonMail is hard to decode, lacks the Autocrypt header and the last few lines of the Autocrypt header is visible in the body text, together with the rest of the mail headers.

## Version Information
ThunderBird  68.12.0 (64-bit) on RHEL 7
Enigmail 2.1.8
ProtonMail Bridge v1.5.2 (installed via flatpak from flathub.org)

## Context (Environment)
I cannot migrate properly to ProtonMail

## Possible Implementation
Improve header parsing in ProtonMail / ProtonMail Bridge.

**Comment by dsommers** [comment]
I added the "Headers Tools Lite" add-on to Thunderbird and edited troublesome mails, removing the `Autocrypt` header.  Then it was possible to copy it without issues to ProtonMail.

**Comment by andrzejsza** [comment]
issue relates to https://github.com/ProtonMail/proton-bridge/issues/146

**Comment by jameshoulahan** [comment]
hi @dsommers, this is likely resolved with the latest 1.5.6-beta as there was a bug in the go-message library we use.
