### ISSUE TITLE
Importing emails fails when the addresses in the To header are separated by a semi-colon

### ISSUE THREAD

**Issue by mberk** [ProtonMail/proton-bridge#139]
## Expected Behavior
I understand that the only acceptable separator according to RFC 5322 is a comma. However, it would be nice if the importer could tolerate this scenario

## Current Behavior
These emails fail to import with the following error:

> failed to import: failed to parse message: failed to parse message header: failed to parse to: error parsing rfc5322 input: no viable alternative at input 'a@b.com;'

## Possible Solution
Manually editing an example .eml file and replacing the semi-colons with commas allow the email to be successfully imported.

It's not clear to me whether the design philosophy would be for this scenario to be tolerated in the importer or to be tolerated in https://github.com/ProtonMail/go-rfc5322/. 

## Steps to Reproduce

1. Create a directory containing a .eml file with the following contents:

```
To: a@b.com; c@d.com
From: e@f.com
Date: Fri, 11 Dec 2020 00:00:00 +0000

```
2. Use the Import local files option on the directory

## Version Information
Import-Export app Elbe 1.2.2

## Context (Environment)
Over the years, I have received about a hundred emails where the separator in the address list is a semi-colon rather than a comma and it is essential for me that I can import all of my emails before permanently switching to ProtonMail.

## Possible Implementation
Do a string replace in `parseMessageHeader` before calling `rfc5322.ParseAddressList`

**Comment by andrzejsza** [comment]
as you said, semicolon are forbidden by rfc5322. thanks for the suggestion, but we won't be implementing this.

**Comment by mberk** [comment]
Personally, I don't see the point in providing an import tool that can only handle RFC 5322 compliant emails. The emails I describe are real emails observed in the wild.

Fortunately, I have the skills to fork this repository and modify the parser appropriately but I don't think you're going to win many customers making it this difficult to migrate to ProtonMail.

**Comment by bartbutler** [comment]
The problem is the semicolons have semantic meaning in emails and they aren't used as email address separators:

3.4.6.  BRACKETING CHARACTERS
     
        There is one type of bracket which must occur in matched pairs
        and may have pairs nested within each other:
     
            o   Parentheses ("(" and ")") are used  to  indicate  com-
                ments.
     
        There are three types of brackets which must occur in  matched
        pairs, and which may NOT be nested:
     
            o   Colon/semi-colon (":" and ";") are   used  in  address
                specifications  to  indicate that the included list of
                addresses are to be treated as a group.
     
            o   Angle brackets ("<" and ">")  are  generally  used  to
                indicate  the  presence of a one machine-usable refer-
                ence (e.g., delimiting mailboxes), possibly  including
                source-routing to the machine.
     
            o   Square brackets ("[" and "]") are used to indicate the
                presence  of  a  domain-literal, which the appropriate
                name-domain  is  to  use  directly,  bypassing  normal
                name-resolution mechanisms.

This was pulled from RFC822 (https://tools.ietf.org/html/rfc822), from 1982. In other words, semicolons have *never* been a valid email separator, has never been seen by us in the wild, and mean something else, which is why implementing support for this use case is probably not in the cards.

**Comment by mberk** [comment]
Saying you've never seen it in the wild when I, a user, am reporting a case of it in the wild seems a bit of a nonsensical argument to me.

You cannot possibly believe that every email in the wild is RFC 5322 compliant which the import tool currently enforces as far as the Subject, From, To, Reply-To, CC, BCC and Date headers are concerned. This is not the only issue I've had while importing, I have also encountered emails where:

* The date field cannot be parsed because the day of the week has not been abbreviated
* Special symbols (specifically a colon) have appeared in a display-name

If you want to say that you only support importing compliant emails then we can leave it at that but I am feeding back to you that your average user is going to have issues importing that they are not going to understand and it's not going to be a good initial experience of using ProtonMail.

**Comment by exander77** [comment]
I think @jameshoulahan should comment on this if there is an easy way to support it in new parser. I do not see a problem from the top of my head.

**Comment by jameshoulahan** [comment]
The [change](https://github.com/ProtonMail/go-rfc5322/commit/8d9d7c881b537fffb3248b96cd03471903ba69dc) was trivial to make to the go-rfc5322 package to support semicolon delimiters so I did it. Support should arrive in upcoming releases of bridge/i-e.
