### ISSUE TITLE
[Linux] Disable mandatory system password manager usage

### ISSUE THREAD

**Issue by Germano0** [ProtonMail/proton-bridge#14]
There are users that do not use the system password manager, but instead use their own password manager like [KeepassXC](https://github.com/keepassxreboot/keepassxc/). They has to be able to not use the system password manager, that the Protonmail bridge forces to use instead.

**Comment by exander77** [comment]
Integration with KeepassXC would be great. I second that.

**Comment by sirius-c** [comment]
Depending on how the Bridge accesses the keyring, this might already be possible as per [this feature](https://github.com/keepassxreboot/keepassxc/pull/2726) at least on Linux. KeypassXC can act as the system keyring.

**Comment by ciehanski** [comment]
KeepassXC has [Secret Service Integration API](https://specifications.freedesktop.org/secret-service/latest) via DBus that could be hooked into and emulated as the system keyring for Proton Bridge. [Here](https://www.cogitri.dev/posts/03-keepassxc-freedesktop-secret/) is a quick explanation and walkthrough on how to enable the Secret Service within the KeepassXC client to enable communication via the API. A Go package ([go-dbus-keyring](https://github.com/ppacher/go-dbus-keyring)) already exists by [ppacher](https://github.com/ppacher) that I believe could be a great starting point regarding implementing this in Proton Bridge. Hope this helps!

**Comment by Germano0** [comment]
@ciehanski very nice, I think you may want to open a new ticket for that feature since the main purpose of this ticket is to remove the mandatory password manager on the bridge

**Comment by ciehanski** [comment]
@Germano0 sounds good. I'll go ahead and gather some more resources and create a new issue.

**Comment by barthr** [comment]
Any update on this? I'm using KDE + KDE Wallet. Is there a way to hook into how proton-bridge stores the credentials.

**Comment by Kazark** [comment]
I'm also on KDE and it would be nice to have native support for KWallet. I've installed `pass` but haven't got it working with that yet either.

**Comment by Germano0** [comment]
> Failure: failed to add user to credentials store: cannot create an item in a locked collection
Users must be able to choose to not store credentials anywhere

**Comment by andrzejsza** [comment]
as per https://github.com/ProtonMail/proton-bridge/pull/217 will close this issue for now - keep us posted if any problem but might be best to open a new issues with new reports just to keep things clean.
