### ISSUE TITLE
protonmail-bridge resets IMAP subscriptions

### ISSUE THREAD

**Issue by dsommers** [ProtonMail/proton-bridge#140]
When unsubscribing to certain folders in Thunderbird, if there are any folder updates or the bridge is restarted, all unsubscribed folders are resubscribed.

## Expected Behavior
Unsubscribed folders should stay unsubscribed.

## Steps to Reproduce
1.  Start Thunderbird and ProtonMail-bridge, configure Thunderbird to use bridge
2.  Unsubscribe to "All Mail"
3.  Restart bridge or do folder updates via ProtonMail webmail
4.  Restart Thunderbird and Bridge

## Version Information
thunderbird-68.12.0-1.el7_8.x86_64
ProtonMail Bridge v1.5.2

## Context (Environment)
Certain folders are for long-term archives and is not needed to be visible in the IMAP client on a daily basis.  In addition, the "All Mail" is (for me) just an annoyance, I never really use it - so I don't want it to take up space in an already long enough folder list.

## Detailed Description
Preserve the IMAP folder subscription state properly.

**Comment by andrzejsza** [comment]
@dsommers yes, we do have the full support of IMAP subscriptions in our backlog already (for internal reference - GODT-367). we will try to look into this alongside broader refactor and keep you posted.

**Comment by mipak** [comment]
since "All Mail" seems the main issue here (like I have) .. #152 might solve that too

**Comment by dsommers** [comment]
> since "All Mail" seems the main issue here (like I have) .. #152 might solve that too

I don't think they are related at all. #152 is about the possibility to disable the "All mails" folder feature.  This ticket is about IMAP folder subscriptions not being preserved.  So if you go into the folder subscriptions in the IMAP based mail client and unsubscribes certain folders, they re-appear again after a restart of the Bridge and IMAP client.  The "All mail" folders in this regards is just like any other folder - a collection of mails, and the subscription of this folder is also not preserved.

**Comment by andrzejsza** [comment]
and this is also handled with V3. can you confirm/close if so?

**Comment by dsommers** [comment]
I have tested this running commit 48480bc8391cee5b1797411e68d0821159f9b4fc since Dec 14 in a non-gui setup. This seems to preserve IMAP subscriptions now, so I believe this can be closed now.  Tested with explicitly unsubscribing to several folders and labels, their subscription status has been preserved through this test period.
