### ISSUE TITLE
'Clear keychain' doesn't remove 127.0.0.1 Root CA from macOS System keychain

### ISSUE THREAD

**Issue by tusing** [ProtonMail/proton-bridge#145]
The 'clear keychain' function does not remove all ProtonMail bridge information from the system keychain, such as the 127.0.0.1 Root CA.

## Expected Behavior

127.0.0.1 trusted Root CAs should be removed from the macOS System Keychain.

## Current Behavior

127.0.0.1 trusted Root CAs are not removed from the macOS System Keychain.

## Version Information

1.5.4

## Context (Environment)

- macOS 10.16 Big Sur
- ProtonMail Bridge 1.5.4
  - Clean install
    - cleared keychain and cache (including 127.0.0.1 root cert from macOS system keychain (#144))
    - logged out
    - removed `~/Library/Caches/ProtonMail Bridge`
  - No accounts added

**Comment by jameshoulahan** [comment]
"Clear keychain" refers to removing secrets from the OS keychain (on windows, the credential manager, on linux, either pass or gnome-keyring, and on macOS, the system keychain). However, on macOS we also put the IMAP/SMTP TLS certificate in the system keychain, and you're right, it would be good to also clean that up. Thanks!

**Comment by andrzejsza** [comment]
definitely, TLS certificate should also be cleaned up. for internal reference - GODT-952 (logged as a bug - I know it's an expected behaviour, but clearly confusing to the users).

**Comment by andrzejsza** [comment]
we were looking into this for some time but couldn't make this work. closing as blocked by Apple - as nice as it would be to have this done, we won't be spending more time here. any ideas are welcomed!
