### ISSUE TITLE
Feature request: offer MTA command-line functionality 

### ISSUE THREAD

**Issue by ploum** [ProtonMail/proton-bridge#149]
Unixes people looking to send emails from the command line need to configure mbsync/sendmail or similar client to connect to Protonmail Bridge. It is also useful for people using mutt, gnus, mu4e and similar clients. Configuring mbsync/sendmail with protonmailbridge involveds a convoluted process, mainly due to TLS handling.

It would make a lot of sense to cut the middleman and have a command to send mails directly using the bridge. As for credentials, it also makes sens to assume that the user running the bridge has access to the bridge password.

**Comment by dsommers** [comment]
This shouldn't be that hard to configure with Postfix.  The description here is untested, and taken mostly from memory.

Add a file `/etc/postfix/sasl_accounts` where you have:

    [127.0.0.1]:1025       {PM_BRIDGE_USERNAME}:{PM_BRIDGE_PASSWORD}

Create a hash-file with `postmap hash:/etc/postfix/sasl_accounts`
Add this line to `/etc/postfix/main.cf`

    smtp_sasl_password_maps = hash:/etc/postfix/sasl_accounts

For those mail addresses you want to go via PM Bridge this way, add lines like this to `/etc/postfix/transport`:

    example.com                    smtp:[127.0.0.1]:1025
    john.doe@exampe.net     smtp:[127.0.0.1]:1025

Create a hash map of this file as well, using `postmap hash:/etc/postfix/transport`  and ensure you have this line in `main.cf`

    transport_maps = hash:/etc/postfix/transport

Any mail going via the local Postfix instance will for selected recipients go via the PM Bridge.  You can also do similar tricks based on sender address (not just recipient address).  It's all pretty well described in the various Postfix docs: http://www.postfix.org/documentation.html.

Another good resource is this book: https://www.oreilly.com/library/view/postfix-the-definitive/0596002122/

**Comment by andrzejsza** [comment]
thanks for the above. not much more we can do here at this stage, closing.
