### ISSUE TITLE
Is it possible to recover a password using the bridge?

### ISSUE THREAD

**Issue by jakecoble** [ProtonMail/proton-bridge#150]
I've somehow lost my password (the password in my password manager doesn't work), but I *am* still logged in through the ProtonMail bridge, and I have an unencrypted copy of all my emails in a local mailbox.

If the bridge can authorize itself to the server, I imagine there could be a way to capture the request and adapt that to the web interface, thereby letting me log in and at least set a recovery email if not change the password entirely. Is this possible?

**Comment by jameshoulahan** [comment]
Hi @jakecoble. This isn't really possible. While bridge does store an API access token in your operating system's keychain, you will in any case need to re-authenticate before changing the password or setting a recovery email, which requires your current password, which you lost. I do advise you to contact customer support; although we do not have your password and thus cannot help you recover access to any messages (good thing you have them synced to your email client!), we may be able to help you reset your account (though that is left up to CS's discretion).
