### ISSUE TITLE
Multiple consecutive accesses of password manager annoying for hardware key users.

### ISSUE THREAD

**Issue by rimio** [ProtonMail/proton-bridge#153]
During startup on a system that also has pass installed, protonmail-bridge accesses the credentials 6 consecutive times for a single account. When using a hardware key that requires touching for each GPG operation this can get very annoying.

## Expected Behavior
I touch the hardware key once.

## Current Behavior
I touch the hardware key 6 times.

## Possible Solution
Cache the credentials across the startup procedure?

## Steps to Reproduce
1. Install pass and protonmail bridge
2. Populate hardware key with GPG secret keys
3. Activate mandatory touch for [E] key
4. Start bridge

## Version Information
```
INFO[0000] Run app                                       appName="ProtonMail Bridge" args="[protonmail-bridge --version]" build="2021-01-02T17:08:14+0200" pkg=cmd revision=9d576beeb8 runtime=linux version=1.5.4-git
ProtonMail Bridge version 1.5.4-git (9d576beeb8) 2021-01-02T17:08:14+0200
```

## Context (Environment)
N/A

## Detailed Description
N/A

## Possible Implementation
Sorry, I wish I knew Go.

**Comment by jameshoulahan** [comment]
This is fixed in bridge v3: we only access the keychain once at startup, to retrieve the vault decryption key. Once we have that, there's no need for further access to the keychain.
