### ISSUE TITLE
can't signin on arch

### ISSUE THREAD

**Issue by chovy** [ProtonMail/proton-bridge#156]
It says "no keyring manager is running" I'm using KDE

I installed pass with `sudo pacman -S pass` and ran `pass init <gpg-id>`

but i still can't setup an account.

**Comment by AlphaXyXy** [comment]
I'm having issues too, but it's more with the ProtonVPN subscription plan not working for me...

**Comment by jameshoulahan** [comment]
Hi @chovy, when using pass, if the gpg key you initialized it with has a passphrase, you'll need to ensure the passphrase is cached by the gpg daemon; bridge is unable to provide the passphrase via pinentry or such things. You will want to configure gpg daemon to cache the passphrase for a long period of time. Alternatively, though this is not recommended for obvious security reasons, you could initialise pass with a gpg key that has no passphrase.

And @AlphaXyXy, i'm not totally sure i understand your exact issue, but please note that you require a paid ProtonMail plan to use bridge -- only having a paid ProtonVPN plan doesn't suffice.

**Comment by chovy** [comment]
keyring daemon wasn't running. i did `pacman -S keyring` and rebooted.

**Comment by andrzejsza** [comment]
also, probably best to contact support@ for issues like that - they might need some more info to help with debugging.
