### ISSUE TITLE
Messages without labels or folder not really deleted

### ISSUE THREAD

**Issue by jaor** [ProtonMail/proton-bridge#158]
A mail with a label in the Trash is not deleted when removed from the Trash.

## Expected Behavior
If I put an unlabeled message in the Trash and delete it via IMAP (using e.g. offlineimap or mbsync), the message is deleted from the server, and cannot be found anymore.  Nor in the label or All Mail.  However, if i put a /labeled/ message in the Trash and delete it via IMAP, it still appears under the label (so it's not really deleted), and, what's worst, if I now delete its label (again, deleting it from its IMAP folder), it disappears from the label view, but it's still found in All Mail: despite the fact that i've removed it from Trash, it's still in the server.

## Current Behavior
I would expect the message to deleted for good, from everywhere, once i delete it from Trash, in the same way as using the web buttons works fine and deletes it even if it has a label.  

## Possible Solution
Always delete messages from everywhere when they're in the trash, regardless of whether they have labels or not. I would also prefer if a message were also deleted if it's not in any folder once its last label is deleted, be it in the Trash or not.

## Steps to Reproduce
1.  Create a sieve filter that puts an incoming message in Trash and adds to it a label
2.  Fetch the Trash folder from IMAP.  Delete the message with IMAP.
3.  See how the message is not in Trash anymore, but it's in the label "folder".  It has not been deleted.

## Version Information
Proton bridge 1.5.6  (but it's happened since at least 1.0)

## Context (Environment)
The way this works, it's extremely easy to end up with lots of "ghost" messages in the server that you thought were deleted, and forces one to delete a message 3 times (once from the Trash, once from the label and once from "All Mail".

Thanks!

**Comment by andrzejsza** [comment]
closing as won't fix - this is expected behaviour and as far as we undertand we are following the rfc here.
