### ISSUE TITLE
There is something seriously wrong in ProtonBridge cache and working with larger number of e-mails

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#159]
From time to time, I have to completely remove Bridge cache as it stops working on a larger amount of e-mails. ThunderBird reports that operation failed and the server got disconnected. It even hangs a ThunderBird menu for several minutes as it probably waits for any kind of response.

I have been trying to remove e-mails from previous import for the whole day.

I am using the latest version, but the problem was there before. If anything it has gotten worse.

Currently, I am trying after cache clearing, but I am not sure if it is even running. No error, but I don't see any progress after 30 minutes. Still, only 500 deleted conversation from during the day. I have around 25 000 to go.

I also think that ProtonBridge should inform about current and pending operations as I have no way to see what is going on.

I have produced 2MB log, but it is overwhelmingly filled with:
```
{"level":"error","msg":"cannot upgrade connection: remote error: tls: bad certificate\n","pkg":"server-imap","time":"2021-01-24T02:01:46+01:00"}
```
Currently, 13108 out of 13200 lines contains this error message.

In the rest 82 lines, not useful information is present, error messages:
```
  13197 "cannot upgrade connection: remote error: tls: bad certificate\n"
      1 "Problem to load store cache"
      1 "Could not list API labels. Trying with local labels."
      1 "Could not initialise user"
      1 "Could not initialise store, attempting to close"
      1 "Could not initialise store addresses"
      1 "Could not get user addresses from API"
      1 "Could not get addresses and address IDs"
      1 "Could not authorize user"
      1 "Cannot refresh token"
      1 "Cannot load cert, generating a new one"
```
I would be testing a new version of Import-Export tool, but I haven't even removed the original e-mails yet.

**Comment by exander77** [comment]
I have cleared ProtonBridge cache several times, but the current situation is that ThunderBird thinks e-mails were removed and does not show them, but they are still in ProtonMail.

Maybe it is related to message UIDs?

**Comment by exander77** [comment]
Any ideas on how to fix it? Last time, I had to remove the ThunderBird profile and redownload all e-mails. I have tried, restart Bridge, clear its cache, restart ThunderBird.

**Comment by exander77** [comment]
The situation didn't rectify itself after 10 days.

There is a schisma between Protonmail and ThunderBird. On server e-mails are still there, ThunderBird thinks they were moved.

I just cannot remove my account from ThunderBird every time I need to delete a large number of e-mails.

**Comment by andrzejsza** [comment]
sorry for the delay on this. you are right - clearing cache in it's current form is indeed causing issues between the clients and Bridge.
moving forward we will:
- redesign the local cache
- remove the option of clearing it from Bridge - when the users do that but don't reconfigure their clients, there is a high chance of having a discrepancy between what client is expecting and what Bridge is providing.
since there is nothing specific do to here, closing.
