### ISSUE TITLE
Support NATIVE building

### ISSUE THREAD

**Issue by slashbeast** [ProtonMail/proton-bridge#16]
Hi,

Currently the build system support only building of binary vendorized package that uses external binary Qt libraries. Even if one were to flex and run
```
    go build cmd/Desktop-Bridge/main.go
```
It will crash with
```
  # github.com/therecipe/qt/core
  core.cpp:10:3: error: #error ------------------------------------------------------------------
     10 |  #error ------------------------------------------------------------------
        |   ^~~~~
  core.cpp:11:3: error: #error please run: '$(go env GOPATH)/bin/qtsetup'
     11 |  #error please run: '$(go env GOPATH)/bin/qtsetup'
        |   ^~~~~
  core.cpp:12:3: error: #error more info here: https:
     12 |  #error more info here: https://github.com/therecipe/qt/wiki/Installation
        |   ^~~~~
  core.cpp:13:3: error: #error ------------------------------------------------------------------
     13 |  #error ------------------------------------------------------------------
        |   ^~~~~
  core.cpp:15:10: fatal error: QAbstractAnimation: No such file or directory
     15 | #include <QAbstractAnimation>
        |          ^~~~~~~~~~~~~~~~~~~~
  compilation terminated.
```
This by no means allow to build a proper distribution package, and seems like that's also the reason why binary Proton Bridge actually ships with dozens of Qt libs that are not even linked.

Please be so kind and support proper, non-binary-package-only building, in a way that the client will use system-wide Qt and other libraries, rather than use precompiled binary blobs.

**Comment by lsalvadore** [comment]
I would like to support the request: I am trying to port the software to FreeBSD and I am getting the same problem.

**Comment by emersion** [comment]
Maybe this helps: https://github.com/therecipe/qt/wiki/Installation-on-Linux#your-system-package-managers-version-without-android-support

**Comment by cuthix** [comment]
Closing this as with `br-1.5.4` we now support building with native libs. You need to follow `therecipe/qt` and set `QT_API=5.X.Y` then `make build` will use native libs.

We will add build instructions in future.
