### ISSUE TITLE
protonmail bridge Linux doesn't load bodies that don't have an attachment

### ISSUE THREAD

**Issue by justinfiore** [ProtonMail/proton-bridge#162]
I am trying to get protonmail-bridge working on Ubuntu 20.04.1 LTS with NextCloud Mail as the email client.
I have the following issue (which is also described in this NextCloud issue: https://github.com/nextcloud/mail/issues/2545)
That issue was resolved because there is a workaround to use hydroxide. However, hydroxide is so slow it is unusable.

The behavior is that when NextCloud Mail is configured to use the protonmail-bridge that:
1) The Email List and Subjects load fine
2) When attempting to load the body of a message that has an attachment, it loads just fine
3) (The Problem) When attempting to load the body of a message that DOES NOT have an attachment, it fails to load entirely. 

## Expected Behavior
Email bodies should load correctly when using the protonmail-bridge regardless of whether or not they have an Attachment.

## Current Behavior
Only emails without an attachment actually load their bodies.
I have no idea if this is specific to NextCloud or if it is specific to the protonmail-bridge on Linux as I haven't been able to try using another email client with protonmail-bridge for linux because I have a headless server.
However, switching to use the hydroxide open-source proton mail bridge, DOES correctly load bodies all the time (though it is terribly slow and unusable).

## Possible Solution
I'm not sure.

## Steps to Reproduce
1.  Install protonmail-bridge for linux
2. Configure it by adding your account
3. Install NextCloud (though it may happen with other email clients) and install the Mail app
4. Configure NextCloud to allow self-signed certificates for the Mail app: by setting ` 'app.mail.verify-tls-peer' => false,` in the `config.php`
5. Configure the Mail App to use the bridge settings (STARTTLS, 127.0.0.1 and the appropriate ports and bridge password.)
6. Try to load email bodies that have no attachments (they don't load)

## Version Information
ProtonMail Bridge version 1.5.7 (645a8257d9) 2021-01-22T11:32:15+0000
Ubuntu 20.04.1 LTS (Focal Fossa)
Nextcloud 20.0.4
NextCloud Mail: 1.8.0

## Context (Environment)
I'm trying to use NextCloud Mail as a client for my Proton Mail

## Detailed Description
I don't know

## Possible Implementation
I don't know

## Logs

These are the logs from the protonmail-bridge with level DEBUG
```
>>> DEBU[Jan 26 19:10:29.471] Creating new IMAP user                        address=<redacted>@protonmail.com pkg=imap
DEBU[Jan 26 19:10:29.471] Retrieving address info from store            pkg=store user="EQjucVlICT3mJba9ebKnycJx0TANhjLnTPtbYM7FBYtsO3maLLSe0-BQnBl3-OXpUndg1mdtpa-0u_HvHGkgvQ=="
DEBU[Jan 26 19:10:29.472] Creating new IMAP user                        address="IdJWi5DEgk_Ut7gY9rNvwfzwyjBxQkpZcJpFII3oYYI1HV0WsszfmxjwDdVW0CQtvs-gWHxrfCPaD1i0QGgD7A==" pkg=imap
DEBU[Jan 26 19:10:29.473] DB counts                                     address="IdJWi5DEgk_Ut7gY9rNvwfzwyjBxQkpZcJpFII3oYYI1HV0WsszfmxjwDdVW0CQtvs-gWHxrfCPaD1i0QGgD7A==" err="<nil>" pkg=imap status-label=5 total=44 unread=7 unreadSeqNum=6 user="EQjucVlICT3mJba9ebKnycJx0TANhjLnTPtbYM7FBYtsO3maLLSe0-BQnBl3-OXpUndg1mdtpa-0u_HvHGkgvQ=="
INFO[Jan 26 19:10:29.477] Pausing event loop                            pause=true pkg=store user="EQjucVlICT3mJba9ebKnycJx0TANhjLnTPtbYM7FBYtsO3maLLSe0-BQnBl3-OXpUndg1mdtpa-0u_HvHGkgvQ=="
INFO[Jan 26 19:10:29.488] Pausing event loop                            pause=false pkg=store user="EQjucVlICT3mJba9ebKnycJx0TANhjLnTPtbYM7FBYtsO3maLLSe0-BQnBl3-OXpUndg1mdtpa-0u_HvHGkgvQ=="
INFO[Jan 26 19:10:29.489] Pausing event loop                            pause=true pkg=store user="EQjucVlICT3mJba9ebKnycJx0TANhjLnTPtbYM7FBYtsO3maLLSe0-BQnBl3-OXpUndg1mdtpa-0u_HvHGkgvQ=="
INFO[Jan 26 19:10:29.500] Pausing event loop                            pause=false pkg=store user="EQjucVlICT3mJba9ebKnycJx0TANhjLnTPtbYM7FBYtsO3maLLSe0-BQnBl3-OXpUndg1mdtpa-0u_HvHGkgvQ=="
INFO[Jan 26 19:10:29.501] Pausing event loop                            pause=true pkg=store user="EQjucVlICT3mJba9ebKnycJx0TANhjLnTPtbYM7FBYtsO3maLLSe0-BQnBl3-OXpUndg1mdtpa-0u_HvHGkgvQ=="
ERRO[Jan 26 19:10:29.502] list message build: wrong section 1           cmd=ListMessages metaID="3XMcntTNzWxgF798_Q1BeKKpeIC5pt8KEkLkmC_EfMrJul4T5su4A-GmR_kUui4DroCaRX45ZZ3P_3BAho23vw==" pkg=imap
INFO[Jan 26 19:10:29.511] Pausing event loop                            pause=false pkg=store user="EQjucVlICT3mJba9ebKnycJx0TANhjLnTPtbYM7FBYtsO3maLLSe0-BQnBl3-OXpUndg1mdtpa-0u_HvHGkgvQ=="
ERRO[Jan 26 19:10:29.512] cannot list messages (true, 41, [BODY.PEEK[1] BODY.PEEK[1.MIME] UID]): list message build: wrong section 1  pkg=imap
DEBU[Jan 26 19:10:29.517] List to expunge is empty                      addrID="IdJWi5DEgk_Ut7gY9rNvwfzwyjBxQkpZcJpFII3oYYI1HV0WsszfmxjwDdVW0CQtvs-gWHxrfCPaD1i0QGgD7A==" labelID=5 pkg=store
DEBU[Jan 26 19:10:29.517] IMAP client logged out address IdJWi5DEgk_Ut7gY9rNvwfzwyjBxQkpZcJpFII3oYYI1HV0WsszfmxjwDdVW0CQtvs-gWHxrfCPaD1i0QGgD7A==  pkg=imap
DEBU[Jan 26 19:10:29.518] Deleting IMAP user                            address=<redacted>@protonmail.com pkg=imap

```

**Comment by justinfiore** [comment]
I looked at some additional logs to try to see the difference between when it works and when it fails.

Logs from when the message body loads (because there are attachments in the message)
```
INFO[Jan 26 19:26:43.566] Pausing event loop                            pause=true pkg=store user="EQjucVlICT3mJba9ebKnycJx0TANhjLnTPtbYM7FBYtsO3maLLSe0-BQnBl3-OXpUndg1mdtpa-0u_HvHGkgvQ=="
DEBU[Jan 26 19:26:43.567] Requesting  GET /mail/v4/messages/bWjhBlSdI_6k6lq92M8atYXUnX7lMOrf4LmONVaSKD7EUbn6pt1CMBZjJX-k3vHuNOUdh53SBzqX2emzmdI-WA==  pkg=pmapi userID="EQjucVlICT3mJba9ebKnycJx0TANhjLnTPtbYM7FBYtsO3maLLSe0-BQnBl3-OXpUndg1mdtpa-0u_HvHGkgvQ=="
DEBU[Jan 26 19:26:43.880] Requesting  GET /mail/v4/attachments/OksbQLYNnpGDf2cGLWCqOtlJ1iMBFwVQFxzpb4mIj6RawoXv1kRVTjGL23wXi0-B0JK8P3jfQarQQneOAj7Suw==  pkg=pmapi userID="EQjucVlICT3mJba9ebKnycJx0TANhjLnTPtbYM7FBYtsO3maLLSe0-BQnBl3-OXpUndg1mdtpa-0u_HvHGkgvQ=="
DEBU[Jan 26 19:26:43.880] Requesting  GET /mail/v4/attachments/18SL3cBAjL4B_vjKVm6JFEtWM0qJKllDA4nUxuJwRGC6EOSY_S5POB6nAit2MUMmiKFqBJousB5M3JtESTiIWw==  pkg=pmapi userID="EQjucVlICT3mJba9ebKnycJx0TANhjLnTPtbYM7FBYtsO3maLLSe0-BQnBl3-OXpUndg1mdtpa-0u_HvHGkgvQ=="
I
```

Logs from when the message body doesn't load (no attachment in the message)
```
INFO[Jan 26 19:26:41.644] Pausing event loop                            pause=true pkg=store user="EQjucVlICT3mJba9ebKnycJx0TANhjLnTPtbYM7FBYtsO3maLLSe0-BQnBl3-OXpUndg1mdtpa-0u_HvHGkgvQ=="
DEBU[Jan 26 19:26:41.644] Requesting  GET /mail/v4/messages/vHMIUaBKO7dbLhYWROjuM6Ak_ekCo2_gICTAyh2fcWmUd1vp_Rfzf01bhE4W9F4LQhZUtOrBgVanWdwQ7f9h3g==  pkg=pmapi userID="EQjucVlICT3mJba9ebKnycJx0TANhjLnTPtbYM7FBYtsO3maLLSe0-BQnBl3-OXpUndg1mdtpa-0u_HvHGkgvQ=="
ERRO[Jan 26 19:26:41.948] list message build: wrong section 1           cmd=ListMessages metaID="vHMIUaBKO7dbLhYWROjuM6Ak_ekCo2_gICTAyh2fcWmUd1vp_Rfzf01bhE4W9F4LQhZUtOrBgVanWdwQ7f9h3g==" pkg=imap
INFO[Jan 26 19:26:41.948] Pausing event loop                            pause=false pkg=store user="EQjucVlICT3mJba9ebKnycJx0TANhjLnTPtbYM7FBYtsO3maLLSe0-BQnBl3-OXpUndg1mdtpa-0u_HvHGkgvQ=="
ERRO[Jan 26 19:26:41.948] cannot list messages (true, 32, [BODY.PEEK[1] BODY.PEEK[1.MIME] UID]): list message build: wrong section 1  pkg=imap
DEBU[Jan 26 19:26:41.954] List to expunge is empty                      addrID="IdJWi5DEgk_Ut7gY9rNvwfzwyjBxQkpZcJpFII3oYYI1HV0WsszfmxjwDdVW0CQtvs-gWHxrfCPaD1i0QGgD7A==" labelID=5 pkg=store
```

So I suspect there is something wrong with the code path that is loading messages with no attachments or something like that.
But I don't know enough Go to really grok it.
But I am happy to test out any unofficial builds to see if changes resolve the problem.

**Comment by ericLemanissier** [comment]
I don't know if it's related, but I tried for weeks  to interface osticket with protonmail bridge, and failed miserably. I stopped when I realized php's imap implementation was broken and not able to load properly emails from protonmail's bridge.  If nextcloud relies on https://www.php.net/manual/fr/book.imap.php for parsing emails, then the bug should be reported on https://bugs.php.net/
(For osticket, the workaround was to use https://docs.python.org/3/library/imaplib.html instead of php's imap implementation, but it may not be possible with nextcloud)

**Comment by justinfiore** [comment]
@ericLemanissier if it was a PHP bug, why would it work correctly with hydroxide and not work with protonmail-bridge?

**Comment by ericLemanissier** [comment]
What confuses php is the way multipart is used. Maybe protonmail-bridge and hydroxide are using a different multipart arrangement gor emails without attachement?

**Comment by justinfiore** [comment]
Thanks

**Comment by miltonhowe** [comment]
This looks like it might be the same problem as #137 . 
I am experiencing the same issue. It seems to fail only on single-part messages.
The OP posted a suggested resolution on the other issue.

**Comment by justinfiore** [comment]
@miltonhowe yes, it does look like the same problem. 
Hopefully a fix can be made soon. 
I'm not proficient in Go or I would take a crack at it. 
But definitely willing to test out any proposed solutions on my end.

**Comment by andrzejsza** [comment]
yes, as #137 is done this should also no longer be a problem.
