### ISSUE TITLE
Bridge ignoring `PASSWORD_STORE_DIR` in 1.6.3

### ISSUE THREAD

**Issue by arcresu** [ProtonMail/proton-bridge#168]
I use pass with a non-default password store location. This is supported by pass by setting the env variable `PASSWORD_STORE_DIR`. In previous versions of Bridge this worked fine, but upon updating to v1.6.3 it seems that Bridge will only attempt to look in the default password store, ignoring `PASSWORD_STORE_DIR` (maybe the environment in which pass is invoked was changed recently?).

## Expected Behavior
Bridge should forward `PASSWORD_STORE_DIR` from the environment when invoking `pass`.

## Current Behavior
Bridge only allows accounts to be added if the default password store is initialised (`PASSWORD_STORE_DIR= pass init $GPGKEY`), even if there's an initialised password store at the location described by `PASSWORD_STORE_DIR`.

## Steps to Reproduce
1. Make sure that `~/.password-store/` does not exist.
2. Export `PASSWORD_STORE_DIR=~/.non-default-password-store`
3. Initialise the store with `pass init $GPGKEY`
4. Launch Bridge and attempt to add a user account.
5. An error message is shown in the UI and the terminal shows:
```
time="..." level=error msg="Failed to add new user" error="failed to add user to credentials store: pass not initialized: exit status 1: Error: password store is empty. Try \"pass init\".\n" pkg=users
```
Looks like [another user has this issue](https://github.com/ProtonMail/proton-bridge/issues/31#issuecomment-772589411).

## Version Information
Installed .deb packages, on Debian sid.

Problem exists in Bridge 1.6.3-1. Worked fine before upgrading from 1.5.7-1.

**Comment by jameshoulahan** [comment]
Hi @arcresu, thanks for the report. I'm trying to reproduce this on Ubuntu 20.04.1 but cannot; the password store is correctly used as per the environment variable.

Could you describe how you are launching bridge and how you have set the environment variable?

**Comment by andrzejsza** [comment]
it works for us - if your problem still persists, please get in touch with support for further debugging.
