### ISSUE TITLE
cli only build

### ISSUE THREAD

**Issue by kausban** [ProtonMail/proton-bridge#17]
Hi. Is there a correct way to build proton-bridge with only cli capabilities?

Is just adding 'nogui' to 'BUILD_TAGS' the way to go? I have this so far: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=protonmail-bridge-nogui

basically doing this: sed -i 's/pmapi_prod/pmapi_prod nogui/' Makefile

**Comment by exander77** [comment]
Have you read the build guide? It is mentioned there: `make run`
You don't have to hack anything.

**Comment by kausban** [comment]
I have. You'd notice its for testing and doesn't generate a binary - at least that isn't obvious to me. I tried it and it does exactly what it says drops me in a CLI interactive bridge menu. - I got the idea to include that flag from the makefile after all.

I would like to generate a binary that I can package and use on a daily basis. I trying to find out if there is a correct way of doing that.

**Comment by jameshoulahan** [comment]
Yes, building with the `nogui` build tag is the ideal way to do this for now. This build tag will build a cli-only binary.

**Comment by kausban** [comment]
That would be really nice and convenient. Thanks!
