### ISSUE TITLE
Update can't be GPG verified

### ISSUE THREAD

**Issue by rigwild** [ProtonMail/proton-bridge#171]
Hi!

Updating the bridge from v1.5.7 to v1.6.3 fails using the "An update is available" prompt.

## Expected Behavior

Updates successully

## Current Behavior

Update failed.

The update file can't be gpg verified. Here are the logs:

```
{"level":"warning","msg":"Cannot verify update file C:\\Users\\myuser\\AppData\\Local\\protonmail\\bridge\\c11\\updates\\bridge_upgrade_windows.tgz: openpgp: invalid data: tag byte does not have MSB set","pkg":"bridgeUtils/updates","time":"2021-02-18T12:33:04+01:00"}
{"level":"error","msg":"update progress: cannot verify signature","pkg":"frontend-qt","time":"2021-02-18T12:33:04+01:00"}
```

### Issue with signature check?
I found this issue, but I don't know if it is related: https://github.com/helm/helm/issues/2843#issuecomment-631001132

### Expired key?
The published GPG key at https://protonmail.com/download/bridge_pubkey.gpg expired on the 2021-02-02.

I found a signature which extends the duration to 2022-02-02 here: http://keys.gnupg.net/pks/lookup?op=vindex&fingerprint=on&search=0xE2C75D68E6234B07

## Steps to Reproduce

1. Open the app
2. Click "Update"
3. Fail

## Version Information
Updating from v1.5.7 to v1.6.3.

## Context (Environment)
Edition	Windows 10 Pro
Version	20H2
OS build	19042.804

Thank you!

**Comment by andrzejsza** [comment]
that was a bug on our side, now fixed.

**Comment by rigwild** [comment]
> that was a bug on our side, now fixed.

Nice! Might as well update the key there https://protonmail.com/download/bridge_pubkey.gpg to include the new expiration date.

**Comment by andrzejsza** [comment]
yep, thanks for pointing this out. done.
