### ISSUE TITLE
Looks like in 1.6.5 go.mod and go.sum are not commited

### ISSUE THREAD

**Issue by molaeiali** [ProtonMail/proton-bridge#174]
## Expected Behavior
The source on 1.6.5 tag being built from Makefile

## Current Behavior
Getting an error when reaching to:
```
go install -v -tags=no_env github.com/therecipe/qt/cmd/...
```
Error
```
/home/ali/.go/pkg/mod/github.com/therecipe/qt@v0.0.0-20200701200531-7f61353ee73e/cmd/env/linux_amd64.go:5:8: no required module provides package github.com/therecipe/env_linux_amd64_513; to add it:
	go get github.com/therecipe/env_linux_amd64_513
/home/ali/.go/pkg/mod/github.com/therecipe/qt@v0.0.0-20200701200531-7f61353ee73e/internal/binding/files/docs/mod.go:4:2: no required module provides package github.com/therecipe/qt/internal/binding/files/docs/5.12.0; to add it:
	go get github.com/therecipe/qt/internal/binding/files/docs/5.12.0
/home/ali/.go/pkg/mod/github.com/therecipe/qt@v0.0.0-20200701200531-7f61353ee73e/internal/binding/files/docs/mod.go:5:2: no required module provides package github.com/therecipe/qt/internal/binding/files/docs/5.13.0; to add it:
	go get github.com/therecipe/qt/internal/binding/files/docs/5.13.0
```

## Possible Solution
```
go get github.com/therecipe/qt/internal/binding/files/docs/5.12.0
go get github.com/therecipe/qt/internal/binding/files/docs/5.13.0
```
These commands are changing `go.mod` and `go.sum` in this way:

 - go.mod:
```
+github.com/therecipe/qt/internal/binding/files/docs/5.12.0 v0.0.0-20200904063919-c0c124a5770d // indirect
```

 - go.sum:
```
+github.com/therecipe/qt/internal/binding/files/docs/5.12.0 v0.0.0-20200904063919-c0c124a5770d h1:hAZyEG2swPRWjF0kqqdGERXUazYnRJdAk4a58f14z7Y=
+github.com/therecipe/qt/internal/binding/files/docs/5.12.0 v0.0.0-20200904063919-c0c124a5770d/go.mod h1:7m8PDYDEtEVqfjoUQc2UrFqhG0CDmoVJjRlQxexndFc=
```

So maybe they should be committed?

## Steps to Reproduce
1. make build

## Version Information
go 2:1.16-1

## Context (Environment)
Arch Linux using kernel 5.10.12

**Comment by Houndie** [comment]
^^ Made a pull request to fix the issue.

**Comment by molaeiali** [comment]
This issue still exists on 1.6.6 @jameshoulahan

**Comment by jameshoulahan** [comment]
Sorry all, should be better now. It won't be given a git tag until the next official release cycle though; should be one going out in the next few days.

And sorry @Houndie, in this case it was easier to just do the change myself than to apply your MR 😬 thanks for the contribution though!

**Comment by Houndie** [comment]
No problem, just glad it's fixed :-D

**Comment by molaeiali** [comment]
@jameshoulahan Looks like this issue is back in 1.7.0

**Comment by andrzejsza** [comment]
@molaeiali thanks for noticing - 1.7.0 was just an internal build - we'll be rolling out 1.7.1 this week to early access and will make sure go.mod/go.sum changes are committed. will let you know once done.
