### ISSUE TITLE
Update Flathub app

### ISSUE THREAD

**Issue by icfmp** [ProtonMail/proton-bridge#175]
Hi,

Protonmail Bridge is still at v. 1.5.7 : https://flathub.org/apps/details/ch.protonmail.protonmail-bridge

Current version is 1.6.3

Thanks :+1:

**Comment by andrzejsza** [comment]
Hi there. We don't maintain that. We release new versions on our website (.deb .rpm and pkg builds) + all the code is open sourced right after the release.
We'll review this at some point, as indeed this has been highlighted from a lot of different angles already.
