### ISSUE TITLE
Look for the secret service instead of the gnome-keyring binary

### ISSUE THREAD

**Issue by A6GibKm** [ProtonMail/proton-bridge#176]
After 1.6.3 proton-bridge looks for the binary of gnome-keyring to be present in PATH https://github.com/ProtonMail/proton-bridge/blob/845074f421ac4c7b30b2dee06afab1c40cd90d17/pkg/keychain/helper_linux.go#L42-L44 When the secret service is working properly the binary itself might not be present and proton bridge can still store secrets as it did before this update, so instead it should look for the secret service.

I had to implement this hack in the Flatpak distribution https://github.com/flathub/ch.protonmail.protonmail-bridge/pull/60/commits/266c7c4c0745de0fd2363394ea0e771c82b6342e to make it work again which highlights how this exec.Lookpath does not accomplish its purpose.

**Comment by andrzejsza** [comment]
thanks for this. agreed that the current solution should be improved.

**Comment by andrzejsza** [comment]
for internal reference - GODT-1451

**Comment by andrzejsza** [comment]
this was done in 2.1.3 (also as per https://github.com/ProtonMail/proton-bridge/issues/14). any other issues - do let us know.
