### ISSUE TITLE
Could not get credentials from native keychain error

### ISSUE THREAD

**Issue by sudoyang** [ProtonMail/proton-bridge#177]
I tried to add new users to proton-bridge on ubuntu 20.04 + proton-bridge 1.6.3 but got the following errors.

time="Feb 26 17:30:26.947" level=error msg="Could not get credentials from native keychain" error="no usernames for protonmail/bridge/users/

time="Feb 26 17:30:26.984" level=error msg="Failed to add new user" error="failed to add user to credentials store: exit status 1: gpg: WARNING: unsafe permissions on homedir '/home/phy/.gnupg'

 skipped: No public key\ngpg: [stdin]: encryption failed: No public key\nPassword encryption aborted.\n" pkg=users
time="Feb 26 17:30:27.250" level=error msg="Failed to clear login session after unlock" error="Invalid access token" pkg=users
time="Feb 26 17:30:27.250" level=error msg="Login was unsuccessful" error="failed to add user to credentials store: exit status 1: gpg: WARNING: unsafe permissions on homedir '/home/phy/.gnupg'\ngpg: 

: skipped: No public key\ngpg: [stdin]: encryption failed: No public key\nPassword encryption aborted.\n" pkg=frontend-qt

**Comment by andrzejsza** [comment]
sorry, missed this. still a problem?

**Comment by andrzejsza** [comment]
should not be, especially since keychain changes in 2.1.3. closing.
