### ISSUE TITLE
Ubuntu Mate repo or Supress update announcements

### ISSUE THREAD

**Issue by Keithsc** [ProtonMail/proton-bridge#184]
I am an Ubuntu Mate user and installed the Bridge app via the official .deb package.

Basically the app is being updated to often for me to be bothered to keep downloading the reinstalling the new package. Would it be possible to create a repository for the app that we could use or alternatively how about a suppress updates option so that we only get pestered about a new version monthly ?

**Comment by andrzejsza** [comment]
@Keithsc why wouldn't you just use autoupdates? since 1.6.x the experience is pretty seamless.

**Comment by Keithsc** [comment]
I didn't know there was an auto updates option in the later versions of the app. I have upgraded to the latest version of the app now, and I can now see the auto-update option. Thanks for the heads up.
