### ISSUE TITLE
ProtonMail bridge strips Autocrypt headers

### ISSUE THREAD

**Issue by ivan-cx** [ProtonMail/proton-bridge#186]
## Expected Behavior
Messages should be sent as-is (with Autocrypt headers)

## Current Behavior
Messages sent are modified by bridge (removed Autocrypt headers, added "Empty message" part)

## Steps to Reproduce
1. Install and configure ProtonMail bridge
2. Install and configure DeltaChat mail client https://delta.chat/en/
3. Send encrypted messages from DeltaChat user1 (using proton mail) to DeltaChat user2 (using generic mail server, like gmail.com or mail.ru)
4. Observe results

## Version Information
Bridge 1.6.6
DeltaChat 1.15.4
Ubuntu 20.04

## Context (Environment)
I was trying to chat with people on DeltaChat (both direct 1-on-1 direct email messages, as well as groups messages) using my ProtonMail bridge. Turns out, good old ("stupid") mail servers work fine (i.e. send mail as-is, without modifications), and  DeltaChat works. ProtonMail, on the other hand, seems to break things.

## Detailed Description
I propose Proton Bridge to send messages from DeltaChat as-is (with Autocrypt headers, no additional parts, etc)

Another consideration: since I can not test ProtonMail + DeltaChat without Bridge, I don't actually know where that "modification" happens (is it Bridge, or  ProtonMail server side). I don't have any idea how to find out if it's Bridge or ProtonMail itself.

**Comment by ivan-cx** [comment]
Possibly related to #138

**Comment by link2xt** [comment]
Additional info on the issue from the receiver side:
https://github.com/deltachat/deltachat-core-rust/issues/2320

Received messages lack `Autocrypt` header, so Delta Chat is unable to encrypt the replies or check the message signature. Also MIME type of the message is changed from `multipart/encrypted` to `multipart/mixed` and an additional part saying "Empty Message" is prepended to OpenPGP attachments. Thunderbird is able to recover this message, but displays a warning suggesting that message was corrupted by MS-Exchange server (in fact ProtonMail server).

**Comment by link2xt** [comment]
@doggodanubus Delta Chat and Thunderbird can only revert "Mixed Up" email format and avoid displaying "Empty message" part instead of the decrypted email.

This issue is about the removed Autocrypt header, which cannot be reverted. This effectively strips attached keys from the outgoing mails, and as a result a receiver using Autocrypt-capable MUA can't send an encrypted message back.

**Comment by LBeernaertProton** [comment]
Closed due to inactivity and according to https://github.com/ProtonMail/proton-bridge/issues/138#issuecomment-764448446 this should have been resolved.
