### ISSUE TITLE
import-export-app: White text on white background

### ISSUE THREAD

**Issue by A6GibKm** [ProtonMail/proton-bridge#187]
I tried updating the flatpak to the latest version and I see the following welcoming screen:

![image](https://user-images.githubusercontent.com/11528996/113461321-94fb9980-940b-11eb-9171-a3c45853b679.png)

Do note that the Flatpak only extracts the official deb file and runs the executable inside a sandbox. It is very plausible that this is a not related to flatpak, but I cannot ignore this possibility.

**Comment by A6GibKm** [comment]
I realize that this is in fact the warning that appears when gnome-keyring is missing, see https://github.com/ProtonMail/proton-bridge/issues/176. 

While I was able to fix the issue in the flatpak by creating a dumb binary named gnome-keyring, the warning itself is bugged in some way.

**Comment by andrzejsza** [comment]
this has been noted but we're not planning to put more work in the I-E app at the moment. closing as won't do,
