### ISSUE TITLE
bridge-log.txt : TLS handshake error for 127.0.0.1:44830: remote error: tls: bad certificate

### ISSUE THREAD

**Issue by Guiraud** [ProtonMail/proton-bridge#188]
After building with a no-gui argument, I sat the protonbridge. 
But I get the message ahead. In the Mattermost smtp config that i'm trying to configure I get this error : 
`
Connection unsuccessful: Connection unsuccessful: authentication failed: x509: certificate signed by unknown authority
`
should I copy my letsencrypt cert/key in .config/protonmail/ certificate folder ?

Any clue ?

**Comment by jameshoulahan** [comment]
Hi Guiraud, sounds like you need to allow mattermost to connect to self-signed certificates. As this is not directly an issue related to bridge, I'll close this.
