### ISSUE TITLE
Bridge not working with pass

### ISSUE THREAD

**Issue by j0hannes** [ProtonMail/proton-bridge#190]
As ProtonMail Bridge doesn't work with KWallet, I installed pass. I initialized it and ran the application again. I enter my credentials and the two-factor auth code, but then the application tells me: **Failure: failed to add user to credentials store: no keychain**

## Expected Behavior

It should work as I have installed and initialized pass.

## Current Behavior

When running Bridge on command line, I the following message is printed:
`WARN[0000] Failed to add test credentials to keychain    error="exit status 1: gpg: Passwords: skipped: No public key\ngpg: [stdin]: encryption failed: No public key\nPassword encryption aborted.\n" helper="*pass.Pass"`

## Possible Solution

It seems that Bridge doesn't handle pass correctly, maybe that needs to be fixed?

## Steps to Reproduce

1. Install ProtonMail Bridge
2. Install pass
3. Initialize pass with `pass init "something"`
4. Run Bridge

## Version Information

Bridge: 1.6.9
pass: 1.7.3

## Context (Environment)

I tried to use the ProtonMail Account via IMAP.

## Detailed Description

n/a

## Possible Implementation

n/a

**Comment by asiantuntija** [comment]
It does work, needs a bit of configuring though, here's a post that might help you:

https://www.reddit.com/r/ProtonMail/comments/gi64ek/protonmailbridge_on_linux_cant_detect_pass/

If I remember right it started working for me after installing gnome-keychain.

**Comment by ehrlichja** [comment]
I have this same problem. Nothing in the reddit thread worked. Missing documentation?

**Comment by githubcom13** [comment]
**He had a bug with your keyring and pass.**

**To solve it I had to:**

1. uninstall gnupg and pass

`apt remove gnupg pass`

2. delete the `.gnupg` and `.password-store` folders

```
rmdir /home/protonmail/.gnupg
rmdir /home/protonmail/.password-store
```

3. reinstall gnupg and pass

`apt install gnupg pass`

4. login as the new isolated user

```
su protonmail
cd ~
```

5. run a script session to avoid the PGP key passphrase prompt to fail

`script / dev / null`

6. run gpg to create the database and its folder

`gpg --list-keys`

7. create a new key

```
gpg --full-generate-key
>>>> Choose 1 (1) RSA and RSA (default)
>>>> Choose 2048 (default)
>>>> Choose 0 0 = key does not expire
>>>> Type your name e.g. Proty McProtonFace
>>>> Type your email e.g. a@a.com
>>>> Leave empty comment
>>>> Leave empty passphrase
```

8. Init the password manager for the chosen email address in the PGP keys step

`pass init a@a.com`

9. List the keys to ensure they were created correctly

`gpg --list-keys`

10. Setup the protonmail bridge client, follow the procedure I described here:

follow the procedure I described here: [https://gist.github.com/githubcom13/2f30f46cd5273db2453a6e7fdb3c422b](https://gist.github.com/githubcom13/2f30f46cd5273db2453a6e7fdb3c422b)

**Comment by aarek-eng** [comment]
How would this be applied to an Arc-based distro like Garuda?
