### ISSUE TITLE
Some EMails are not sent

### ISSUE THREAD

**Issue by MakerStuff** [ProtonMail/proton-bridge#191]
Hi, in the past couple weeks i was not able to send some messages via ProtonBridge/Evolution on Ubuntu Linux and finally got at least some clue as to where the problem could be.

Here is what i can provide to solve the problem:

- The problem occurs when sending new emails or replies
  - Sending a new mail directly after a failed reply works
- As far as i know my recipients had different email providers (custom domains so it is not obvious)
- Failed mails were composed of raw text and sometimes included attachments
- When enabling the option to warn on outgoing mails without encryption the warning dialog does not show up

I am not able to reproduce this error so if anybody can contribute their experience to this issue, maybe we can come up with something together.

**Comment by andrzejsza** [comment]
Any updates on this? not sure if it's worth to keep this open - if this is still happening, might be best to contact the support with logs so that we could have a look for any oddities.

**Comment by ericLemanissier** [comment]
Could it be the same as https://github.com/ProtonMail/proton-bridge/issues/161 ?

**Comment by MakerStuff** [comment]
Has not happened since. Maybe it's just a microsoft thing. I mistrust them even on a technical level by now…
