### ISSUE TITLE
Provide a symbolic icon

### ISSUE THREAD

**Issue by proletarius101** [ProtonMail/proton-bridge#192]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

We should provide a [symbolic icon](https://wiki.gnome.org/Design/OS/SymbolicIcons) for the ProtonMail Bridge icon in the taskbar on Linux

## Expected Behavior

The ProtonMail Bridge icon in the taskbar should be [symbolic](https://wiki.gnome.org/Design/OS/SymbolicIcons), which should be in svg format

## Current Behavior

- The icon in the taskbar is blurry under HiDPI
- The icon is so square (the round corner is subtle in such a small size) and looks not native as other taskbar icons

## Possible Solution

Use a symbolic icon under `/usr/share/icons/hicolor/symbolic/apps/` (e.g. https://protonmail.com/images/media/logos/protonmail-sign-white.eps but in svg), for taskbar presentation

## Steps to Reproduce

1.
2.
3.
4.

**Comment by andrzejsza** [comment]
closing as duplicated by https://github.com/ProtonMail/proton-bridge/issues/142 and fixed in the upcoming release.

**Comment by proletarius101** [comment]
Well, apparently NOT duplicated with #142. Symbolic icons != SVG icons. For mac the menubar icon IS symbolic. For Linux the menubar icon is graphical. @andrzejsza

**Comment by proletarius101** [comment]
> Symbolic icons are usually low color or monochrome and intended to match the foreground font color

**Comment by andrzejsza** [comment]
yes, I can see how the solution you're proposing is different, but if the icon is not blurry and looks native then there is no really a reason to be changing this. Could you have a look at this build (it's not public) https://github.com/ProtonMail/proton-bridge/releases/tag/v1.7.0 and let us know if the icon behaves as you would expect?

**Comment by proletarius101** [comment]
Unfortunately no.
Expected:
![image](https://user-images.githubusercontent.com/54175165/116393375-14b13400-a811-11eb-90af-c92e62800afc.png)

Actually:
![image](https://user-images.githubusercontent.com/54175165/116393335-09f69f00-a811-11eb-87fc-66f579a3cd35.png)

**Comment by andrzejsza** [comment]
for internal reference: GODT-1163

**Comment by andrzejsza** [comment]
ok, this is (finally) fixed in the upcoming beta.

**Comment by l0drex** [comment]
In v2.2.2, the icon is sadly colored again. 

I am using Gnome and the flatpak version, if that matters.

**Comment by primalmotion** [comment]
same. thanks for uglyfing my tray bar.
