### ISSUE TITLE
Window freezes when working on process

### ISSUE THREAD

**Issue by Spixmaster** [ProtonMail/proton-bridge#194]
# Issue
I notice every time that if I lost the Internet connection and press the reconnect button on the GUI the complete window is not responsive anymore, not a little bit. It cannot be moved, no buttons can be pressed, nothing.

# Machine
Operating System: Arch Linux
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.81.0
Qt Version: 5.15.2
Kernel Version: 5.11.16-arch1-1
OS Type: 64-bit
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8265U CPU @ 1.60GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Comment by andrzejsza** [comment]
Thanks. Known issue, already reported in https://github.com/ProtonMail/proton-bridge/issues/181.
