### ISSUE TITLE
Does not build on Fedora 34 

### ISSUE THREAD

**Issue by doggodanubus** [ProtonMail/proton-bridge#195]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

Build fails on Fedora 34 

## Expected Behavior

I should be able to properly build and install the application. 

## Current Behavior

go install -v -tags=no_env github.com/therecipe/qt/cmd/...
go: github.com/jameskeane/bcrypt@v0.0.0-20170924085257-7509ea014998 (replaced by github.com/ProtonMail/bcrypt@v0.0.0-20170924085257-7509ea014998): version "v0.0.0-20170924085257-7509ea014998" invalid: unknown revision 7509ea014998
make: *** [Makefile:180: prepare-vendor] Error 1

## Possible Solution

None

## Steps to Reproduce

1. git clone this repository
2. install go
3. run make
4. fails

## Version Information

Current git repository as of this bug.

**Comment by andrzejsza** [comment]
could you please confirm if that's still a problem on 1.8.7?

**Comment by doggodanubus** [comment]
Nope


> # github.com/therecipe/qt/widgets
> widgets-minimal.cpp: In function ‘void* QDesktopWidget_AvailableGeometry(void*, int)’:
> widgets-minimal.cpp:824:88: warning: ‘const QRect QDesktopWidget::availableGeometry(int) const’ is deprecated: Use QGuiApplication::screens() [-Wdeprecated-declarations]
>   824 |         return ({ QRect tmpValue = static_cast<QDesktopWidget*>(ptr)->availableGeometry(screen); new QRect(tmpValue.x(), tmpValue.y(), tmpValue.width(), tmpValue.height()); });
>       |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
> In file included from /home/jcaldwel/Downloads/proton-bridge/vendor/github.com/therecipe/env_linux_amd64_513/5.13.0/gcc_64/include/QtWidgets/QDesktopWidget:1,
>                  from widgets-minimal.cpp:16:
> /home/jcaldwel/Downloads/proton-bridge/vendor/github.com/therecipe/env_linux_amd64_513/5.13.0/gcc_64/include/QtWidgets/qdesktopwidget.h:88:67: note: declared here
>    88 |     QT_DEPRECATED_X("Use QGuiApplication::screens()") const QRect availableGeometry(int screen = -1) const;
>       |                                                                   ^~~~~~~~~~~~~~~~~
> widgets-minimal.cpp: In function ‘int QDesktopWidget_PrimaryScreen(void*)’:
> widgets-minimal.cpp:834:64: warning: ‘int QDesktopWidget::primaryScreen() const’ is deprecated: Use QGuiApplication::primaryScreen() [-Wdeprecated-declarations]
>   834 |         return static_cast<QDesktopWidget*>(ptr)->primaryScreen();
>       |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
> In file included from /home/jcaldwel/Downloads/proton-bridge/vendor/github.com/therecipe/env_linux_amd64_513/5.13.0/gcc_64/include/QtWidgets/QDesktopWidget:1,
>                  from widgets-minimal.cpp:16:
> /home/jcaldwel/Downloads/proton-bridge/vendor/github.com/therecipe/env_linux_amd64_513/5.13.0/gcc_64/include/QtWidgets/qdesktopwidget.h:73:65: note: declared here
>    73 |     QT_DEPRECATED_X("Use QGuiApplication::primaryScreen()") int primaryScreen() const;
>       |                                                                 ^~~~~~~~~~~~~
> widgets-minimal.cpp: In function ‘void* QDesktopWidget_Screen(void*, int)’:
> widgets-minimal.cpp:839:57: warning: ‘QWidget* QDesktopWidget::screen(int)’ is deprecated: Use QScreen [-Wdeprecated-declarations]
>   839 |         return static_cast<QDesktopWidget*>(ptr)->screen(screen);
>       |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
> In file included from /home/jcaldwel/Downloads/proton-bridge/vendor/github.com/therecipe/env_linux_amd64_513/5.13.0/gcc_64/include/QtWidgets/QDesktopWidget:1,
>                  from widgets-minimal.cpp:16:
> /home/jcaldwel/Downloads/proton-bridge/vendor/github.com/therecipe/env_linux_amd64_513/5.13.0/gcc_64/include/QtWidgets/qdesktopwidget.h:77:45: note: declared here
>    77 |     QT_DEPRECATED_X("Use QScreen") QWidget *screen(int screen = -1);
>       |                                             ^~~~~~
> 
> make: *** [Makefile:148: cmd/Desktop-Bridge/deploy/linux/proton-bridge] Error 1
> thegeekcondition:proton-bridge$

**Comment by doggodanubus** [comment]
Ok I did not realize the version of the git would be the same in the changelog. I just cloned the git again and it builds and appears to run. If I have any other issues I'll issue a new bug. Thanks.
