### ISSUE TITLE
Not possible to send calendar invites from Thunderbird

### ISSUE THREAD

**Issue by dsommers** [ProtonMail/proton-bridge#196]
When sending a calendar invite to an external user via Thunderbird 78.10.2, the error message below appears.  This does not look like anything Thunderbird is responsible for. I have also tried to send invites to users inside the same ProtonMail organization, with the same result.  And I've tried to send invites in various weather conditions - everything from pooring rain to cloudy to sunny.  Always the same result, so it is even a bit harsh to blame it on the weather.

![Screenshot](https://user-images.githubusercontent.com/1685255/118661785-bbc13400-b7ef-11eb-85ab-65bad9b0e976.png)

## Expected Behavior
Calendar invite should be sent and the receiver should receive it as a proper .ics invite.

## Current Behavior
ProtonBridge blames weather conditions.

## Steps to Reproduce
1.  Create a new event in Thunderbird
2.  Click the "Atendees" tab in the calendar event window
3.  Add a correct e-mail address where to send the invite
4.  Click "Send And Close".

## Version Information
Linux distro: RHEL 8.3 
Thunderbird 78.10.2 (latest upstream version, downloaded from getthunderbird.com - for Linux 64-bit)
ProtonMail Bridge v1.6.9

**Comment by andrzejsza** [comment]
we've tested with tbird 91.8.1 and it works as expected. still a problem for you?

**Comment by dsommers** [comment]
I've tested on RHEL 8.5 with TB 91.8.1 x86_64 as well.  I'm running Proton Mail Bridge 2.1.3 now.   Everything works fine now, no errors seen.  But is a warm and sunny day :wink:

Closing it as resolved.
