### ISSUE TITLE
Bulding 1.8.1 requires Go 1.15 (not 1.13)

### ISSUE THREAD

**Issue by Razican** [ProtonMail/proton-bridge#198]
## Expected Behavior
As mentioned in the [BUILDS.md](https://github.com/ProtonMail/proton-bridge/blob/v1.8.1/BUILDS.md) file, I would expect the build to succeed with Go 1.13.

## Current Behavior
Building the 1.8.1 version with Go 1.14 fails with the following error:

```
# github.com/ProtonMail/go-rfc5322/parser
../go/pkg/mod/github.com/!proton!mail/go-rfc5322@v0.5.0/parser/rfc5322_parser.go:2756: constant 4230534781 overflows int
../go/pkg/mod/github.com/!proton!mail/go-rfc5322@v0.5.0/parser/rfc5322_parser.go:2780: constant 4230534781 overflows int
../go/pkg/mod/github.com/!proton!mail/go-rfc5322@v0.5.0/parser/rfc5322_parser.go:6683: constant 2740715144 overflows int
../go/pkg/mod/github.com/!proton!mail/go-rfc5322@v0.5.0/parser/rfc5322_parser.go:6683: constant 4294967167 overflows int
../go/pkg/mod/github.com/!proton!mail/go-rfc5322@v0.5.0/parser/rfc5322_parser.go:11728: constant 4244674173 overflows int
../go/pkg/mod/github.com/!proton!mail/go-rfc5322@v0.5.0/parser/rfc5322_parser.go:12153: constant 4292870143 overflows int
note: module requires Go 1.15
make: *** [Makefile:89: build-nogui] Error 2
```

## Possible Solution
A solution would be to raise the minimum required Go version in the documentation to 1.15, but that would mean that it cannot be built in stable debian (Go 1.11), not even with the backports repo active (1.14).

## Steps to Reproduce
1. Clone the repository in the v1.8.1 tag in a machine with Go 1.13 or 1.14
2. Run `make build-nogui`
3. See the failure

## Version Information
Building bridge v1.8.1

## Context (Environment)
```
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```
```
go version go1.14 linux/arm
```
```
Linux 5.10.17-v7l+ #1414 SMP Fri Apr 30 13:20:47 BST 2021 armv7l GNU/Linux
```

**Comment by g-svg** [comment]
I was getting a similar error on my pi with go 1.16.4 and noticed the BUILDS.md file has "64-bit OS (the go-rfc5322 module cannot currently be compiled for 32-bit OSes)".

**Comment by Razican** [comment]
> I was getting a similar error on my pi with go 1.16.4 and noticed the BUILDS.md file has "64-bit OS (the go-rfc5322 module cannot currently be compiled for 32-bit OSes)".

Yes, I noticed that too, but the "note: module requires Go 1.15" error disappears when building on Go 1.16 (the other errors are due to building in a 32-bit OS).

**Comment by jameshoulahan** [comment]
Good catch. The `go.mod` in the `go-rfc5322` module specifies 1.15 as the minimum version, applying a sort of "transitive limitation" on building bridge. I'll just drop the minimum go version of the `go-rfc5322` module to 1.13 :shrug:
