### ISSUE TITLE
OpenBSD v6.9 build with pass

### ISSUE THREAD

**Issue by noahbailey** [ProtonMail/proton-bridge#201]
Trying to get the project building on OpenBSD using `pass`, hoping to get some help with the last couple pieces. 

With a few modifications, I could get the project building: 

* Copy the file `internal/config/tls/cert_store_linux.go` to `internal/config/tls/cert_store_openbsd.go`
* Changing the first line of `util/credits.sh` to `#!/usr/bin/env bash` to work with the different file path for `bash` on BSD's. 

Then I could build the CLI only version: 

    TARGET_OS="linux" gmake build-nogui

However, after building I can't run the program. I do have `pass` installed and set up but it seems unable to use that. 

Hopefully somebody else has experience with this setup and can point out any steps I may have missed. Thanks!

**Comment by cuthix** [comment]
From first look I think it needs !200 first to be merged.

**Comment by LBeernaertProton** [comment]
Closed due to inactivity.
