### ISSUE TITLE
protonmail-bridge doesn't work on NixOS 21.05

### ISSUE THREAD

**Issue by Kreyren** [ProtonMail/proton-bridge#203]
See https://github.com/NixOS/nixpkgs/issues/126174

Any help with the diagnostics is appreciated since the program doesn't provide any output

**Comment by matthew-piziak** [comment]
Can reproduce. When I run `protonmail-bridge` it exits immediately with no output and with exit code 0.

**Comment by Kreyren** [comment]
CC @jameshoulahan @horejsek @cuthix @BilyakA

**Comment by Kreyren** [comment]
FWIW i am getting:

```
--- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=10369, si_uid=1000} ---
```

in standard trace

**Comment by Kreyren** [comment]
Suspected duplicate of https://github.com/ProtonMail/proton-bridge/issues/176
