### ISSUE TITLE
Mixed messages metadata and body in sent directory

### ISSUE THREAD

**Issue by JulienPalard** [ProtonMail/proton-bridge#204]
I'm using protonmail-bridge 1.8.3 and thunderbird 78.10.0, I can't tell if the issue is from thunderbird or protonmail-bridge...

## Current Behavior

When I click a message in the message list, another email shows up in the message detail below:

- Different subject
- Different contacts
- Different date

I mean it's a completly other email that get picked up, not the one I clicked in the first place.

## Steps to Reproduce

Hard to tell, it never happened before. But now it happel, when I click an email, another shows up.

**Comment by andrzejsza** [comment]
it does look like Thunderbird problem. does repairing/rebuilding the mailbox in third solve this?

**Comment by JulienPalard** [comment]
Looks like a Thunderbird repair fixed the issue, TIL about it and thanks a lot for the pointer!

**Comment by andrzejsza** [comment]
there is definitely a problem there, likely more than one. as we (@jameshoulahan) discovered not long ago when tbird does a UID fetch request like:
`tag uid fetch 94 (UID RFC822.SIZE BODY[])`
UID is requested first, before the rest of the items `RFC822.SIZE`,`BODY[]`. If the return to that fetch response doesn't put the UID first, tbird gets confused and it might explain the behaviour you are seeing. We will be looking into this but yes, repairing the mailbox should fix it.
