### ISSUE TITLE
Verification of Debian package fails on Bullseye

### ISSUE THREAD

**Issue by benediktahrens** [ProtonMail/proton-bridge#207]
The verification of the Debian package on Debian Bullseye fails. Specifically, after following the steps outlined at 
https://protonmail.com/support/knowledge-base/verifying-bridge-package/
I obtain an error saying that a suitable policy has not been found when running the `debsig` command:
```
debsig: no applicable policy found
```

The manual works fine for Debian Buster.

## Expected Behavior
The signature should be checked successfully, i.e.
```
debsig: Verified package from 'Proton Technologies AG (ProtonMail Bridge developers) <bridge@protonmail.ch>' (Proton Technologies AG)
```

## Current Behavior
```
debsig: no applicable policy found
```

## Steps to Reproduce
On Debian Bullseye, follow the instructions of https://protonmail.com/support/knowledge-base/verifying-bridge-package/

## Version Information
protonmail-bridge_1.8.3-1_amd64.deb

**Comment by andrzejsza** [comment]
turned out the instructions (https://protonmail.com/support/knowledge-base/verifying-bridge-package/) were incorrect for the install the policy file part - updated now. Could you try again and confirm if the problem persists?

**Comment by benediktahrens** [comment]
@andrzejsza : Thanks a lot for your message. Can you tell me what has changed in the instructions?

**Comment by andrzejsza** [comment]
turned out there were some incorrect steps for the `install policy file section.`

**Comment by andrzejsza** [comment]
just confirmed all works for us - let us know if the problem persist at your end.

**Comment by zcyph** [comment]
Hello, following the steps on Ubuntu 22.04 from https://proton.me/support/verifying-bridge-package results in:

`debsig: No applicable policy found`

**Comment by andrzejsza** [comment]
which version are you checking? could you try the recent beta?

**Comment by zcyph** [comment]
> which version are you checking? could you try the recent beta?

Thanks for following up. I realized issue was PEBKAC after all in my case, I had not followed the instructions properly ("you need to change the xml namespace to http://…"), was able to then get it working.
