### ISSUE TITLE
Errors when setting up bridge with nextcloud

### ISSUE THREAD

**Issue by jacktheripper19** [ProtonMail/proton-bridge#208]
I'm trying to set up the bridge on a server hosting nextcloud so that I can use my account with the mail app. I can connect to my account on nextcloud but I can't read emails and the bridge is giving me errors even though I can see the titles:

 ERRO[Jun 22 12:41:33.927] Could not get mailbox                         error="mailbox Labels does not exist" name=Labels pkg=imap 

ERRO[Jun 22 12:41:33.927] Could not get mailbox                         error="mailbox Folders does not exist" name=Folders pkg=imap

ERRO[Jun 22 12:41:43.018] cannot list messages (true, 25, [BODY.PEEK[1] BODY.PEEK[1.MIME] UID]): list message build: wrong section 1  pkg=imap

ERRO[Jun 22 12:42:18.072] list message build: wrong section 1           cmd=ListMessages metaID="dfefsdfdsf-dsdfesdfdfefsdfe-sdfdsfsdfefsdf==" pkg=imap

I can read some old messages though but I can't send new emails at all.

## Expected Behavior

Be able to read and send messages on nextcloud mail app with protonmail bridge without errors

## Current Behavior
can only see titles, can't open majority of messages, errors on the bridge, can't send messages at all

## Steps to Reproduce

1. install bridge
2. start bridge with protonmail-bridge -cli
3. login to account
4. on nextcloud mail app, on manual connect, connect using info from bridge:
IMAP Settings
Address:   127.0.0.1
IMAP port: 1143
Username:  user@protonmail.com
Password:  bridgepassword
Security:  None

SMTP Settings
Address:   127.0.0.1
SMTP port: 1025
Username:  user@protonmail.com
Password:  bridgepassword
Security:  None 

5. succeed to connect but previous errors

for security I tried both STARTTLS and None

## Version Information
latest version from website: protonmail-bridge_1.8.3-1_amd64.deb

## Context (Environment)
Nextcloud hosted on docker container
Bridge installed on the same container as Nextcloud

**Comment by exander77** [comment]
I don't think NextCloud is within supported clients.

**Comment by andrzejsza** [comment]
it's not, but the behaviour might have improved with v3 - do let us know how does it work with the latest beta. closing anyway.
