### ISSUE TITLE
update theresipe/qt for qt 5.15

### ISSUE THREAD

**Issue by williamh** [ProtonMail/proton-bridge#211]
Hi, I am assisting with packaging proton-bridge for Gentoo linux.

We have found that the version of therecipe/qt you are using does not work with qt 5.15, but the latest version of the package does.

Also, the qt docs should not be in go.mod since it is not up to date for qt 5.15.

It seems that running "go get github.com/therecipe/qt" and committing the update go.mod/go.sum fixes this.

Can we have a new release of proton-bridge that applies these updates?

Thanks much,

William

**Comment by andrzejsza** [comment]
we will be updating to qt6 shortly so closing this issue.

**Comment by podiki** [comment]
Is there an update on this? As far as I see the recent package are still on QT5 and some version before 5.15?

**Comment by andrzejsza** [comment]
We've updated to qt6 - currently in internal alpha, will be release to public beta shortly. We'll update https://github.com/ProtonMail/proton-bridge/issues/155 once it's out.

**Comment by podiki** [comment]
@andrzejsza great, thanks!
