### ISSUE TITLE
Incorrectly detecting headers and body, causing the part of headers to be encrypted as part of the body

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#212]
I already talked about this issue over a year ago. I am not sure where to report it, but it is still not fixed and both e-mails I receive and e-mails imported by Import Assistant are corrupted.

It happens when the e-mail is embedded within another e-mail using multipart. Usually happens with undeliverable responses (Office 365 and others) and certain types of e-mail forwarding.

I reported 2020-04-17 to ProtonMail support as:
> ProtonMail breaks undeliverable responses from Offce 365 creating a malformed email

When that happens, message body usually starts like this:
```
----------------------------------------------
multipart/related
----------------------------------------------
--00000000000010fa6705bbe092f2
Content-Type: multipart/alternative; boundary="00000000000010fa6e05bbe092f3"

--00000000000010fa6e05bbe092f3
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable
```

**Comment by jeremybenaim** [comment]
Hi @exander77, thanks for the report. That's quite strange indeed!

Could you [reach out to our customer support](https://protonmail.com/support-form) so that they can help you figuring out what's going on?

Also, that would be helpful for us to have a `.eml` file that we can look at, if that's possible. 🙏 

Thanks!

**Comment by exander77** [comment]
@jeremybenaim I already supplied them with an example e-mail (comparison of how it was received on ProtonMail and Gmail including screenshots of rendered e-mails) that will cause this and a way to reproduce it with Office 365 when I made the original report. I know I sometimes push for things to be solved ASAP, but this one is more than a year old and it breaks e-mails.

**Comment by exander77** [comment]
Gmail:
![Undeliverable_ Re_ Změna stavu dotazu - Gmail](https://user-images.githubusercontent.com/2256039/129758383-af63706d-25bc-46f6-88f9-dd242c1e52ca.png)
ProtonMail:
![Undeliverable_ Re_ Změna stavu dotazu - ProtonMail](https://user-images.githubusercontent.com/2256039/129758389-65d4f08e-47a8-4ec4-915d-337fdf5ab0f3.png)

**Comment by trev-dev** [comment]
SO awesome. I have 4 emails with ProtonMail on a professional package and I can't back out of it even if I wanted to. Could we please:

1. See a message that needs sending
2. Bridge it to ProtonMail
3. Send it _exactly as it was intended to be sent_

I really don't understand why this is a problem.

**Comment by andrzejsza** [comment]
bit late, but this should be finally fixed - we needed a backend change here, so it took some time but the fix should be valid for all clients - Bridge and the Import Assistant aka Easy Switch alike.
