### ISSUE TITLE
Bridge password is not accepted by SMTP while being accepted by IMAP

### ISSUE THREAD

**Issue by wilderjds** [ProtonMail/proton-bridge#214]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

## Expected Behavior

Being able to send emails via SMTP through the bridge 

## Current Behavior

Password checking fails with log:

DEBU[Aug 23 23:58:58.363] Incorrect bridge password                     pkg=credentials userID=OMITTED
ERRO[Aug 23 23:58:58.363] Could not check bridge password               error="backend/credentials: incorrect password" pkg=smtp

The same password works for IMAP. 
## Steps to Reproduce

1.
2.
3.
4.

## Version Information

1.8.7

## Context (Environment)

Possibly related note: when creating the account, the following error is displayed
ERRO[Aug 24 00:04:46.951] Could not unmarshal secret                    error="backend/credentials: malformed secret: malformed credentials" pkg=credentials user="Iu-TZ7gF5BOK9ygo9o_XSCNnpA2mUH1hxPwG7----OBFUSCATED-----mn58f-zHU2wUInKfrQ==

email client is kmail

**Comment by wilderjds** [comment]
Thunderbird works… I'll debug from the kmail side

**Comment by wilderjds** [comment]
Bug in kmail smtp password retrieval.  Sorry for the noise.

**Comment by Freeedim** [comment]
Nevermind... Although "clear cache" and "clear keychain" did not work, I just deleted the identity in KMail and created a new (and identical) one and it works now.
