### ISSUE TITLE
[Request][macOS] Add option to hide window on startup 

### ISSUE THREAD

**Issue by ciehanski** [ProtonMail/proton-bridge#22]
It would be nice to have a configuration option to hide the Proton Bridge's window during system startup. On macOS specifically the window always pops up and can be quite pesky. Low-priority request, but a QoL improvement nonetheless. Would be willing to submit a PR.

**Comment by andrzejsza** [comment]
Bridge shouldn't be popping up after startup - it should just start minimised in the dock, as we're adding `--no-window` in the shortcut's target - seems as everything works fine at this end.
If you still have this problem @ciehanski, please report as a bug.
