### ISSUE TITLE
Arm64 Support

### ISSUE THREAD

**Issue by Claywd** [ProtonMail/proton-bridge#222]
Curious if you've already approached building for arm64 debian and if there was a reason it wasn't further developed. Otherwise I'd be very interested in adding the build targets and trying to get it working.

**Comment by jg110** [comment]
The `build-nogui` target works on Mobian, so it should work on arm64 Debian. This doesn't seem to have official support though, which would be nice to have.

**Comment by andrzejsza** [comment]
just to manage expectations - there won't be official support for now, so closing the issue.
