### ISSUE TITLE
[Feature] subscribe to calendar through the bridge

### ISSUE THREAD

**Issue by ploum** [ProtonMail/proton-bridge#223]
In order to access our calendar offline, the bridge could allow access to the ICS version of the calendar.

**Comment by andrzejsza** [comment]
yes, it would be cool. we'd definitely like to look into it.

**Comment by ploum** [comment]
If I may add, one thing important would be, for me, to have everything in the same tool in order to not have a "mail bridge", "calendar bridge" then "file bridge". would make life a lot easier for users.

**Comment by Akselmo** [comment]
This would definitely make my life easier :)

**Comment by andrzejsza** [comment]
also CalDAV support as per #309, now closed as duplicate.

**Comment by alexrentsch** [comment]
Is there any new information on this topic from the proton team? I'd like to switch to the proton eco-system, but without some standard protocols it's not possible to embed proton into my environment which is built up for years.

**Comment by thepian** [comment]
I'm not sure why I would use Proton Calendar without support for CalDAV

**Comment by tangodev** [comment]
IMHO the priority should be higher since there's a ton of requests for this on User Voice.

https://protonmail.uservoice.com/forums/932842-proton-calendar/suggestions/39383308-calendar-accessible-through-protonmail-bridge
https://protonmail.uservoice.com/forums/932842-proton-calendar/suggestions/42585853-outlook-compatibility-for-the-calendar-feature-us
https://protonmail.uservoice.com/forums/932842-proton-calendar/suggestions/43591329-protoncalendar-bridge
https://protonmail.uservoice.com/forums/284483-proton-mail/suggestions/45750190-complete-the-mail-bridge-add-webdav-and-ldap-or
https://protonmail.uservoice.com/forums/932842-proton-calendar/suggestions/42967416-ical-support-for-protonmail-calendar
https://protonmail.uservoice.com/forums/932842-proton-calendar/suggestions/43132866-proton-calendar-extension-subscription-of-externa
https://protonmail.uservoice.com/forums/932842-proton-calendar/suggestions/42609169-bridge-that-syncs-with-other-calendars-like-fantas
https://protonmail.uservoice.com/forums/932842-proton-calendar/suggestions/42352933-allow-calendar-to-be-accessible-via-a-bridge-equiv
https://protonmail.uservoice.com/forums/932842-proton-calendar/suggestions/43591329-protoncalendar-bridge

Not having a central source of truth for calendars that's easy to sync is a quit moment for many. Google may be evil, but the instantly win here in the UX department.

**Comment by deepbits** [comment]
Highly needed feature. CalDav sync is essential!

**Comment by joshuaks** [comment]
Adding on as another user interested in this. 

Lack of native Calendar support (and Drive support, but that's separate) have been keeping me from going full in on Proton. Not a fan of web apps.

**Comment by stephandewaard** [comment]
This is a very important feature request to me as well.

It would enable offline desktop access to Proton Calendar and also enable me to have my personal proton calendar and work/other calendars in the same desktop client.

**Comment by jory3** [comment]
+1 - (Cal-/CardDAV) Sync is the only thing I need to be able to switch completely from fastmail to proton.

**Comment by Baardi** [comment]
I will not transition over to the Proton ecosystem, untill they support basic standard protocols

**Comment by kirawi** [comment]
Has this been explored further on Proton's side? Has any resolution been made regarding it? Or is it still in limbo?

**Comment by 8bitmd** [comment]
I already switched to Proton Mail, Drive, Pass and VPN, and this is the only reason why I'm not using Calendar. Please add this.

**Comment by ghostsquad** [comment]
Please add this! I just switched to Proton, but I need a solution for managing events.

**Comment by gvasco** [comment]
Adding further support to CalDAV integration and not sure if it would make sense to add CardDAV for contacts

**Comment by travissouthard** [comment]
I have been a Proton customer for a year and would love to have CalDAV support for managing my calendar

**Comment by flowt-au** [comment]
The lack of integration eg CalDAV is what is stopping me from embracing the Proton ecosystem. So +1 for this.

**Comment by DrakePork** [comment]
+1

**Comment by john-okeefe** [comment]
I too would like to +1 this. I'm trying to move from fastmail to the proton ecosystem, but with no app for Linux for drive and no Cal/Card-DAV support, it's making it really difficult.

**Comment by Lcchy** [comment]
Without wanting to add an nth +1, I want to mention my interest in the Cardav protocol being implemented as well as Caldav in order to also sync contacts. Thank you.

**Comment by gabor-meszaros** [comment]
Hi Everyone, Thank you for the suggestion, and in general your interest in Proton Mail Bridge. While I understand the frustration, GitHub is not a good place to collect feature requests. If you are interested in the CalDav support, please upvote the [related uservoice request](https://protonmail.uservoice.com/forums/932842-proton-calendar/suggestions/39383308-bridge-support-for-calendar-outlook-thunderbird), and/or comment under that. Thank you for your collaboration.

**Comment by travissouthard** [comment]
> If you are interested in the CalDav support, please upvote the [related uservoice request](https://protonmail.uservoice.com/forums/932842-proton-calendar/suggestions/39383308-bridge-support-for-calendar-outlook-thunderbird), and/or comment under that. Thank you for your collaboration.

@gabor-meszaros this is a four year old request with 1000+ votes and 6+ pages of comments asking for this. I'm new to Proton and making requests for features. Any insight into what threshold would be needed to reach for this to even begin implementation?

**Comment by domharrington** [comment]
@gabor-meszaros I tried to create an account on uservoice but the sign up flow is not working on Firefox. I already have a github account so it's easier for me to use this to keep tabs on this issue. Like what @travissouthard said, is there any threshold that is required for ProtonMail to take this feature request into account or should I start to look for other email/calendar providers? 👀 Would be nice to have an official statement yes or no on this pretty fundamental issue.

**Comment by ploum** [comment]
As the initial reporter of this issue (and badly wanting it implemented), I should highlight that Github issues are almost never a good place to add "+1" kind of messages. If you would like to do so, please add a thumbsup to the original issue and subscribe to the bug.

Every "me too" messages is sent to all people subscribed to the issue, giving false hope "oh, something is happening on this issue". This also make the whole thread unusable for real discussion about how the issue should be handled and developed.

For those new to Protonmail, I must add that Proton has the culture of taking the time to do thing right. It means that it takes a long time (years) to get new features but when those features are announced, they are basically ready and almost immediately usable.  I’m pretty sure that this feature request is on their radar, they know about it, they know it is requested and they are thinking about it.

But it is far from being the most requested feature on uservoice. People seems to badly want Todo and birthdays first in their calendar. (no, I don’t understand that either but who am I to judge…)

So please add a comment if you think you are bringing something new to the discussion (like offers to contribute to the bridge or technical question about the API to use). If not, please:

- add a thumbs up on the first message of this issue
- subscribe to this issue  (you will quickly understand why "me too" comments are annoying)
- consider creating an account on uservoice to vote there  (no, I didn’t manage to create mine…)

**Comment by ploum** [comment]
(just didn’t realize that this issue has been closed. It should maybe be reopened)

**Comment by GarlandKey** [comment]
@ploum Vote for this feature here: https://protonmail.uservoice.com/forums/932842-proton-calendar/suggestions/39383308-bridge-support-for-calendar-outlook-thunderbird

**Comment by adowair** [comment]
+1 Here, having bridge support mail and calendar will allow me to finally move everything to Proton. I'm seriously considering switching out given this limitation

**Comment by fabian-st** [comment]
This is a very critical feature which should be implemented ASAP.

**Comment by jmomort** [comment]
https://github.com/emersion/hydroxide/pull/282 could be a valuable basis
