### ISSUE TITLE
How to remove all configuration files

### ISSUE THREAD

**Issue by TRPB** [ProtonMail/proton-bridge#226]
I'm using the Arch Linux AUR package. I've tried `protonmail-bridge`, `protonmail-bridge-bin` and `protonmail-bridge-nogui` and all have the same problem.

A couple of days ago I started getting this error when running  the `protonmail-bridge` command:

```
WARN[0000] Failed to add test credentials to keychain    error="exit status 1: gpg: error retrieving '[MY EMAIL ADDRESS]' via WKD: Syntax error in URI\ngpg: [MY EMAIL ADDRESS]: skipped: Syntax error in URI\ngpg: [stdin]: encryption failed: Syntax error in URI\nPassword encryption aborted.\n" helper="*pass.Pass"
```

It looks like there's a syntax error in the config files. Since nothing is stored on the computer I figured I'd just delete the config files and set up my accounts again. I deleted `~/.config/protonmail` and `~/.password-store/protonmail-credentials/`.

Even after doing so, it was still referencing my email address so I tried removing the entire `~/.password-store` directory. Now, however, now whenever I run `protonmail-bridge` I get zero output in the terminal. Nothing, the program just starts and exits. 

I'm guessing there is some configuration file somewhere which is now invalid because the others are missing, unfortunately I  can't find it. I tried to use `strace` to work out where `protonmail-bridge` was looking but I can't find that either, it might be using dbus or something to read settings.

Can you provide documentation about how to completely wipe the configuration as at the moment I cannot use this at all as it seems to be crashing on startup.

**Comment by andrzejsza** [comment]
odd.
everything config-related is in
`~/.config/protonmail`
maybe also try
`~/.cache/protonmail` ? 
let us know if you still have problems.
