### ISSUE TITLE
Option to disable automatic updates

### ISSUE THREAD

**Issue by gudvinr** [ProtonMail/proton-bridge#229]
## Expected Behavior

There should be an option either at compile time (preferable) or at runtime to disable automatic updates and checking for them.

## Current Behavior

Bridge tries to fetch updates using `https://protonmail.com/download/bridge/version_linux.json`.

## Possible Solution

Compile-time flag, environment variable, CLI flag that turns off updates.

## Steps to Reproduce

1. Compile Bridge
2. Launch

## Version Information

v1.8.10

## Context (Environment)

I am building headless proton-bridge for using inside container.  
It should not update itself because once container stopper it'll rollback to the version it started with.

Automatic updates through app are also impossible (and wrong even if it is possible) in most GNU/Linux distributions since  version management controlled by package managers exclusively.

I didn't find any option to do so. There's no information about that in `BUILDS.md`, `Makefile`, etc.

**Comment by cuthix** [comment]
you can change either via CLI

```
./proton-bridge -c 
>>> updates autoupdates disable
Bridge is currently set to automatically install updates.
Are you sure you want to stop bridge from doing this? yes/no: yes
```

or just edit prefs file `~/.config/protonmail/bridge/prefs.json` and set  `"autoupdate": "false"`
