### ISSUE TITLE
Emails sent via Bridge do not appear in Outlook Office 365 in email body, but as text file attachment

### ISSUE THREAD

**Issue by jwflory** [ProtonMail/proton-bridge#230]
When an email is sent via the Proton Bridge to an email address using Microsoft Office 365, Outlook does not show the message text in the email body. Instead, the email message is added as a text file attachment.

## Expected Behavior

Email message appears in body of email, not as an attachment. **This works as expected when sending mail from `mail.protonmail.com`**.

![Screenshot of an email in Outlook (Office 365) rendering correctly in the body content of the email, not as an attachment.](https://user-images.githubusercontent.com/4721034/139153980-276cbfef-7fd1-4d94-b618-7ead9184f779.png "Screenshot of an email in Outlook (Office 365) rendering correctly in the body content of the email, not as an attachment.")

## Current Behavior

When an email is sent from the Bridge to an email address in Office 365, it appears like this:

![Screenshot of an email in Outlook (Office 365) showing an empty email with a text file attached](https://user-images.githubusercontent.com/4721034/139153965-14588872-7150-4b96-b737-91cbc1283e25.png "Screenshot of an email in Outlook (Office 365) showing an empty email with a text file attached")

![Screenshot of the text file attachment in previous image.](https://user-images.githubusercontent.com/4721034/139153971-2443b77f-4ffd-4db9-9460-f9f197cc2622.png "Screenshot of the text file attachment in previous image.")

## Possible Solution

It's hard for me to guess!

## Steps to Reproduce

1. Launch Proton Bridge.
2. Draft an email to an email address with an Office 365 or Microsoft Outlook subscription.
3. Send email.
4. Check received email; message body appears as a text attachment.

## Version Information

v1.8.10.

## Context (Environment)

Running Fedora Linux 35 with Thunderbird as my email client.

**Comment by exander77** [comment]
This looks to me more like Office 365 issue, but a workaround should be possible. Standard HTML message is a defacto attachment and I haven't noticed such behaviour anywhere. I have actually seen the reverse issue, that Bridge messed some messages during import and the content was considered an attachment.

**Comment by alfredonodo** [comment]
Hi,
I have a similar problem with thunderbird 102 or 91 + protonBridge 2.4 or 2.3. If I send an encrypted message from webmail to a protonmail account and not protonmail it works fine. However, if I send the same encrypted message via thunderbird, it is received as an attachment. Should I open a new problem?
![Error](https://user-images.githubusercontent.com/41476198/194616086-92fe59e1-1b30-42db-8792-25180a931adb.png)

**Comment by jwflory** [comment]
@alfredonodo Looks like the same issue I had 👍🏻 I'm not sure how the @ProtonMail team triages GitHub issues though.

**Comment by alfredonodo** [comment]
> @alfredonodo Looks like the same issue I had 👍🏻 I'm not sure how the @ProtonMail team triages GitHub issues though.

Have you solved it? Should I contact protonMail support?

**Comment by andrzejsza** [comment]
feel free to get in touch with support, just to make sure this is the same issue. we have this in our backlog (for internal reference GODT-1559).

**Comment by alfredonodo** [comment]
Hi,
I solved it with the help of support. In a nutshell you have to disable the e2ee in thunderbird and leave the e2ee provided by proton mail via proton bridge. Otherwise you will have a double level of encryption and the message will be sent as an attachment.

**Comment by andrzejsza** [comment]
indeed. we've tested with 3.1.x and everything works as expected.
