### ISSUE TITLE
Quad9 resolver doesn't work on standard :443 port

### ISSUE THREAD

**Issue by gudvinr** [ProtonMail/proton-bridge#231]
Protonbridge fails to resolve domains using quad9 DoH server.  
This results in errors:
```
ERRO[Nov  4 09:40:41.851] Failed to query DNS records                   error="failed to unpack DNS response: dns: bad rdata" pkg=pmapi provider="https://dns11.quad9.net/dns-query"
```

## Expected Behavior

Quad9 DNS over HTTPS resolver is working.

## Current Behavior

Quad9 DoH resolver doesn't work and fails every time app starts.

## Possible Solution

Use :5053 port

## Steps to Reproduce

1. Launch protonbridge

## Version Information

`v1.8.10`

## Detailed Description

There's chance that it happens because of API misuse. Quad9 [mention on their site](https://www.quad9.net/news/blog/doh-with-quad9-dns-servers/) that API updated to work on :5053 port.

I tried checking this theory by using curl to request DNS records:
```
$ curl -SL 'https://dns9.quad9.net/dns-query?name=protonmail.com&type=A'
Unable to find the DNS parameter
```

And with :5053:
```
curl -SL 'https://dns9.quad9.net:5053/dns-query?name=protonmail.com&type=A'
{"Status":0,"TC":false,"RD":true,"RA":true,"AD":true,"CD":false,"Question":[{"name":"protonmail.com.","type":1}],"Answer":[{"name":"protonmail.com.","type":1,"TTL":1200,"Expires":"Thu, 04 Nov 2021 09:59:47 UTC","data":"185.70.42.12"},{"name":"protonmail.com.","type":46,"TTL":1200,"Expires":"Thu, 04 Nov 2021 09:59:47 UTC","data":"A 7 2 1200 20211126062337 20211027060404 46517 protonmail.com. l8BiJerP+s87WWnpS/u2FNzhHdiIE7SSjdBiOyW1YqE+kTWVjlCmffOY9/04HYvZU566KpOsAJuCwgIT6abbsmxhikDcRgTQY+Zy0Gakuy0HjKpgLL+r4pMV5tE1+YhRjarEHWh7HTNrwUkBYtGERR7axeoyzAmFWFkqBtqhvZNvQG4xNsGnQijzlqpYRyaYgoeATy+RbKdaatsI8LmZxG8dC2CQ7IdNCnHvOVXzZ7vMR4fFDraEXnnEyQdFjceJzZ6Tx2baASkikoZ3YEZi03SWVg+GivN0l1QCX30YRK1x2x61pXT+XgDkrkdKP4O/xX9ylwSe2GsoW/9FR5CISw=="}]}
```

**Comment by andrzejsza** [comment]
thanks for pointing this out. yes, we'll look into this and so will other clients using quad9.

**Comment by andrzejsza** [comment]
and done in 2.12.
