### ISSUE TITLE
cannot upgrade connection: EOF                protocol=IMAP

### ISSUE THREAD

**Issue by ipflowss** [ProtonMail/proton-bridge#232]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

## Expected Behavior
Auth via IMAP

## Current Behavior
ERRO[Nov  7 18:28:06.119] cannot upgrade connection: EOF                protocol=IMAP

## Steps to Reproduce

1.  followed bridge install directions here on an ubuntu 20.04 server: https://gist.github.com/githubcom13/2f30f46cd5273db2453a6e7fdb3c422b
2. Added protonmail account
3. I can send email out
4. IMAP auth fails with error:  "cannot upgrade connection: EOF                protocol=IMAP"

## Version Information

protonmail-bridge_1.8.10-1_amd64.deb

## Context (Environment)

The bridge IMAP fails with error.

The IMAP client is freescout https://github.com/freescout-helpdesk/freescout

The freescout IMAP settings tried.  There are no other server auth options to try from freescout's perspective 
  
1 no TLS/SSL with no cert checking
2 SSL with no cert checking
3 TLS with no cert checking
4 no TLS/SSL with cert checking 
5 SSL with cert checking
6 TLS with cert checking

Freescout has no issue with 6 other IMAP servers running on completely different hosts including gmails IMAP servers, dovecot, and other IMAP servers with no auth issues.

**Comment by andrzejsza** [comment]
can you try the latest beta and let us know if any improvements?
