### ISSUE TITLE
EVOLUTION for Linux: Blank emails

### ISSUE THREAD

**Issue by CWM030** [ProtonMail/proton-bridge#233]
I just want to report that sometimes the emails come in as blank in Evolution for Linux.

There is no name or subject line and you cant click on the emails.
And Evolution will not move those emails off of the server to the local folders.

But upon closing Evolution and opening Evolution again, the senders name and subject line appears and the emails are moved to the correct local folders.

Chris

**Comment by andrzejsza** [comment]
thanks for the reports. we don't claim to support `Evolution` just yet but we've the IMAP rewrite that we're working on things should get better with smaller clients like this. I'll close the issue for now as there is no work in our pipeline that is directly linked to this.
