### ISSUE TITLE
go get: dependency github.com/jameskeane/bcrypt broken

### ISSUE THREAD

**Issue by momo13** [ProtonMail/proton-bridge#234]
Issuing go get (with go version go1.17.3) results in:
go get: github.com/ProtonMail/proton-bridge@v1.8.10 requires
	github.com/jameskeane/bcrypt@v0.0.0-20170924085257-7509ea014998: invalid version: unknown revision 7509ea014998

## Expected Behavior
Dependency should be resolved.

## Current Behavior
Dependency cannot be resolved

## Possible Solution
Fix go.mod?

## Steps to Reproduce
go get
go mod tidy

## Version Information
github.com/ProtonMail/proton-bridge@v1.8.10

**Comment by servusdei2018** [comment]
@momo13 the `go get` you're doing is unnecessary, and generates the error because it is unaware of the `replace` directive in `go.mod` regarding the dependency in question:

go.mod:
```
replace (
	...
	github.com/jameskeane/bcrypt => github.com/ProtonMail/bcrypt v0.0.0-20210511135022-227b4adcab57
)
```

Rather, running `go mod tidy` alone should download & extract the necessary dependencies.

**Comment by eau-u4f** [comment]
small naive question, is there a specific reason to use a random bcrypt implementation instead of the [golang one](https://pkg.go.dev/golang.org/x/crypto/bcrypt)?

**Comment by andrzejsza** [comment]
@eau-u4f - golang bcrypt doesn't allow to choose the salt and we provide salts from the app layer.

**Comment by eau-u4f** [comment]
oh ok, i see, thanks for explaining.

**Comment by ArsenArsen** [comment]
on another note, it is currently impossible to get the bridge via goproxy, since it lacks a `/v2` and go requires `/vN` for `N>=2`.

example:
```
[c] ~$ go get github.com/ProtonMail/proton-bridge@v2.1.1
go get: github.com/ProtonMail/proton-bridge@v2.1.1: invalid version: module contains a go.mod file, so module path must match major version ("github.com/ProtonMail/proton-bridge/v2")
[i] ~ 1 $ 
```

**Comment by andrzejsza** [comment]
Closing as this has been fixed a while back.
We are now using go1.18 and `go get` is no longer used. `go mod tidy` works as expected. Thanks for bringing this up.
