### ISSUE TITLE
"Far" side (bridge) doesn't support "P" (passed) flag

### ISSUE THREAD

**Issue by trev-dev** [ProtonMail/proton-bridge#237]
mbsync cannot sync your service via the bridge in some cases where the P flag has been tacked onto the message.

P is for "passed" meaning the message was forwarded.

Please let us know what flag you'd prefer, or fix this issue.

**Comment by cuthix** [comment]
We would need more information to understand this request correctly. Is there some documentation of this P flag? Is it IMAP or mbsync feature?

If you mean a custom flag message attribute https://datatracker.ietf.org/doc/html/rfc3501#section-2.3.2? Should it be mailbox (e.g. `\Deleted`)  or global (shared over all mailboxes e.g. `\Seen`) attribute

**Comment by trev-dev** [comment]
Hey, sorry. Of course this is some old/non-standard thing. I'm using mbsync. As long as this error doesn't stop my mail from syncing I can live with it, but I'd prefer a way to handle it instead.

**Comment by bergheim** [comment]
I have the same issue ("Notice: far side store does not support flag(s) 'P'; not propagating."). It is a bit annoying that the logs keep getting spammed by this, but as far as I can tell it still works..
