### ISSUE TITLE
Deleting email from All Mail folder

### ISSUE THREAD

**Issue by dhammel** [ProtonMail/proton-bridge#238]
Hello,

I just updated to v1.8.12 and realized that I can no longer delete all emails in the all mail folder as i've always been able to.

I always do this in thunderbird as theres no option through the website to do so. All delete request are not allowed.

Why is this? If I can't do it in thunderbird, how else could I delete 50k+ emails from the folder. Doing so manually would take hours.

As of now, rolling back to prior version will work, but i'd rather not have to do that.

**Comment by andrzejsza** [comment]
hi. as we understand - you were never allowed to delete (move to Trash) messages from All Mail - this is not an allowed action, as in Proton environment Trash is part of All Mail.
what changed in 1.8.12 is that we are letting the client know about this so they can error it out, i.e.
BEFORE
the user tries to delete from All Mail, the messages appear as deleted by are coming back with no info
NOW
the user tries to delete from All Mail, client shows an error.

As for deleting 50k+ email from a folder - that should be all fine, we just not allowing deletion from All Mail.

**Comment by dhammel** [comment]
@andrzejsza 

In v1.8.10 or before, i can delete all messages from All Mail, then empty trash, works all the time. 

As for deleting 50k+ emails, if I can't delete from All Mail anymore, then how would this work? If lets say I've used up all my storage space and want to backup all my emails, and then delete them from protonmail, how would I do this If I can no longer delete from All Mail folder?

Proton itself allows deleting from All Mail through the browser, and was able to do so through thunderbird as well up until v1.8.12.

**Comment by exander77** [comment]
> hi. as we understand - you were never allowed to delete (move to Trash) messages from All Mail - this is not an allowed action, as in Proton environment Trash is part of All Mail. what changed in 1.8.12 is that we are letting the client know about this so they can error it out, i.e. BEFORE the user tries to delete from All Mail, the messages appear as deleted by are coming back with no info NOW the user tries to delete from All Mail, client shows an error.

Bollocks. We already discussed it this: https://github.com/ProtonMail/proton-bridge/issues/62

Are you guys totally incompetent? Or why are you feeding us nonsense all the time?

@horejsek and @andrzejsza I would fire you guys on the spot.

**Comment by morciej** [comment]
What I am doing these days (until Protonmail fixes this, which is likely never) is to COPY messages from All Mail (or Spam) to Trash (NOT "move") which has to be done manually, as Thunderbird does "Delete" by move to trash, at least the way I have things set up. Works for me!

**Comment by dhammel** [comment]
@morciej Thanks for the tip, I had not tried that. What I did instead is use an Open Source app called Electronmail which is an unofficial fork for protonmail ui access in a native app. With the local store option, can delete everything from All mail. Worked with seconds.

**Comment by andrzejsza** [comment]
Will update https://github.com/ProtonMail/proton-bridge/issues/165 in the coming days, closing as duplicate.
