### ISSUE TITLE
1.8.12 is marked as pre-release but is published

### ISSUE THREAD

**Issue by molaeiali** [ProtonMail/proton-bridge#240]
1.8.12 is marked as pre-release but is published in the [website](https://protonmail.com/bridge/install) and users are being prompted inside the application to upgrade, as a maintainer on Arch-Linux AUR, should I update the package? why is this unconsistency?

## Expected Behavior
1.8.12 become the latest release, or not putting 1.8.10 on the website if it's not ready?

## Current Behavior
1.8.12 is marked as pre-release but is published

**Comment by andrzejsza** [comment]
sorry for the inconsistency - the tag should be updated last week. fixed now.

**Comment by molaeiali** [comment]
This issue is returned in version 3.7,1, here on GitHub the latest version is 3.6.1 but on the website, 3.7.1 is downloadable, is 3.7.1 the latest stable release? @andrzejsza

**Comment by molaeiali** [comment]
@cuthix @gabor-meszaros @BilyakA
