### ISSUE TITLE
New symbolic icon getting stretched to bigger sizes v2.0.1

### ISSUE THREAD

**Issue by PoisonFrog** [ProtonMail/proton-bridge#242]
Icon is not in the size it is supposed to be and the color is not accurate.

## Expected Behavior
I'm using 22x22 icons and protonmail-bridge should be using the 22x22 icon my icon pack provides as it is.

## Current Behavior
Icon is stretched and appears bigger than it is supposed to be and the color is different.

![2021-12-17_00-20](https://user-images.githubusercontent.com/74987652/146483643-17ab5c74-e6b8-4d4e-9bd5-0454d16a2cbe.png)

Protonmail-bridge icon is the one on the right, just to the left of it is how it is supposed to look like in the panel.

## Version Information
v2.0.1

## Context (Environment)
Using xfce4-panel with 22 size icons with Papirus icon pack.

**Comment by andrzejsza** [comment]
closing as all the icons have been changed earlier this year.
