### ISSUE TITLE
Support tunning off STARTTLS for localhost

### ISSUE THREAD

**Issue by ghost** [ProtonMail/proton-bridge#245]
Hello,

I am running proton-bridge on headless environment and I would like to request adding command-line option to tun off STARTTLS while on localhost.

Since there is no single point to encrypt for the local email session, this will support more smtp email clients with STARTTLS option disabled and it will remove problems caused by self-signed certificates.

**Comment by bartbutler** [comment]
This sounds like a good idea.

**Comment by m4rkw** [comment]
+1 this would be really helpful. I've wasted a lot of time trying to architect a productionised deployment of proton-bridge for my own use but struggle to make it play nice with the surrounding tooling. This would help a lot with that.

**Comment by jamolnng** [comment]
While not a solution for turning off STARTTLS, I've got a write-up about how to get Let's Encrypt certificates working with proton-bridge so you have valid TLS certificates

https://lder.dev/posts/Fixing-ProtonMail-Bridge-SSL-errors-with-Lets-Encrypt/

**Comment by jamolnng** [comment]
@ayanamidev Ya I did realize that for Nextcloud after I finished getting the certificates working, but I figured there might be one point where disabling starttls doesn't work for some application and I didn't want to be stuck

**Comment by xadhatter** [comment]
I haven't tested but there does seem to be a way to change from STARTTLS to SSL, which would solve my use case issues. https://github.com/ProtonMail/proton-bridge/blob/777ad369a290aaa0e4ef30a3f0846c4edec97aef/utils/vault-editor/README.md?plain=1#L51-L52

**Comment by xadhatter** [comment]
Appears this was added in v3. Can't wait!

![image](https://user-images.githubusercontent.com/3497441/214929234-bb9357d4-6715-4a5e-924e-70977627a3ab.png)

**Comment by andrzejsza** [comment]
indeed. feel free to test and let us know if doesn't work.

**Comment by vjau** [comment]
I can't get SSL to work with thunderbird.
I get an ssl_error_protocol_version_alert in the thunderbird console.
