### ISSUE TITLE
UI doesn't work at all on Gnome Xwayland (NVIDIA?)

### ISSUE THREAD

**Issue by ghost** [ProtonMail/proton-bridge#247]
## Expected Behavior
Should be able to see the UI and interact with it.

## Current Behavior
On older version you can't see anything at all, on 2.0.1 the window decoration shows, but the UI doesn't.

## Possible Solution
No clue. It works if you force it to run on pure Wayland with QT_QPA_PLATFORM=wayland, but it's laggy, looks wrong, and the app exits out when you press X, so it's not ideal for my use case.

## Steps to Reproduce
1. Be on Gnome (with nvidia? 495.46)
2. Run Wayland session
3. Launch protonmail bridge (it defaults to Xwayland)
4. Blank bridge window that you can't do anything with

## Version Information
1.8.12 and 2.0.1

## Context (Environment)
It's not as bad on 2.0.1, I have the app set up already and it does work as long as it's already set up in advance. You just can't interact with the app to change anything if you ever needed to.

## Detailed Description
Qt is lagging way behind when it comes to Wayland, and that's probably the problem.

## Possible Implementation
Ditch Qt, it sucks. GTK all the way.

**Comment by Pshemas** [comment]
same behavior on my end - OpenSUSE Tumbleweed, Nvidia 510.47.03. On X11 it works correctly.

Mind this happens only on Nvidia - I've checked Wayland session on a laptop with Intel integrated gpu and it works correctly.

**Comment by andrzejsza** [comment]
could you guys confirm is works as expected with the 2.4 beta?

**Comment by andrzejsza** [comment]
seems that it does. closing.

**Comment by fthx** [comment]
This issue or something near is still open.
Case: Ubuntu session (so GNOME), hybrid NVIDIA/Intel, Wayland session.
GUI does not launch (2.4.8 or 3.0.10) then makes the bridge unavailable in Thunderbird (unable to connect to localhost).
No issue using a non-hybrid setup (iGPU only or NVIDIA only).
