### ISSUE TITLE
[Bridge 2.1.0] London does not build on Fedora 35 

### ISSUE THREAD

**Issue by doggodanubus** [ProtonMail/proton-bridge#249]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

I get this error when running make build. I recently scrubbed Fedora 34 off my system and installed Fedora 35 so I do not have the version of go you'd previously installed. Well I think you'd installed it local.

tower:proton-bridge-master$ make build
make: go: No such file or directory
fatal: Needed a single revision
make: *** No rule to make target 'cmd/Desktop-Bridge/deploy/', needed by 'bridge__.tgz'.  Stop.

## Expected Behavior

I believe 2.01+git would go fetch go

## Current Behavior

tower:proton-bridge-master$ make build
make: go: No such file or directory
fatal: Needed a single revision
make: *** No rule to make target 'cmd/Desktop-Bridge/deploy/', needed by 'bridge__.tgz'.  Stop.

## Possible Solution

No idea.

## Steps to Reproduce

1. Run make build
2.
3.
4.

## Version Information

Bridge 2.1.0] London

## Context (Environment)

I will only run programs I compile/build/etc so I pull from git since this is not part of any distributions repository.

## Detailed Description

None

## Possible Implementation

None

**Comment by andrzejsza** [comment]
fixed a while back, with 2.3
