### ISSUE TITLE
High CPU usage when doing nothing

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#25]
Basically, when I run it, my fan does not stop at all. Proton-bridge is 120% CPU usage in htop. No program is interfacing with it. So no message encryption should occur.

![Screenshot_2020-04-23_17-03-46](https://user-images.githubusercontent.com/2256039/80115209-c1b0fb00-8584-11ea-844d-da71355c965a.jpeg)

**Comment by jameshoulahan** [comment]
Are you able to consistently reproduce this? If so, it would be very helpful for us to know what bridge is doing -- could you run it with `--log-level trace` and see what kind of activity that shows?

**Comment by exander77** [comment]
It basically spams this:

```
TRAC[Apr 24 14:05:19.505] IMAP IDLE unavailable                         pkg=store user="removed"
TRAC[Apr 24 14:05:19.505] IDLE status                                   address=removed mailbox=removed pkg=store total=0 unread=0 user="removed"
```

For all the users, mailboxes etc. It goes non stop very fast. CPU usage 120-130% again.

**Comment by horejsek** [comment]
This means sync is ongoing. Bridge is syncing all messages from API and it will use CPU resources. The only thing we can do here is to not do it in parallel but it would slow down bridge a lot. Once full sync is finished, it will be OK.

We had also problem where we sent many IDLE updates to IMAP client which was not needed. It's going to be fixed with next version.

**Comment by exander77** [comment]
@horejsek Syncing with what? No program was accessing it.

**Comment by horejsek** [comment]
When you log in, bridge needs to sync all metadata from server so bridge can construct local database with metadata used to produce responses to IMAP clients. If your account contains only few messages, this can be done in few seconds; if your account contains hundred of thousands of messages, it can take few hours (of course, depends also on internet speed). Even if IMAP client is not connected, bridge does the sync to be ready when IMAP client connects. The sync is ideally done only once at the beginning but can happen again when bridge was not connected for long time and account have so many changes that it's easier to do full re-sync again.

**Comment by horejsek** [comment]
Hope this explanation solves your question. We plan to show status what bridge is doing somehow. For now we don't know how to tackle it properly yet. So hopefully once it will be more clear why bridge is using CPU resources.

**Comment by exander77** [comment]
I left it for hours, it didn't recover from the problem. I didn't fetch new emails. Deleted mails popped back again because it was not able to confirm their deletion.

I solved it by clearing the cache.

So this should be investigated.

The easiest way I suggest is, delete 50k emails and see what happens.
