### ISSUE TITLE
inbox sync issues via mbsync

### ISSUE THREAD

**Issue by hakova** [ProtonMail/proton-bridge#250]
Hi,

I have been using neomutt as my mail client to access my protonmail account via protonmail-bridge without issues for more than 3 years now. However, since mid December, I noticed that my local inbox is not properly synced with my far side protonmail inbox. I use mbsync to pull my emails and when I run this in verbose mode, I can see that it does connect to the bridge and pulls emails from far side inbox without reporting any errors, as well as pulling emails from other folders. Although all emails are pulled and placed in their appropriate folders after this sync, only the emails in inbox do not appear in my local/near inbox. The last time this sync worked properly was December 6 to be accurate. I confirm that this is the case for the two computers that I try: my laptop and my desktop. The former runs arch linux whereas the latter does manjaro linux. Any pointer will be greatly appreciated. I am more than happy to help in troubleshooting if you need the output of certain executions.

Thanks!

**Comment by andrzejsza** [comment]
hi there. seems to be correlated with the V2 beta release - neomutt might not like our changes to cache. have you tried disabling Bridge's local cache (in advanced settings)?

**Comment by hakova** [comment]
Thank you so much for the quick response! I am not sure I can find that setting. My bridge version is 1.8.12+git. Perhaps it has not been implemented in this version yet? I posted an image of my advanced settings below. I hope it helps clarify the issue.

![image](https://user-images.githubusercontent.com/1278438/151682245-71be47fe-7de7-4985-a9be-e9e8bfcfe222.png)

**Comment by hakova** [comment]
Yes, after hours of troubleshooting, I found that this wasn't a protonmail-bridge issue, but related to either neomutt directory structure or uidvalidity that mbsync uses. It is now fixed, I am closing the issue.

Thanks!
