### ISSUE TITLE
Notifications cover "Back" Button

### ISSUE THREAD

**Issue by A6GibKm** [ProtonMail/proton-bridge#251]
Notifications appear in the top of the window:

![image](https://user-images.githubusercontent.com/11528996/152322692-05cb6d4d-9613-4baa-9f29-073fb5e58b7e.png)

Meaning that some interactions like pressing the Back button cannot be done without manually dismissing the notification, doing notifications on the bottom of the window is in many cases a better approach. 

Another related issue is that notifications do not disappear after N seconds.

**Comment by andrzejsza** [comment]
yes, this is by design as things stand - most of the notifications will have a manual action. we will be reviewing some of them, but won't be changing the design approach here.
