### ISSUE TITLE
Cache should not be stored in ~/.config by default

### ISSUE THREAD

**Issue by ploum** [ProtonMail/proton-bridge#252]
In Linux computers, a cache should never be stored in a .config folder.  (reason being that lot of people make backups of their .config folder, through .git, .rsync, etc.  Also, when debugging, a cache could be easily wipped).

 This is covered by the Freedesktop specification:

https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html
see https://ploum.net/207-modify-your-application-to-use-xdg-folders/

On most desktop, the value of $XDG_CACHE_HOME should be used. If this variable is not set, a safe bet is to use ~/.cache/

Lot of libraries exists to get that XDG value in most languages.

**Comment by ploum** [comment]
Note that libraries are really not required in this case. The code is simply:

if os.env.$XDG_CACHE_DIR : then cache_path = join(os.env.$XDG_CACHE_DIR,protonmail-bridge)
else cache_path = ~/.cache/protonmail-bridge

**Comment by andrzejsza** [comment]
very valid and fixed in v3 (current beta 3.0.8) - cache is stored in .cache or .local/cache depending on the setup.
