### ISSUE TITLE
No way to close the bridge on Linux

### ISSUE THREAD

**Issue by ploum** [ProtonMail/proton-bridge#253]
There’s no way to close the bridge on Linux since v2.

Closing the window close to the tray without closing the bridge. Any close shortcut does the same. There’s no "shutdown button" like in V1.

**Comment by ploum** [comment]
Ok, found it, it was really hidden in the menu and does not work well with tiling WM. A shutdown option in the main interface would be nice.

**Comment by michaljenicek** [comment]
I would also like an option to close the bridge from the app itself, especially since the drop-down menu stopped working in Elementary OS in the newest build of bridge.

**Comment by wgomg** [comment]
WIl ask here instead of opening a new issue. Is there a way to start bridge minimized to tray?

**Comment by andrzejsza** [comment]
just add `--no-window`. as for the original issue - the way is there, so closing.
