### ISSUE TITLE
Indicator applet UI is surprising on Gnome

### ISSUE THREAD

**Issue by kortschak** [ProtonMail/proton-bridge#255]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

## Expected Behavior

A single click on applets in the indicator applet bar on Gnome should open a theme-consistent menu.

## Current Behavior

A single click does nothing. A double click brings a theme inconsistent pane which is not really a menu, but which has an almost dark patterned menu button at the bottom right. This menu does not close when the outer pane is dismissed, remaining present when the applet indicator icon is double clicked again to open it.

## Steps to Reproduce

First issue:
1. Single click on the applet indicator icon in Gnome.
2. :cricket: 

Second issue:
1. Double click on the icon.
2. Click on the three dots at the bottom right of the pane.
3. Click away.
4. Double click on the applet indicator icon.

## Version Information

v2.1.0

## Context (Environment)

Ubuntu 18.0.4

**Comment by kortschak** [comment]
This is more than one year stale.

**Comment by LBeernaertProton** [comment]
Hey @kortschak can you check again with the latest version of Bridge (v3.0.20). Do note that the minimum supported OS is Ubuntu 20.04.

**Comment by kortschak** [comment]
No, no I can't. I don't imagine that it will have changed though.

**Comment by LBeernaertProton** [comment]
If the issue persist in v3, please open another ticket as v2 is no longer supported.

**Comment by kortschak** [comment]
If you leave things long enough, you can close anything as unsupported. :clap:
