### ISSUE TITLE
License notification regression

### ISSUE THREAD

**Issue by kortschak** [ProtonMail/proton-bridge#256]
The license advertisement information provided in the help screen of the bridge v2.1.0 does not contain the required license advertisements for third party software that has been used to produce the bridge. This was previously rectified in #135.

Relevant list of projects that should have license advertisements is readily available from [the go mod file](https://github.com/ProtonMail/proton-bridge/blob/v2.1.0/go.mod).

**Comment by andrzejsza** [comment]
the licence can be found in the same place as before - the footer of the help tab and is, as before, distributed with the binaries.
![licence](https://user-images.githubusercontent.com/17064289/155561259-61800205-e72c-4cc2-8331-f5538f2d6bb0.png)

**Comment by kortschak** [comment]
Thank you.

**Comment by andrzejsza** [comment]
so we will do two things:

1. making sure that the dependencies and their licenses listed https://github.com/ProtonMail/proton-bridge/blob/master/COPYING_NOTES.md are uptodate
2. add a link to those to GUI.

will update the ticket once done, sorry it takes more than expected.

**Comment by andrzejsza** [comment]
this is now done in 2.2.0 beta 👌
