### ISSUE TITLE
bridge cli exits silently when bridge service is running

### ISSUE THREAD

**Issue by roberth** [ProtonMail/proton-bridge#259]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

## Expected Behavior

Either print a message to stderr indicating that the bridge must be shut down before running the cli, or allow the cli to run while the service is up.

## Current Behavior

It just exits with no feedback.
The fact that there's no `--help` isn't helping either.

## Steps to Reproduce

1. start the bridge service (I used a nogui build)
2. start the cli
3. nothing happens

## Version Information

proton-bridge 1.8.12 on Linux via Nixpkgs

## Context (Environment)

This is was my first experience with the bridge. I almost gave up.

I'd really appreciate some tutorial-style instructions for cli-based bridge setup. 
Googling the proton bridge cli returns the command reference, which is not suitable for getting started, and does not explain how to run the cli.

## Detailed Description

- [ ] improve docs
  - [ ] add cli setup instructions on the site
  - [ ] link to the setup tutorial in cli reference
 - [ ] add a `--help` text
 - [ ] add a message on stderr when the command terminates because another instance is running

**Comment by Dremor** [comment]
the cli should be accessible even if the bridge is running, and should start a new instance only if there is none running. This behaviour is especially bothering when running it in headless mode, when running it in Docker for example.

As docker images will start the bridge (usually using "protonmail-bridge --cli") from a user inaccessible console, it isn't possible to configure such a deployment without killing the bridges first, start a new cli instance in order to do the configuration, and then restart the container for it to start the deamon again.

**Comment by lucala** [comment]
> In my opinion, the cli should be accessible even if the bridge is running, and should start a new instance only if there is none running. This behaviour is especially bothering when running it in headless mode, when running it in Docker for example.
> 
> As docker images will start the bridge (usually using "protonmail-bridge --cli") from a user inaccessible console, it isn't possible to configure such a deployment without killing the bridges first, start a new cli instance in order to do the configuration, and then restart the container for it to start the daemon again.

Absolutely this! Incredibly annoying the way it is right now.

**Comment by LBeernaertProton** [comment]
Since V2 there has been a `--help` which list all options and in  v3.1 there's now the following log entry when an existing instance of bridge is running:

```
WARN[Apr 14 14:16:21.120] Failed to create lock file; another instance is running 
```

Regarding all the other docker comments, this not an officially supported "platform".
