### ISSUE TITLE
What does the Trash Icon do? The wording is confusing and risky.

### ISSUE THREAD

**Issue by Raarl** [ProtonMail/proton-bridge#263]
**Selecting the Trash Icon next to the "Sign Out" button has a confusing wording.** 
Does selecting "Delete Account" remove the account signed into the application or one's actual ProtonMail account?

![ProtonMail Bridge](https://user-images.githubusercontent.com/98439763/162134299-1205cac5-4a45-4c0c-aff4-038d0db34320.PNG)
![ProtonMail Bridge 2](https://user-images.githubusercontent.com/98439763/162134975-b6ab97cb-a223-494d-9dfa-2b205e068056.PNG)

**Comment by andrzejsza** [comment]
right on. we haven't thought about this. we will change the wording on the confirmation dialog box to make it clear that the deletion is about removing the account from Bridge only.

**Comment by Raarl** [comment]
Thanks!

**Comment by andrzejsza** [comment]
this has now been updated - in beta 2.2.0
