### ISSUE TITLE
Problem list

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#27]
These are the problems I have encountered so far after 14 days of using ProtonMail. I am losing track of what I have reported and how, so I would like to keep it in one place and mark it solved when it is solved. Support advised me that there is no public bug tracking and as most of these relates to Bridge or are somehow connected to Bridge, I would like to keep it here.

**Receiving emails:**
1. Damages some emails by correctly not detecting headers and body, causing the part of headers to be encrypted as part of the body.
Reported to support@protonmail.com
2. Damages signatures on emails, for example, S/MIME.
Reported: https://github.com/ProtonMail/proton-bridge/issues/26
3. Damages attachments encoded as quoted-printable replacing \r\n by \n in binary files.
Reported: https://github.com/ProtonMail/proton-bridge/issues/18
4. Ads Content-Disposition: inline to multipart data.
Reported: https://github.com/ProtonMail/proton-bridge/issues/18
5. Changes encoding to all parts to base64.
Reported: https://github.com/ProtonMail/proton-bridge/issues/18
6. Does not comply with RFC7505 and hijacks emails sent to a domain hosted on ProtonMail even if the MX records do not lead to ProtonMail and by that opens you to a few kinds of a man-in-the-middle attack.
Reported to support@protonmail.com, security@protonmail.com

**Sending and importing emails from ProtonBridge:**
1. Damages signatures on emails, for example, S/MIME.
Reported: https://github.com/ProtonMail/proton-bridge/issues/26
2. Silently shreds any email moved into Sent folder where the From corresponds to the account email (complete loss of that email when moving from a different IMAP account, even the ProtonMail one).
Reported: https://github.com/ProtonMail/proton-bridge/issues/2
3. Unable to import a large number of messages because of various parsing problems, namely:
- NO non-utf8 content without charset specification
- NO mime: duplicate parameter name
- NO mime: invalid media parameter
- NO multipart: NextPart: EOF
- NO malformed MIME header line: <something>
- NO multipart: unexpected line in Next(): <something>
Reported here: https://github.com/ProtonMail/proton-bridge/issues/8, https://github.com/ProtonMail/proton-bridge/issues/18
4. Ads Content-Disposition: attachment to multipart data.
Reported: https://github.com/ProtonMail/proton-bridge/issues/18
5. Fails to import mails over 26214400 bytes.
Reported to support@protonmail.com
6. Randomly fails to return APPENDUID.
Reported to bridge@protonmail.ch
7. Operating with a large number of emails causes unrecoverable 120% CPU usage until the cache was cleared.
Reported: https://github.com/ProtonMail/proton-bridge/issues/25
8. Changes encoding to all parts to base64.
Reported: https://github.com/ProtonMail/proton-bridge/issues/18

**General:**
1. All Mail folder contains Trash and Spam which is non-standard and causes glitches in mail clients (like a complete profile failure).
Reported to support@protonmail.com, bridge@protonmail.ch

**Web UI:**
1. Cannot find emails by subject if it contains /, \ or ? symbols.
Reported to support@protonmail.com
2. Cannot find emails by message-id.
Reported to support@protonmail.com
3. When an email is moved into Sent folder, it shows message of success, but actually fails and messages stay in the original location.
Maybe connected to this somehow as well: https://github.com/ProtonMail/proton-bridge/issues/2
Reported to support@protonmail.com

**Comment by horejsek** [comment]
Thank you for all your reports. We will look into them. But please let's keep only one issue per issue so we can track all of them more easily (e.g. comments in one place). Thank you.

**Comment by horejsek** [comment]
BTW also note this is repository for bridge only, so this is not place where to report web UI or general issues.

**Comment by exander77** [comment]
@horejsek This not so much for you, as it is for me, to keep track, as I hame losing orientation in bug reports I have sent.

**Comment by omicron-b** [comment]
@exander77 you have a fork of Bridge, you can keep track there for yourself
such list in the official repo would confuse other reporters

**Comment by exander77** [comment]
@omicron-b I hope that before that could possibly happen, all of those bugs will be solver for a long time.

**Comment by exander77** [comment]
Another similarly affected: https://www.reddit.com/r/ProtonMail/comments/gbqpud/hard_time_migrating_from_imap_to_protonmail/
