### ISSUE TITLE
Doesn't run on aarch64 (Asahi Linux M1)

### ISSUE THREAD

**Issue by cmalvi** [ProtonMail/proton-bridge#271]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

I'm trying to setup bridge on Asahi Linux on Macbook Air M1, with a 4K kernel patch to run electron apps, but even allowing to build on my machine i can't run proton-bridge.
Running it from terminal call Box64, so i think is always recognized as x86_64 application

## Expected Behavior

Open proton-bridge

## Current Behavior

Doesn't open

## Possible Solution

Add compatibility with aarch64 architecture on Linux

## Steps to Reproduce

1. Install proton-bridge
2. Try to open it

## Version Information

Lastest from github release (2.1.2-1)

## Context (Environment)

Set up my protonmail account

**Comment by andrzejsza** [comment]
closing as a duplicated of https://github.com/ProtonMail/proton-bridge/issues/155

**Comment by cmalvi** [comment]
> closing as a duplicated of #155

The linked issue is about macOS, mine is about Linux

**Comment by cmalvi** [comment]
I’ve also made a pull request to add this info on the Build readme.

Thanks for have reopened the issue

**Comment by LBeernaertProton** [comment]
With  v3.1 it should be possible to run bridge on ARM64 based systems. We can't provide any official package as we currently don't directly support ARM64 based Linux.

**Comment by andirsun** [comment]
@cmalvi How did you install the package an run it in the background ?
