### ISSUE TITLE
No SMTP port conflict warning macOS 

### ISSUE THREAD

**Issue by m4rkv5** [ProtonMail/proton-bridge#274]
When Synology Drive Client is installed, smtp port 1025 is already in use by Synology Drive Clients Finder Sync feature.

## Expected Behavior
Tell the user that the smtp port is already in use.

## Current Behavior
Apple Mail can't connect.

## Possible Solution
Check if the port is already in use.

## Steps to Reproduce
1. Install Synology Drive Client
2. Enable Synology Drive Client Finder extension
3. Install ProtonMail Bridge
4. Try to connect to smtp port 1025 with apple mail.

## Version Information
ProtonMail Bridge 2.1.3

## Context (Environment)
macOS Monterey 12.4
Apple Mail 16.0

**Comment by andrzejsza** [comment]
thanks for the report. we reproduced internally - for internal reference GODT-1566.
