### ISSUE TITLE
flatpak doesn't auto start

### ISSUE THREAD

**Issue by AppleMayExist** [ProtonMail/proton-bridge#277]
The flatpak package of Bridge doesn't auto start when "Open on startup" is checked.

## Expected Behavior
Start up automatically when "Open on startup" is checked

## Current Behavior
Doesn't start automatically

## Steps to Reproduce
1. Setup bridge (flatpak linux)
2. Enable "Open on Startup"
3. Log out and back in
4. observe a lack of opening-on-startupiness

## Version Information
v2.1.3

## Context (Environment)
Currently I've used GNOME Tweaks to start Bridge up at startup, but this opens the window every time I sign in.

## Detailed Description
Have ProtonMail Bridge start up automatically when "Open on startup" switch is flicked on flatpak.

**Comment by Nationalgeographic** [comment]
In Gnome, You can enhance that start up file from `/home/user/.config/autostart/ch.protonmail.protonmail-bridge.desktop`

just change that Exec line to:
`Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=protonmail-bridge ch.protonmail.protonmail-bridge "--no-window"`

mind that `"--no-window"`.

**Comment by Deuchnord** [comment]
The issue does not seem to be only on GNOME: I can reproduce it on Windows and macOS too.
On macOS, you can use the OS features to start the app in the background as a workaround, but on Windows, this bug prevents the app to autostart completely.

**Comment by andrzejsza** [comment]
@Deuchnord can you confirm which version of Bridge are you using? we can't replicate on macOS nor Windows.

**Comment by Deuchnord** [comment]
I'm on v2.2.2

**Comment by jvnknvlgl** [comment]
To fix this, an app would need to place a desktop file for auto-starting in `~/.config/autostart`. Copying `/var/lib/flatpak/exports/share/applications/ch.protonmail.protonmail-bridge.desktop` to this directory of course fixes the issue, as it autostarts the bridge on boot, but it would be nice if it could be started headless, but I can't find a flag to start the bridge without a GUI.

**Comment by parcelcat** [comment]
> To fix this, an app would need to place a desktop file for auto-starting in `~/.config/autostart`. Copying `/var/lib/flatpak/exports/share/applications/ch.protonmail.protonmail-bridge.desktop` to this directory of course fixes the issue, as it autostarts the bridge on boot, but it would be nice if it could be started headless, but I can't find a flag to start the bridge without a GUI.

@jvnknvlgl That flag is `--no-window`. After adding `--no-window` to the end of `Exec=` in the `ch.protonmail.protonmail-bridge.desktop` file copied to `~/.config/autostart`, Proton Mail Bridge auto-starts in a minimized state after starting up.

**Comment by A6GibKm** [comment]
The flatpak app is not maintained by the ProtonMail bridge, please file an issue at https://github.com/flathub/ch.protonmail.protonmail-bridge/pull/95. This could be fixed using the background portal https://flatpak.github.io/xdg-desktop-portal/index.html#gdbus-org.freedesktop.portal.Background.

**Comment by baskin77** [comment]
This problem still exists in Gnome!
The workaround works well by the way. Copy /var/lib/flatpak/exports/share/applications/ch.protonmail.protonmail-bridge.desktop to ~/.config/autostart and then add "--no-window" behind Exec=

**Comment by A6GibKm** [comment]
This issue nothing to do with this repo (which is about the flatpak distribution of the app) nor with GNOME or any DE. Proton Bridge should use the [appropriate portal](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Background.html) for installing auto start files instead of copying a file over the right folder.

**Comment by RokeJulianLockhart** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1851337#c0
