### ISSUE TITLE
Folders with slashes in their names not visible in IMAP clients

### ISSUE THREAD

**Issue by juergh** [ProtonMail/proton-bridge#279]
If a folder name contains a slash '/' it won't show up in an IMAP client. If I change that to a pipe ('|') all works well.

**Comment by andrzejsza** [comment]
yes, this is a known problem - we need to make sure we follow rfc here https://datatracker.ietf.org/doc/html/rfc2683.
more discussion on this here: https://github.com/ProtonMail/proton-bridge/issues/227
closing as the resolution will be included as part of 227, as soon as we figure our how to properly handle subfolders.
