### ISSUE TITLE
Unable to send emails via Protonbridge

### ISSUE THREAD

**Issue by tgm-git** [ProtonMail/proton-bridge#280]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

I have setup a docker container running proton-bridge, version 2.2.0, and have logged into it with a user from my business account. Using the email of the user and the generated password I login to the proton bridge instance from a python service using smtplib.

I am able to login and connect correctly.

## Expected Behavior
When I send an email from my python service and I am using the correct email and password I expect the email to be sent.

## Current Behavior
The bridge hangs for a while before returning the following error.
`smtplib.SMTPSenderRefused: (451, b'4.0.0 backend: invalid return path: not owned by user', 'no-reply@catchscan.com')`
where no-reply@catchscan.com is the user under my business account.

## Possible Solution
If I start the proton bridge and the python instance outside of the docker containers, everything works fine.

## Steps to Reproduce
run a docker container with protonmail bridge and login, then attempt to send an email via python smtplib

## Version Information
proton bridge v2.2.0

## Context (Environment)
I have built the bridge from git repository under the `golang:1.15` container.

## Detailed Description
I should be able to send emails when the proton-bridge is in a docker container. Or perhaps a clearer error description.
At the moment I do not understand why a user does not own their own email address

The error is returned from the backend, perhaps there is something in the logs on your end?

**Comment by tgm-git** [comment]
Dockerfile 
```# syntax=docker/dockerfile:1.2
FROM golang:1.15 AS build

# Build
RUN apt update && apt install -y libsecret-1-dev

WORKDIR /build/
COPY make.sh VERSION /build/
RUN bash make.sh

#FROM debian:latest
FROM ubuntu:bionic
LABEL maintainer="Thomas G. McCollin  <tgm@catchscan.com>"

EXPOSE 25/tcp
EXPOSE 143/tcp

# Install run time dependencies
RUN apt update \
	&& apt install -y --no-install-recommends socat pass libsecret-1-0 ca-certificates python3 \
	&& rm -rf /var/lib/apt/lists/*

RUN mkdir -p /home/agent/
COPY --from=build /build/proton-bridge/proton-bridge /home/agent/
RUN apt update && apt install -y curl procps htop nmap

RUN mkdir -p /home/agent/credentials/debug
WORKDIR /home/agent/credentials

ADD key-spec key-spec
ADD entrypoint.sh entrypoint.sh

RUN --mount=type=secret,id=psw cat /run/secrets/psw > .psw
RUN --mount=type=secret,id=usr cat /run/secrets/usr > .usr

# Create user
#RUN useradd -u 4211 agent
#RUN chown -R agent:agent /home/agent
#USER agent

# Generate gpg key for pass
RUN gpg --generate-key --batch key-spec
RUN pass init pass-key

# Login to account
RUN (printf "login\n$(cat .usr)\n$(cat .psw)\n" && cat) | /home/agent/proton-bridge -c
RUN echo info | /home/agent/proton-bridge -c | grep -m1 "Password" > /home/agent/credentials/debug/.password_entry
RUN cat /home/agent/credentials/debug/.password_entry | awk '{print $2}' > /home/agent/credentials/password
RUN rm .usr .psw

ENTRYPOINT ["bash", "/home/agent/credentials/entrypoint.sh"]
#CMD bash
```

make.sh
```
#!/bin/bash

set -ex

VERSION=`cat VERSION`

# Clone new code
git clone https://github.com/ProtonMail/proton-bridge.git
cd proton-bridge
git checkout v$VERSION

# Replace host ip to  0.0.0.0
#sed -i 's/Host = "127.0.0.1"/Host = "0.0.0.0"/' internal/bridge/constants.go

# Build
if ! make build-nogui ; then
	# If build fails it's probably because it is a 32bit
	# system and there was a overflow error on the parser
	# This is a workaround for this problem found at:
	#   https://github.com/antlr/antlr4/issues/2433#issuecomment-774514106
	find $(go env GOPATH)/pkg/mod/github.com/\!proton\!mail/go-rfc5322*/ -type f -exec sed -i.bak 's/(1<</(int64(1)<</g' {} +

	# Try again after implementing the workaround
	if ! make build-nogui ; then
		echo "Build did not work!"
		exit $?
	fi
fi
```

entrypoint.sh
```
#!/bin/bash

set -ex

# Initialize
# socat will make the conn appear to come from 127.0.0.1
# ProtonMail Bridge currently expects that.
# It also allows us to bind to the real ports :)
socat TCP-LISTEN:25,fork TCP:127.0.0.1:1025 &
socat TCP-LISTEN:143,fork TCP:127.0.0.1:1143 &


# Generate gpg key for pass
gpg --generate-key --batch key-spec
pass init pass-key

# Start http server
python3 -m http.server 80 &

# Start protonmail
# Fake a terminal, so it does not quit because of EOF...
rm -f faketty
mkfifo faketty
cat faketty | /home/agent/proton-bridge -c
```

**Comment by tgm-git** [comment]
The problem seems to related to DNS lookup. I have found the following errors in the container.

```
ERRO[Jun 15 09:00:00.148] Timed out querying DNS records                pkg=pmapi provider="https://dns11.quad9.net/dns-query"
2022/06/15 09:00:00.148509 ERROR RESTY Get "https://api.protonmail.ch/metrics?Action=daily&Category=heartbeat&Label=": failed to find a usable proxy: timed out while refreshing proxy cache, Attempt 4
ERRO[Jun 15 09:00:00.148] Timed out querying DNS records                pkg=pmapi provider="https://dns11.quad9.net:5053/dns-query"
ERRO[Jun 15 09:00:00.148] Timed out querying DNS records                pkg=pmapi provider="https://dns.google/dns-query"
ERRO[Jun 15 09:00:20.148] Timed out querying DNS records                pkg=pmapi provider="https://dns11.quad9.net/dns-query"
ERRO[Jun 15 09:00:20.148] Timed out querying DNS records                pkg=pmapi provider="https://dns11.quad9.net:5053/dns-query"
ERRO[Jun 15 09:00:20.148] Timed out querying DNS records                pkg=pmapi provider="https://dns.google/dns-query"
```

**Comment by tgm-git** [comment]
I found the problem and fixed it, this issue can be considered closed.

The solution was that I was running the container in docker-compose network and had set the network to `internal`, which I had not realised severs incoming _and_ outgoing traffic.

**Comment by plind-dm** [comment]
@tgm-git I'm facing same error. Would you provide the solution in more detail?

**Comment by tgm-git** [comment]
@plind-dm  You need to serve the docker container in a network in bridge mode or host net.
