### ISSUE TITLE
Running Proton-Bridge gets me banned from Proton's servers!

### ISSUE THREAD

**Issue by mmanjos** [ProtonMail/proton-bridge#281]
This has started happening over the last few weeks. If Proton has a general outage, and I send a mail through proton-bridge locally, something causes me to be BANNED from Proton's API.

When this happens, all clients (web, Android and proton-bridge itself) at my home IP address get banned for hours, until I manually shut down proton-bridge and let the ban expire.

THIS IS INCREDIBLY FRUSTRATING. I've tried reporting this to support, but the ticket has gone nowhere.

## Current Behavior
When Proton's API starts returning errors, proton-bridge logs these messages:
```
Jun 14 18:36:17 x protonmail-bridge[1506]: 2022/06/14 18:36:17.380913 ERROR RESTY Get "https://api.protonmail.ch/mail/v4/settings": read tcp x:49928->185.70.42.25:443: read: connection reset by peer, Attempt 2
Jun 14 18:36:17 x protonmail-bridge[1506]: 2022/06/14 18:36:17.413105 ERROR RESTY Get "https://api.protonmail.ch/mail/v4/settings": read tcp x:49930->185.70.42.25:443: read: connection reset by peer, Attempt 6
Jun 14 18:36:17 x protonmail-bridge[1506]: 2022/06/14 18:36:17.977365 ERROR RESTY Get "https://api.protonmail.ch/mail/v4/settings": read tcp x:49932->185.70.42.25:443: read: connection reset by peer, Attempt 3
Jun 14 18:36:18 x protonmail-bridge[1506]: 2022/06/14 18:36:18.758519 ERROR RESTY Get "https://api.protonmail.ch/mail/v4/settings": read tcp x:49934->185.70.42.25:443: read: connection reset by peer, Attempt 4
Jun 14 18:36:19 x protonmail-bridge[1506]: 2022/06/14 18:36:19.677578 ERROR RESTY Get "https://api.protonmail.ch/mail/v4/settings": read tcp x:49936->185.70.42.25:443: read: connection reset by peer, Attempt 5
```

After Proton comes back up, my IP is still banned from the servers. Trying to load my account using the Android app gives me a "no connection to server" error and trying to load my account in a web browser displays: 

403 Forbidden
Request forbidden by administrative rules.

## Possible Solution
Either Proton's security team need to **FIX** their rules that are causing proton-bridge users to be banned from the API, or proton-bridge needs to implement more intelligent exponential back-off. 

## Version Information
ProtonMail Bridge version 2.1.1

**Comment by mmanjos** [comment]
This happened with only 1 message queued to be sent by proton-bridge. 

I can't keep using proton if this tool continues to block me from using services.

**Comment by andrzejsza** [comment]
thanks for the report. sorry to hear the support ticket when nowhere  - it has now been found so best to continue the conversation there.
for visibility - we've investigated the problem in the meantime. When handling an SMTP send command, the first thing Bridge does is fetch the most up-to-date sending settings from the proton API. If this fails, it errors out. It appears that the SMTP client reacts to this error by immediately retrying the send operation, leading to bridge sending an overwhelming number of (failing) API requests to the server.
It's quite clear now that we should add an exponential backoff when handling failed SMTP send commands. We will aim to do that in the next release.
In the meantime, the SMTP client could likely be configured to wait before retrying a failed SMTP send request.

**Comment by mmanjos** [comment]
Closing this one - it hasn't been an issue since the initial report about a year ago (when it seems like the API anti-ddos settings were refined)
