### ISSUE TITLE
Bridge Blank Black Window on Fedora 36 KDE desktop

### ISSUE THREAD

**Issue by itsjustarumour** [ProtonMail/proton-bridge#283]
Proton Bridge opens with blank black window on Fedora 36, using Wayland display server and NVidia driver.  Works fine with Xorg.

NVIDIA GeForce GTX 660 
NVDIA 470.129.06 driver
Fedora Linux 36 (Workstation Edition)
64-bit
GNOME Version 42.2

## Expected Behavior

Proton Bridge window should display contents correctly.

## Current Behavior

Proton Bridge opens with blank black window

## Possible Solution

No idea.  

## Steps to Reproduce

1.  Open application.
2.  Window opens, and is blank/black.

## Version Information

v2.1.3

## Context (Environment)

Stops me seeing any Proton Bridge settings

**Comment by andrzejsza** [comment]
could you confirm with 2.4.0 (you need to enable beta access)?

**Comment by itsjustarumour** [comment]
> could you confirm with 2.4.0 (you need to enable beta access)?

Hi Andrzejsza, just tried the 2.4.0 beta.  That seemed to work!  Many thanks :-)

**Comment by itsjustarumour** [comment]
Hi Andrzejsza, I'm afraid I spoke too soon.

v2.4.0 fixed the issue on Fedora 36 with GNOME 42.  

However, I've just tried on the same Fedora 36 installation with the KDE desktop, and the v2.4.0 window is blank.

Can this bug be re-opened?

**Comment by itsjustarumour** [comment]
@andrzejsza Thanks for re-opening this bug.

I've just upgraded my machine to an MSI NVidia Geforce GTX 1660 Super graphics card, and upgraded the driver to NVidia 5.15 series.

I'm still seeing the same behaviour on Wayland - Bridge window displays fine in GNOME 42, but is blank in KDE.

**Comment by itsjustarumour** [comment]
I've now upgraded to Fedora 37, GNOME 43 and Proton Bridge v2.4.3.  I still have the same issue - window displays OK in GNOME, but is blank in KDE.

**Comment by novacellus** [comment]
Same on Kubuntu 22.10, KDE 5.26.5, Wayland, NVIDIA GTX 1060.

**Comment by LBeernaertProton** [comment]
I kindly request everyone still using v2 to upgrade to v3 and check if the issue still persists.

**Comment by RTheren** [comment]
Hi.

I have tested this on version 3.0.21

**Comment by LBeernaertProton** [comment]
Can you try starting the GUI with the `--software-renderer` flag?

**Comment by RTheren** [comment]
Yup, and it loads! I haven't noticed this flag before, otherwise I'd absolutely try it out first :D 
![image](https://user-images.githubusercontent.com/12765090/228807275-8adbc357-e874-442c-9b5d-d3ef63927f1b.png)
