### ISSUE TITLE
Unable to retrieve some mails, malformed MIME header

### ISSUE THREAD

**Issue by aaclause** [ProtonMail/proton-bridge#285]
For a few months, I have been unable to retrieve certain emails. Thunderbird tells that the server replied:
`list message build: malformed MIME header: missing colon: "<truncated subject>"`

Proton Mail Bridge Logs say:
`[31mERRO[0m[<date>] cannot list messages (true, <ID>, [UID RFC822.SIZE FLAGS BODY.PEEK[HEADER.FIELDS (FROM TO CC BCC SUBJECT DATE MESSAGE-ID PRIORITY X-PRIORITY REFERENCES NEWSGROUPS IN-REPLY-TO CONTENT-TYPE REPLY-TO)]]): list message build: malformed MIME header: missing colon: "<extract from the beginning of the message>"  [31mpkg[0m=imap`

I tried deleting the cache, reinstalling the Bridge, tested on another machine... Same issue.

Any idea to solve this?

I'm running on v2.2.2, but it's been there since at least v2.0.

**Comment by andrzejsza** [comment]
sorry for the late reply - missed this issue completely. if you still have this problem, could you please contact bridge@protonmail.ch? we would need to have a look at some of those headers to confirm. closing the issue here.
