### ISSUE TITLE
GUI is rendered very tiny on high DPI monitors

### ISSUE THREAD

**Issue by manuth** [ProtonMail/proton-bridge#286]
## Expected Behavior
The application should be rendered in accord to the DPI configured in the system settings.

## Current Behavior
The application is rendered with 100% DPI.

## Possible Solution
Sadly I have never worked with go and thus know of no solution.

## Steps to Reproduce
1. For better convenience, you should test this on a High-DPI monitor. Otherwise you might suffer from eye cancer.
2. Set your system's DPI to more than 100% (150% or 200%)
3. Take note that the GUI is rendered very tiny while other applications are rendered according to the chosen DPI

![image](https://user-images.githubusercontent.com/7085564/181758293-fedbc82e-4e08-46cc-8ece-29c8961a7e56.png)

## Version Information
  - ProtonMail Bridge v2.2.2.0

## Context (Environment)
  - I had quite a struggle with logging in to Proton Mail Bridge trying to read the tiny labels in the GUI

## Detailed Description
n/a

## Possible Implementation
n/a

**Comment by j0siah** [comment]
I also have this issue!

**Comment by andrzejsza** [comment]
can you confirm which OS/installer are you using?

**Comment by manuth** [comment]
> can you confirm which OS/installer are you using?

Assuming that you're addressing me:
I'm running ProtonMail Bridge on a Windows 11 machine (Version 21H2).
I installed it from `account.proton.me`
The download link points to the following address: <https://protonmail.com/download/bridge/Bridge-Installer.exe>

**Comment by andrzejsza** [comment]
mhm, thanks for confirming. could you please install this and confirm if you still have the same problem? https://drive.proton.me/urls/C9MBVHSE2W#xIqh0mHWwhtc
it's an internal alpha so best to uninstall after testing.

**Comment by manuth** [comment]
I can confirm that the scaling of this version of Proton Mail Bridge is working properly.

**Comment by andrzejsza** [comment]
great. thank you for checking 🙏 it will be in beta as soon as we fix some regressions there.

**Comment by manuth** [comment]
Until the next version is released, you might want to use this workaround:
1. Open up the directory containing `proton-bridge.exe` (usually `C:\Program Files\Proton AG\Proton Mail Bridge`)
2. Hit the right mouse button on `proton-bridge.exe` and open up its Properties
3. Open up the `Compatibility` tab and optionally open up `Change settings for all users` if you'd like to apply the workaround for all users on your computer
4. Hit `Change high DPI settings`
5. On the bottom of this dialogue, tick `Override high DPI scaling behavior`
6. Select `System (Enhanced)`

Notice that Proton Mail Bridge will appear blurry when using this workaround.
Thus, keep in mind to revert this workaround again once a fixed version of Proton Mail Bridge has been released and installed. Otherwise, Proton Mail Bridge will keep appearing blurry.

**Comment by cornopaez** [comment]
Can confirm that this happens also in Ubuntu 22.04.01. I can assist with testing in Ubuntu if needed.

**Comment by andrzejsza** [comment]
thanks @cornopaez. could you try this build? https://drive.proton.me/urls/3FPXWRXQPC#GOZZprL3RNWk

**Comment by cornopaez** [comment]
Hey @andrzejsza. Downloaded and installed but nothing changed. Everything is very tiny still.

**Comment by gabor-meszaros** [comment]
Hi @cornopaez , can you please try this one:

1. Create a file with the name ```qt.conf``` and content:
  > [Platforms]
  > WindowsArguments = dpiawareness=0
2. Copy it next next to the ```Desktop-Bridge.exe```, so most probably to ```C:\Program Files\Proton Technologies AG\ProtonMail Bridge```.
3. Restart the application with "Quit Bridge" (i.e., not just minimize it with the close button that put it to the background)

**Comment by joshhansen** [comment]
Also having this scaling issue. Linux Mint 21, Protonmail Bridge 2.3.0 installed via Flathub.

**Comment by LBeernaertProton** [comment]
Is anyone still having this issue on the latest version of bridge (v3) ?

**Comment by LBeernaertProton** [comment]
Closed as it seems reported to be fixed with duplicate ticket https://github.com/ProtonMail/proton-bridge/issues/254#issuecomment-1510741972
