### ISSUE TITLE
Icon not disappearing from notification area when quitting from bridge

### ISSUE THREAD

**Issue by Raarl** [ProtonMail/proton-bridge#287]
## Expected Behavior
When quitting from "Proton Mail Bridge", the icon on the notification area should disappear.

## Current Behavior
When quitting from "Proton Mail Bridge", the icon on the notification area instead stays. And when having the setting for a disappearing taskbar, it keeps the taskbar upfront.

## Possible Solution
To fix this, the user has to hover their mouse pointer over the icon to make it disappear.

## Steps to Reproduce

1.Open "Proton Mail Bridge"
2.Right click the icon on the notification area.
3.Click on the "3-dots" and then select "Quit Bridge"
4.The application will quit but the icon will stay, displaying the issue.

## Version Information
v2.2.2 | Windows 10

## Context (Environment)
I have my taskbar set to disappear from my screen after a certain time. This issue makes it so that I have to constantly hover my pointer over the icon to turn my taskbar back to its hidden state.

## Detailed Description
Make the icon disappear when quitting from the application

## Possible Implementation
Add options in minimizing to tray.

**Comment by andrzejsza** [comment]
looking into this. for internal reference: GODT-1820

**Comment by andrzejsza** [comment]
fixed with new beta (2.4.0).
