### ISSUE TITLE
Signed releases 

### ISSUE THREAD

**Issue by ubbabeck** [ProtonMail/proton-bridge#290]
I would appreate if you added gpg signed releases in the release notes for all new versions.

**Comment by cuthix** [comment]
Hi,
do you mean to sign the assets in releases published on github https://github.com/ProtonMail/proton-bridge/releases/  ?

FYI: All assets are signed and signature is published on our website e.g.:

https://proton.me/download/bridge/Bridge-Installer.dmg
https://proton.me/download/bridge/Bridge-Installer.dmg.sig

where also public key is available:

https://proton.me/download/bridge/bridge_pubkey.gpg

**Comment by ubbabeck** [comment]
Yes, that would be nice to have them in the relases published on github too.

Thank you, that was what I where looking for.
