### ISSUE TITLE
Thunderbird OpenPGP message corruption error with 3rd party PGP keys

### ISSUE THREAD

**Issue by cares8** [ProtonMail/proton-bridge#291]
## Current Behavior
When using either Thunderbird or Betterbird with Proton Mail Bridge, if using 3rd-party PGP keys (for example using Yubikey's PGP function or a keypair created with gnupg), it will cause Thunderbird to show the following error message when trying to open the encrypted email (for example in Sent or Inbox):

```
This is an OpenPGP message that was apparently corrupted by MS-Exchange. If the message contents isn't shown as expected, you can try an automatic repair.
```

The repair fails if doing it from inside the user's live Protonmail account folders, but works if copy-pasted to a local folder after which the message is displayed properly. (Noteworthy: if tried in a "live" folder, not only does it not work, the message disappears, but yet is still available via the webmail interface).

Oddly enough, when using Outlook with 3rd-party keys and Proton Mail Bridge, no such issue happens. In fact, Outlook can also decrypt messages sent from a Thunderbird client with no issues, so it appears Thunderbird is sending properly.

I've looked at past issues #28 and #216, but not sure if this is related.

## Version Information
Proton Mail Bridge 2.2.2 - Linux
Thunderbird 91.12.0 and Betterbird 91.13.0 (Linux)

Edit to add: forgot to mention this doesn't happen if using another mail service.

Any thoughts?

**Comment by dsommers** [comment]
More recent reports about the same issue: https://www.reddit.com/r/ProtonMail/comments/y6p5m4/encrypted_emails_sent_through_proton_bridge_are/

**Comment by LBeernaertProton** [comment]
Closing as v2 is no longer support and according to https://github.com/ProtonMail/proton-bridge/issues/320#issuecomment-1350901372 this is not something we are going to support.

**Comment by seanbethard** [comment]
Y U No support my key?

**Comment by Tauwasser** [comment]
I also just ran into this issue and have to say that this is a very disappointing decision to say the least. I'm fully okay with opportunistic encryption to protonmail recipients, but if I sent an already-encrypted e-mail to a non-protonmail recipient, I expect it to Just Work™.

I don't understand why using ProtonBridge has to go out of its way to break the e-mail?

**Comment by dsommers** [comment]
@Tauwasser Can you elaborate more here?  I've used external PGP keys (with private key on a Yubikey) successfully since the v3 generation of the Proton Mail Bridge (based on gluon) together with the [Proton SMTP Submission](https://proton.me/support/smtp-submission#setup) feature for sending e-mails using those keys.

Incoming mails are using my external public PGP key are decrypted by Thunderbird instead of Proton Mail Bridge and outgoing mails signed with my external PGP are sent via the SMTP Submission feature.

**Comment by Tauwasser** [comment]
@dsommers I basically did what the original reporter did: I sent a fully encrypted e-mail to a non-protonmail recipient. Viewing the e-mail in the sent folder gives the reported error message and shows an empty e-mail with two attachments: `attachment.bin` and `encrypted.asc`:
![image](https://github.com/user-attachments/assets/23abfaca-7860-425e-886c-ae22fc381b66)

`attachment.bin` only contains 12 bytes: "Version 1\0x0D\0x0A". The message I sent does contain an attachment, if that matters. I can save and manually decrypt `encrypted.asc` using gpg and my private key, which yields the correct e-mail contents (headers, base64-encoded body + attachments). However, I'm not sure if the e-mail was actually sent correctly to the recipient :(

Unfortunately, repairing the e-mail in an offline folder does not work as expected and prompts for the wrong private key after repairing and trying to manually decrypt using gpg.

I just noticed that apparently Proton SMTP Submission is a separate feature from the Protonmail Bridge? Could it be related to that? Basically, I would expect to be able to read encrypted message in my sent folder without manually saving/decrypting and without the "corrupted OpenPGP message" pop-up.

**Comment by dsommers** [comment]
> I sent a fully encrypted e-mail to a non-protonmail recipient. Viewing the e-mail in the sent folder gives the reported error message and shows an empty e-mail with two attachments: attachment.bin and encrypted.asc

Sending PGP encrypted mails using external PGP keys via the Proton Mail Bridge will still fail.  You need the Proton SMTP Submission approach for external PGP keys to work.

> I just noticed that apparently Proton SMTP Submission is a separate feature from the Protonmail Bridge?

Yes, that is correct.  Proton SMTP Submission is basically a standard SMTP service for Proton users on paid plans with their own domains.  The mail client will connect directly to a Proton server and not pass the traffic via Proton Mail Bridge.  The downside for ordinary mail traffic is that it won't do opportunistic encryption automatically - unless your mail client does it for you instead.  So the chances of inadvertently sending more mails unencrypted unknowingly is quite higher.  So use with care.

**Comment by Tauwasser** [comment]
> Sending PGP encrypted mails using external PGP keys via the Proton Mail Bridge will still fail. You need the Proton SMTP Submission approach for external PGP keys to work.

Yeah, this is king of what I meant that Proton Mail (Bridge) is seemingly going out of their way to break this? At least an error/warning message would have been nice.

> Proton SMTP Submission is basically a standard SMTP service for Proton users on paid plans with their own domains

I am on a paid plan with multiple domains, yet apparently I need a business plan as well? This is honestly very confusing and discouraging :(
