### ISSUE TITLE
Cannot configure Apple Mail on MacOS Ventura

### ISSUE THREAD

**Issue by cravend** [ProtonMail/proton-bridge#293]
## Expected Behavior
Configuring Apple Mail should automatically install a profile.

## Current Behavior
The app freezes and no profile is installed.

## Steps to Reproduce
1. Click configure
2. Click Apple Mail
3. Click Configure automatically
4. A profile is not installed

## Version Information
v2.2.2, macOS Ventura (16.0)

**Comment by andrzejsza** [comment]
this is already fixed in the recent beta - 2.3.0 👍
