### ISSUE TITLE
Linux/Gnome AppIndicator icon creates empty space

### ISSUE THREAD

**Issue by enewbury** [ProtonMail/proton-bridge#294]
## Expected Behavior
When unlocking computer, the protonmail appindicator should remain in the tray with no empty spaces

## Current Behavior
Every time the computer is unlocked after sleep, an empty space is created in the tray (common Gnome Desktop Environment extension [AppIndicators and KStatusNotifierItem Support](https://extensions.gnome.org/extension/615/appindicator-support/)
![Screenshot from 2022-09-07 11-47-17](https://user-images.githubusercontent.com/4422419/188922969-1c0cd024-69a7-4248-b233-a1cc2221ab3f.png)

The issue compounds itself because every subsquent unlock creates an additional new space, making a computer restart required or the tray overflows and becomes useless.

## Steps to Reproduce

1. Running Fedora 36, Gnome Desktop w/ Wayland, AppIndicators extension
2. Installed Protonmail (via Flatpak)
3. Close the laptop lid
4. Open laptop and log in w/ passoword
5. See extra space created in tray
6. Close again and repeat, see additional space created each time.

## Version Information

2.2.2 and all previous versions. | Linux Flatpak (and RPM)

## Context (Environment)

AppIndicators are probably the most common extension on Gnome since it allows me to see apps running in the background, and because this is a compounding issue where a new space is created every time the computer sleeps, it renders my tray useless after a few hours in the day, requiring a restart. The issue has been so bothersome, that I've been unable to use the bridge at all for the last year. I hoped with the major release this issue would be fixed, but unfortunately it seems the time has come to officially report it.

**Comment by A6GibKm** [comment]
App indicators and wayland are more or less incompatible, so that might be causing the issue.

**Comment by enewbury** [comment]
Huh, surprised to hear that, I've been using apps like 1password, element, slack, nextcloud, and others on gnome Wayland with appindicators and haven't had any problems. Any idea how they could be making it work?

**Comment by A6GibKm** [comment]
Because some parts of it might work, but others might not.

**Comment by LBeernaertProton** [comment]
@enewbury In 3.2.0 we replaced the context menu with a native implementation. Does that fix the problem for you?

**Comment by LBeernaertProton** [comment]
Previously the context menu was written using QML. In 3.2.0 we switched 
to QWidgets (native), which better resembles the native style context 
menu for the OS.

**Comment by enewbury** [comment]
Hey @LBeernaertProton , sorry I've not been using linux for a while b/c work requirements, but I just popped it up, got everything updated, and confirming the issue is resolved with the new implementation! Thanks ya'll!
