### ISSUE TITLE
Bridge 2.4.0 gRPC backend failure

### ISSUE THREAD

**Issue by tpeacock19** [ProtonMail/proton-bridge#299]
I have upgraded my bridge from 2.3.0 to the pre-release of 2.4.0 and it is giving me some problems. I've tried starting it both with, and without my ProtonVPN active.

## Expected Behavior

The bridge should start 

## Current Behavior
The bridge does not start and returns the error `Cannot connectToServer to go backend via gRPC: Server failed to generate certificate on time`.

## Steps to Reproduce
1. Install the bridge using the PKGBUILD, or using the automatic upgrade from 2.3.0
2. Try to start proton-bridge from cli or using desktop application

## Detailed Description

OS: Arch Linux
Kernel: 5.19.11-zen1-1-zen 
Compositor/WM: Wayland (River)

```shell
 ❯ VERBOSITY=debug /usr/lib/protonmail/bridge/proton-bridge                 28s 130
[INFO] lock file created /home/morpheus/.local/var/cache/.cache/protonmail/bridge/bridge-gui.lock
[DEBUG] Bridge executable path: /usr/lib/protonmail/bridge/bridge
Cannot connectToServer to go backend via gRPC: Server failed to generate certificate on time
```

Additionally, I tried cloning and building the bridge locally but the Makefile complains of a missing qt.conf file and tells me to set `QT6DIR`. I set `QT6DIR` to the location in the cache where the update resides and has the bundled qt6 files. But I'm not sure what the qt.conf file should contain. Is there a more explicit instruction on how to build the 2.4.0 bridge locally?

**Comment by tpeacock19** [comment]
I've installed QT from the recommended link in the bridge-gui README.md (https://www.qt.io/download-open-source) and was able to successfully build the program. However, I still run into the previously described error.

**Comment by andrzejsza** [comment]
thanks for the report. we've hit that internally to, working on the fix.

**Comment by MartenBE** [comment]
Is there a hint on the release date of the fix? I can't use the protonmailbridge for nearly a month at the moment due to this error on the protonmail-bridge-2.3.0-1.x86_64.rpm version.

**Comment by andrzejsza** [comment]
could you please check with 2.4.3.? https://github.com/ProtonMail/proton-bridge/releases/tag/v2.4.3 ?

**Comment by tpeacock19** [comment]
I get the same error when using the latest release.

@MartenBE If you want a workaround and you systemd you can use the below with just the cli. It does require you have `screen` on your system:

```bash
#!/usr/bin/env bash

case "$1" in
start)
    # will create an screen in detached mode (background) with name "protonmail"
    screen -S protonmail -dm {path-to-}/proton-bridge --cli
    echo "Service started."
    ;;
status)
    # ignore this block unless you understand how screen works and that only lists the current user's screens
    result=$(screen -list | grep protonmail)
    if [ $? == 0 ]; then
        echo "Protonmail bridge service is ON."
        exit 0
    else
        echo "Protonmail bridge service is OFF."
        exit 1
    fi
    ;;
stop)
    # Will quit a screen called "protonmail" and therefore terminate the running protonmail-bridge process
    screen -S protonmail -X quit
    echo "Service stopped."
    ;;
*)
    echo "Unknown command: $1"
    exit 1
    ;;
esac
```


```
#protonmail-bridge.service
[Unit]
Description=Service to run the Protonmail bridge client
After=network.target

[Service]
Type=oneshot
ExecStart=/home/morpheus/.local/bin/protonmail.sh start
ExecStop=/home/morpheus/.local/bin/protonmail.sh stop
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
```

```systemctl --user enable --now protonmail-bridge.service```

**Comment by andrzejsza** [comment]
@tpeacock19 could you contact bridge@protonmail.com and send us your logs? we still can't repro this issue, and in 2.4.3 we've done a few potential fixes, mainly extending some timeouts, ensuring gRPC has no issues with selecting a port and enabling gRPC to generate its own TLS certificate. If not of that helped, we're not sure what can, so some more detailed investigation would be useful.

**Comment by tpeacock19** [comment]
I've just sent some logs over now.

**Comment by MartenBE** [comment]
2.4.0 prerelease didn't work, but I've just tried the 2.4.8 prerelease and it seems to be fixed :)

**Comment by jasperges** [comment]
For me pre-release 2.4.5 already fixed the problem.

**Comment by andrzejsza** [comment]
thanks for confirming 👌
