### ISSUE TITLE
[Flatpak] Proton Mail Bridge not showing up in the notification area

### ISSUE THREAD

**Issue by telometto** [ProtonMail/proton-bridge#300]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

The Proton Mail Bridge icon isn't visible in the status bar/notification area.
Fedora 36 with GNOME 42.4

## Expected Behavior

It used to show up in the notification area, so the expected behaviour would be that it shows up there.

## Current Behavior

The program runs normally. If you press 'x' to close the window in the top-right corner, it continues to run in the background.

## Possible Solution

It'd be nice to have the program show up in the notification area, instead of having to kill it using `flatpak kill`.
Another nice-to-have would be the possibility to exit the program from *within* the program's main window.

## Steps to Reproduce

1. Open the GNOME menu (akin to the Windows 'Start' equivalent).
2. Open the program 'Proton Mail Bridge'.

## Version Information

2.3.0

## Context (Environment)

As mentioned further up, it is kinda annoying having to manually kill the program using the CLI.

**Comment by ErikReider** [comment]
Here's a quick fix: https://github.com/flathub/ch.protonmail.protonmail-bridge/issues/93#issuecomment-1298608685

**Comment by LBeernaertProton** [comment]
Hey @telometto we do not maintain the flatpak package. Please contact the owner of the link mentioned by @ErikReider .
