### ISSUE TITLE
Verification of debian package on debian bookworm fails

### ISSUE THREAD

**Issue by pegenaran** [ProtonMail/proton-bridge#301]
This is similar to a failed verification on bullseye from last year:
The verification of the Debian package on Debian Bookworm fails. Specifically, after following the steps outlined at
https://protonmail.com/support/knowledge-base/verifying-bridge-package/
When I run the debsig-verify protonmail-bridge_xxxx.deb command, it returns:
debsig: Failed verification for protonmail-bridge_2.3.0-1_amd64.deb

**Comment by andrzejsza** [comment]
tested with 2.4.5 and works as expected now. thanks for the report.
