### ISSUE TITLE
qt.conf not found

### ISSUE THREAD

**Issue by doggodanubus** [ProtonMail/proton-bridge#302]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

make build squalls about a missing /bin/qt.conf on Fedora 36, qt5 and qt6 development packages are installed. 

## Expected Behavior

It should just build
## Current Behavior

make build squalls about a missing /bin/qt.conf on Fedora 36, qt5 and qt6 development packages are installed.

## Possible Solution

I eviscerated the check  for qt.conf and it tries to compile but gives a 503 error on another package download.

+ /usr/src/proton-bridge/internal/../extern/vcpkg/bootstrap-vcpkg.sh -disableMetrics
Downloading vcpkg-glibc...
curl: (22) The requested URL returned error: 503
curl: (22) The requested URL returned error: 503
curl: (22) The requested URL returned error: 503
curl: (22) The requested URL returned error: 503
+ check_exit 'Failed to bootstrap vcpkg.'

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

Compile proton-bridge myself

**Comment by andrzejsza** [comment]
Thanks for pointing this out. Currently, the build system relies on the definition of a QT6DIR environment variable to determine the location of the Qt 6 install directory (hence the check for the presence of a qt.conf). It doesn't need to. We can just have the requirement of having qmake in the PATH environment variable. We'll do that shortly and also update BUILD.md docs. Will keep you posted once done.

**Comment by andrzejsza** [comment]
fixed with 2.4.5 beta.
