### ISSUE TITLE
Sporadically seeing emails in inbox (web + mobile) that don't show up in clients through Bridge

### ISSUE THREAD

**Issue by sj** [ProtonMail/proton-bridge#303]
## Expected Behavior

When an email exists in my inbox and is visible on native Proton clients like mobile and web, it should also be visible/accessible through email clients that connect through Bridge

## Current Behavior

I sporadically notice emails that show up in my inbox on web+mobile, but not in Thunderbird (which is connected through Bridge).

## Possible Solution

Haven't found one yet. But this issue might be related to https://github.com/ProtonMail/proton-bridge/issues/220 (not sure how to test this)

## Steps to Reproduce

Haven't found a reliable way to reproduce his. However, I do know of at least one message that's currently at the top of my inbox that is not showing up in Thunderbird. I'll leave it there in case you have further instructions on how to help debug this.

Notably, this also seems to cause an off-by-one error in clients: if I mark that particular email as starred on mobile, then a different email appears as starred in Thunderbird! 

## Version Information

Bridge 2.4.0 on Ubuntu 22.10 beta

**Comment by cenouro** [comment]
I had the same problem yesterday: some messages were missing from Inbox in Thunderbird (although they were present in the All Mail folder).

Interestingly, deleting and then undeleting the messages using the web client made Thunderbird show them properly.

> I'll leave it there in case you have further instructions on how to help debug this

Could you try disabling the cache in Bridge? If that doesn't work, then maybe try applying a label to the message using the web client. This should at least give a starting point for the devs.

**Comment by andrzejsza** [comment]
not much dev work to do here.
1) can you check the v3 beta? potentially related to instability of message UIDs
2) please contact the support - we would be keen to log at the logs, if possible
