### ISSUE TITLE
duplicates filtered out

### ISSUE THREAD

**Issue by linuxlurak** [ProtonMail/proton-bridge#304]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

## Expected Behavior

I want to send duplicate mail (eg. for testing). 
## Current Behavior

Duplicated mails were filtered out and bridge logs this event with "Message was already sent".
## Possible Solution

Please add an option in protonbridge to disable duplicate filtering. If you want to send duplicates, this should be possible (especially for a paid mailing service).
## Steps to Reproduce

1. Use a form on your wesite and send a test mail.
2. Resend same form and check your logs: you will see a "Message was already sent" notification meaning your mail was filtered.

## Version Information

ProtonMail Bridge version 2.1.3
running bridge as a systemd service:
```
[Unit]
Description=Protonmail client bridge service
[Service]
Type=simple
#StandardOutput=journal
StandardOutput=file:/var/log/protonmailbridge
ExecStart=/usr/bin/protonmail-bridge --noninteractive -l debug
User=##CUTOUT###
[Install]
WantedBy=default.target
```
## Context (Environment)

`Linux 5.15.39-4-pve #1 SMP PVE 5.15.39-4 (Mon, 08 Aug 2022 15:11:15 +0200) x86_64 x86_64 x86_64 GNU/Linux`

## Detailed Description

Add a argument to protonbride like "--no-duplicate-filtering".

**Comment by andrzejsza** [comment]
what other use cases are there for sending duplicates apart from testing? and what are you testing?

**Comment by ericLemanissier** [comment]
This is probably the same problem as https://github.com/ProtonMail/proton-bridge/issues/161
My use case is a scanner which sends documents as separate emails, with the same subject

**Comment by andrzejsza** [comment]
The whole idea behind the sendrecorder was to ensure that the same message is not being send twice, and we wanted to have an extra check for this.
I can see how this might not work for some.
Closing as indeed duplicated by https://github.com/ProtonMail/proton-bridge/issues/161. We'll be looking into this.
