### ISSUE TITLE
Timeout to access DBusHelper when using pass

### ISSUE THREAD

**Issue by Moult** [ProtonMail/proton-bridge#305]
When I run proton-mail-bridge v2.3.0 on Gentoo Linux I get this:

```
$ proton-mail-bridge

WARN[0010] Failed to add test credentials to keychain    error="timed out after 10s" helper="*keychain.SecretServiceDBusHelper"
WARN[0035] Failed to add test credentials to keychain    error="Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached" helper="*secretservice.Secretservice"
WARN[0060] Failed to get test credentials from keychain  error="exit status 2: gpg: decryption failed: No secret key\n" helper="*pass.Pass"
ERRO[Oct 25 12:55:56.123] Could not list credentials                    error="no keychain" pkg=credentials
ERRO[Oct 25 12:55:56.123] Could not load all users from credentials store  error="no keychain" pkg=users
```

I have pinentry-1.2.1-r1 installed. /etc/init.d/dbus status is started. I have libsecret installed. I have gnome-keyring installed. My GPG key has a passphrase.

I've read https://www.reddit.com/r/ProtonMail/comments/gi64ek/protonmailbridge_on_linux_cant_detect_pass/ - my dbus is compiled with X support on Gentoo. I've tried running `gnome-keyring-daemon`

**Comment by Moult** [comment]
I recently discovered that this problem only occurs when using my regular user. If I `su -` to root and run proton-mail-bridge it all works as intended (i.e. I get a gnome-keyring popup instantly, I can sign in to my account, etc).

**Comment by LBeernaertProton** [comment]
Can you check again with v3.1?

**Comment by LBeernaertProton** [comment]
Closed due to lack of activity.

**Comment by Moult** [comment]
The bug still exists with 3.1.
