### ISSUE TITLE
Notification emails for new mails not available for non private users

### ISSUE THREAD

**Issue by linuxlurak** [ProtonMail/proton-bridge#307]
## Expected Behavior

Notification mails for new mails should be available for non private users too. The notification feature is described here: https://proton.me/support/notification-email
Only private users have a recovery mail address and only this recovery mail address is used for the notification mails.
(This description needs clarification as it's not obvious that the daily notification for new mails is restricted to private users).
## Current Behavior

Non private users lack the possibility to receive daily notification mails.
## Possible Solution

Add a general option for daily notification mails and do not depend this functionality on an existing recovery mail address.
## Steps to Reproduce

1. Try to follow this tutorial: https://proton.me/support/notification-email
2. You will notice there is no daily notification mail option if you are a non private user.

## Version Information

WebUI of protonmail.com
## Context (Environment)

Not dependent on a browser or an OS.

**Comment by bartbutler** [comment]
We are aware of it and it is a bug, will fix. Not relevant to bridge specifically so closing here.
