### ISSUE TITLE
Support for IMAP OR/NOT queries

### ISSUE THREAD

**Issue by BlackLight** [ProtonMail/proton-bridge#308]
The bridge doesn't currently support IMAP OR and NOT queries.

This impacts K-9 on Android, but probably other clients as well, since loading a mailbox fails on the bridge with an `unsupported search query` error.

I have [implemented a workaround](https://github.com/BlackLight/proton-bridge/commit/a9abe130636f1a1b9887f1f985f8e0d52ff25dda) on my fork that simply ignores `not` queries, and for now that seems to work, but this looks like a gap between the IMAP specification and the Proton bridge implementation.

## Expected Behavior

Messages are loaded on the client side without errors.

## Current Behavior

K-9 on Android (but probably other clients too) doesn't load mailboxes, and the server shows an `unsupported search query` error.

## Possible Solution

Merge my commit if it's "good enough" (if e.g. K-9 is the only known major client that performs these queries, and the workaround of simply ignoring them works), or properly implement OR/NOT logic in `internal/imap/mailbox_messages.go`.

## Version Information

It impacts all versions.

**Comment by andrzejsza** [comment]
hey, thanks for this. OR/NOT will be supported in the upcoming V3, as has been already included in the new IMAP library that we're switching to: https://github.com/ProtonMail/gluon

**Comment by BlackLight** [comment]
Thanks! Since this is one among several other issues related to the current IMAP implementation (the other major one is related to the unreliable handling of message UIDs), I'd be really interested in upgrading.

Is there a timeline for V3? Or is it already in a state where it can be beta-tested without message losses?

**Comment by andrzejsza** [comment]
@BlackLight can you check the recent beta? now is the time ;-)

**Comment by BlackLight** [comment]
@andrzejsza I've just tested the `v3` branch and it seems to indeed fix a lot of the IMAP issues (including both OR/NOT queries and out-of-order messages because of messed up message IDs), thanks!

It did however introduce a regression - namely, the default sort has apparently change (from date descending to date ascending), resulting in older messages displayed at the top, and I haven't found a way to change it via configuration. I'll take a look at the source code to see what changed and either open a new PR for it or a new issue.
