### ISSUE TITLE
PHP_IMAP

### ISSUE THREAD

**Issue by DunklerPhoenix** [ProtonMail/proton-bridge#310]
I try to get protonmail bridge to work with php_imap, but its not possible to connect to the bridge

## Expected Behavior
I can get the emails from the bridge

## Current Behavior
php_imap can't connect

## Steps to Reproduce
1. setup this php script (from php.net) on a server
```
<?php
function imapConfig($options, $i=0, $till = array()) {
        if(sizeof($options)==$i)
            return $till;

        if(sizeof($till)==0)
            $till[] = '';

        $opt = $options[$i];
        $new = array();
        foreach($till as $t) {
            foreach($opt as $o) {
                if(strlen($o)==0)
                    $new[] = $t;
                else
                    $new[] = $t.'/'.$o;
            }
        }
        return imapConfig($options, $i+1, $new);
    }

function imap_test($server, $port, $dir, $username, $passw) {
        $options = array();
        //$options[] = array('debug');
        $options[] = array('imap', 'imap2', 'imap2bis', 'imap4', 'imap4rev1', 'pop3'); //nntp
        $options[] = array('', 'norsh');
        $options[] = array('', 'ssl');
        $options[] = array('', 'validate-cert', 'novalidate-cert');
        $options[] = array('', 'tls', 'notls');

        $configOptions = imapConfig($options);
        foreach($configOptions as $c) {
            $mbox = @imap_open("{".$server.":".$port.$c."}".$dir, $username, $passw);
            echo "<b>{".$server.":".$port.$c."}".$dir."</b> ... ";
            if (false !== $mbox) {
                echo '<span style="color: green"> success</span>';
            }
            else {
                echo '<span style="color: red"> failed</span>';
            }
            echo '<br>';
        }
    }

imap_test('127.0.0.1', 1143, 'INBOX', 'mail@XXXX', 'PASSWORD');
```
2. See that every possible combination fails

## Version Information
/usr/lib/protonmail/bridge/proton-bridge-launcher]" build="2022-08-31T15:11:10+0000" revision=b5321f8993 runtime=linux version=2.3.0

## Context (Environment)
PHP8.1 on Debian

## Detailed Description
The Protonbridge shows errors like "peer closed connection" or "first message doesn't look like TLS, can't upgrade"

## Possible solution
Make IMAP SSL or plain possible

**Comment by LBeernaertProton** [comment]
Hey @DunklerPhoenix you need to change the connection mode for IMAP to `SSL` in the Bridge for this work correctly. By default it is set to `STARTTLS`.

Alternatively you can try to setup your IMAP client library to use `STARTTLS` instead of `SSL`.

**Comment by LBeernaertProton** [comment]
My mistake, I didn't notice this was for v2. This option exists in the v3.0.x beta releases. 

I would suggest you either try with one of those or you change your IMAP client to use `STARTTLS` instead of `SSL`.

**Comment by gabor-meszaros** [comment]
Not much activity on this issue, I am closing it. If you encounter a problem with an email client setup, please feel free to reach out to our customer support. Thank you!
