### ISSUE TITLE
Protonmail Bridge 2.4.8 fails to launch on Linux Mint 19.3 due to newer required glibc version

### ISSUE THREAD

**Issue by jangxx** [ProtonMail/proton-bridge#312]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

## Expected Behavior
The bridge starts.

## Current Behavior
The bridge fails to start with the following message in the terminal:
```
INFO[Nov 24 09:18:21.583] No more updates found, looking up bridge executable  error="no available newer versions" exe_to_launch=bridge-gui launcher_path=/usr/lib/protonmail/bridge/proton-bridge launcher_version=2.4.8
/usr/lib/protonmail/bridge/bridge-gui: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/protonmail/bridge/bridge-gui)
/usr/lib/protonmail/bridge/bridge-gui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/protonmail/bridge/lib/libQt6Core.so.6)
FATA[Nov 24 09:18:21.585] Failed to launch                              error="exit status 1" exe_path=/usr/lib/protonmail/bridge/bridge-gui exe_to_launch=bridge-gui launcher_path=/usr/lib/protonmail/bridge/proton-bridge launcher_version=2.4.8
```

## Possible Solution
Version 2.3.0 worked without issues but it seems like a recent update has raised the required glibc version.
Unfortunately it's downright impossible to update glibc without breaking the entire system, so a solution for this would be to downgrade the internal requirements to an older version which doesn't require this new version of glibc (I'm suspecting Node 18 might be the culprit here. Node 16 still works fine)

## Steps to Reproduce

1. Enter `protonmail-bridge` in the terminal.

## Version Information
`2.4.8` while `2.3.0` still worked.

## Detailed Description
I haven't looked at the code of the bride yet, but I'm guessing this is related to the bridge using Electron (i.e. Node) and this issue: https://github.com/nodejs/node/issues/42351
The only fix seems to be to downgrade to Node 16, which I would appreciate. Linux Mint 19 is still within the LTS lifespan, same as Ubuntu 20, so it should still be supported by software such as this imo.

**Comment by gabor-meszaros** [comment]
Hi @jangxx, Thank you for reporting this. Bridge doesn't use Electron or Node, the GLIBC dependency comes from Qt 6. I am not familiar with Linux Mint 19, but it can be that it comes with an older GLIBC and that it is difficult to upgrade. Unfortunately, we cannot prioritize supporting older GLIBC. In case you cannot update to a newer version of Linux Mint, you can try to recompile Qt 6, and then to compile Bridge with that Qt 6.

**Comment by dngray** [comment]
I had this when using a PM docker container, rebasing on jammy fixed it for me https://github.com/shenxn/protonmail-bridge-docker/pull/71

**Comment by dngray** [comment]
> It may be possible to backport Qt6 to Ubuntu 18 and 20, but I would strongly encourage users to just upgrade to 22 rather than relying on older software.

I don't even know if that would be easy, and I would rather see PM spend resources on getting bridge v3 stable as opposed to trying to support some `insert ancient distribution`.

**Comment by jangxx** [comment]
@Ammako 

>It will reach end of life next April. Is there a reason why you can't upgrade?

The only reason I haven't upgraded is because I haven't found the time yet. I will definitely do it before April though.

>Third-party app publishers aren't (and shouldn't be) beholden to this.

I'm aware of this, I only wrote that because I think that software dealing with encryption and other security critical stuff should be at least somewhat backwards compatible so that people who can't upgrade their OS every year are not suddenly forced to run insecure software. Of course using the LTS cycle is completely arbitrary, I merely used it to point out the fact that the OS is not really all that old (Linux Mint 19.3 came out in December 2019) and still officially supported even.
