### ISSUE TITLE
Not possible to launch noninteractive cli mode anymore in 2.4.8

### ISSUE THREAD

**Issue by jmontleon** [ProtonMail/proton-bridge#313]
Running `protonmail-bridge --noninteractive` wants to launch bridge-gui no matter what.

If I specify `--noninteractive` and `--cli` it seems it refuses to launch non-interactively

## Expected Behavior
Run noninteractive cli when no gui is available. This was possible before 2.4.8.

## Current Behavior
```
FATA[Nov 24 10:35:36.799] Failed to launch                              error="exit status 127" exe_path=/usr/lib/protonmail/bridge/bridge-gui exe_to_launch=bridge-gui launcher_path=/usr/lib/protonmail/bridge/proton-bridge launcher_version=2.4.8
```

## Steps to Reproduce
1. Update to 2.4.8
2. Try to run non-interactively in a cli only environment
3. It always tries to run bridge-gui

## Version Information
2.4.8

Probably https://github.com/ProtonMail/proton-bridge/commit/b1eefd6c8561f0aed99e9bb3adbed204c680976a

You default to bridge-gui unless explicitly asking for cli now and with it impossible to use noninteractive and cli together (I don't think it's ever been possible) it just falls over.

https://github.com/ProtonMail/proton-bridge/commit/b1eefd6c8561f0aed99e9bb3adbed204c680976a#diff-621f76db694d94390921f84a5f98a9560ac41d5448a2d886671baf1e051a9abeR112

Copying bridge over bridge-gui allows it to work as desired, but that's kind of a gross woraround.

**Comment by gabor-meszaros** [comment]
Hi @jmontleon, Thank you for reporting this issue. It is indeed a bug that we have just recorded in our internal issue tracker (GODT-2154). Unfortunately, there is no clean workaround for this problem other than bypassing the launcher and launching bridge directly. E.g.
- CLI: `/usr/lib/protonmail/bridge/bridge -c`
- Non-interactive: `/usr/lib/protonmail/bridge/bridge -n`

That works only if you installed 2.4.8 directly there, if you installed it via an update, you need to launch it from the update folder (`$usercache/protonmail/bridge/update` where `$usercache` is `$HOME/.cache` or `$XDG_CACHE_HOME/.cache` if the `XDG_CACHE_HOME` environment variable is set)

**Comment by jmontleon** [comment]
@gabor-meszaros thank you for the quick response and explaining how to launch bridge directly. Launching it the way you described should work for me.

**Comment by jmontleon** [comment]
Cool! I'll go ahead and close this. FWIW we should hopefully be back to the stock Fedora kernel by 6.10 or 6.11. The PR to fix audio is in the stable-queue upstream. 

https://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git/tree/queue-6.0/asoc-rt5514-fix-legacy-dai-naming.patch

This is the only kernel PR I've ever submitted so I'm not well versed on what the entire process looks like, but it's getting there.
