### ISSUE TITLE
Compiling for ARM64 Raspberry Pi

### ISSUE THREAD

**Issue by superteece** [ProtonMail/proton-bridge#314]
My knowledge of compiling from source is limited to the `./configure`. `make`, `sudo make install` types of projects. As I understand there is not a .deb for ARM64 I thought last night, "I'll just grab the ARM64 versions of the toolchain and dependencies and that'll work" but it doesn't seem to be the case.

Am I barking up a non-existent tree? Is building non-GUI for use on an ARM64 Raspberry Pi just not possible at the moment?

**Comment by gabor-meszaros** [comment]
Hi @superteece, We have never tried to build Bridge (especially the newer versions) for Raspberry Pi. In theory, building the non-gui part should not be impossible, but it might not be straightforward. You can start with `make run-noninteractive`, and continue from there.

**Comment by LBeernaertProton** [comment]
You would also need to ensure that the dependent libraries (https://github.com/ProtonMail/gluon) also have their native counter parts built on ARM64.

**Comment by superteece** [comment]
Thank you both. I'll look into these this weekend.
