### ISSUE TITLE
Add --export-tls argument to export certs to disk

### ISSUE THREAD

**Issue by dngray** [ProtonMail/proton-bridge#315]
No client certificates written to disk in v3

## Expected Behavior
Version 2.x of the bridge printed a the certificate out to `.config/protonmail/bridge/cert.pem` which was useful for commandline clients like `mbsync` etc.

## Current Behavior
With v3 no such certificate is in the `.config/protonmail/bridge-v3` directory.

## Possible Solution
Could either patch, to print the certificate, or provide a CLI option to print it.

## Steps to Reproduce
N/A

## Version Information
3.0.4

## Context (Environment)
Using docker container [shenxn/protonmail-bridge-docker](https://github.com/shenxn/protonmail-bridge-docker) because this is most suitable for my needs.

On a side note there, it would be good if Proton had an official Docker container.

## Detailed Description
Being able to copy the `cert.pem` was rather useful, as it would fix verification issues.

A workaround that I used was to enable TLS (not STARTTLS) ie, `change imap-security` and get the certificate to be printed with `openssl s_client -connect 127.0.0.1:1143`

## Possible Implementation

Alternatively, if there's some reason that you don't want to print client certificates out to a file anymore, then maybe an option in the CLI to do it.

**Comment by gabor-meszaros** [comment]
Hi @dngray, Thanks for reporting this issue. We are aware of this limitation of the current alpha V3 (internal reference: GODT-1847), and we will work on a solution very soon. Please stay tuned.

**Comment by jameshoulahan** [comment]
This option already exists in the v3 shell:

```bash
$ ./proton-bridge -c
INFO[0000] Migrating keychain helper

            Welcome to Proton Mail Bridge interactive shell
                              ___....___
    ^^                __..-:'':__:..:__:'':-..__
                  _.-:__:.-:'':  :  :  :'':-.:__:-._
                .':.-:  :  :  :  :  :  :  :  :  :._:'.
             _ :.':  :  :  :  :  :  :  :  :  :  :  :'.: _
            [ ]:  :  :  :  :  :  :  :  :  :  :  :  :  :[ ]
            [ ]:  :  :  :  :  :  :  :  :  :  :  :  :  :[ ]
   :::::::::[ ]:__:__:__:__:__:__:__:__:__:__:__:__:__:[ ]:::::::::::
   !!!!!!!!![ ]!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!![ ]!!!!!!!!!!!
   ^^^^^^^^^[ ]^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[ ]^^^^^^^^^^^
            [ ]                                        [ ]
            [ ]                                        [ ]
      jgs   [ ]                                        [ ]
    ~~^_~^~/   \~^-~^~ _~^-~_^~-^~_^~~-^~_~^~-~_~-^~_^/   \~^ ~~_ ^
>>> export-tls
Enter a path to which to export the TLS certificate used for IMAP and SMTP: /home/james/certs
TLS certificate exported to /home/james/certs
```

As @gabor-meszaros said, the corresponding option in the GUI will be added soon (it's been merged, just needs to be released).

But you make a good point -- this would make for a nice CLI flag, for exporting without requiring user interaction. I'll open a ticket internally.

**Comment by dngray** [comment]
> But you make a good point -- this would make for a nice CLI flag, for exporting without requiring user interaction. I've opened a ticket internally (GODT-2186)

Sounds, good, we could then integrate that with the docker container, has there been any thought about an official docker container?

This allows for better testing, particularly when building from master.

**Comment by dsommers** [comment]
> Thoughts, definitely, but the product itself has our highest priority right now and for the immediate future.

flatpak and snap would be easier for most desktop users to install and run, though.

**Comment by andrzejsza** [comment]
it's been added to the GUI and available in both beta/prod. closing.
