### ISSUE TITLE
[v3] Folders and labels containing non-US ASCII chars misbehaves

### ISSUE THREAD

**Issue by dsommers** [ProtonMail/proton-bridge#318]
In my Proton Mail account I have several folders and labels containing non-US ASCII characters (ö,ü,ä,ë,æ,ø,å).  These folders and labels are empty/inaccessible from Thunderbird (102.5.1).

When entering the "subscription" menu (Right click on "Account line" above "Inbox", select "Subscriptions") these folders are listed twice.  The first one is not subscribed to while the second one is subscribed to.

I'm testing a non-gui build of v3.0.6 (commit f070314524aac277150c) on RHEL 8.7.

**Comment by LBeernaertProton** [comment]
Hey @dsommers , thanks for reporting the issue. I have managed to reproduce it locally.

**Comment by LBeernaertProton** [comment]
A fix for this issue will be released in 3.0.7.

**Comment by dsommers** [comment]
Please, @LBeernaertProton, can you push out your development work so we can test that and give an early feedback?  This bug is actually making my daily work harder; I'm willing (and capable) to build the non-gui version from git.

**Comment by jameshoulahan** [comment]
Hey @dsommers, i've updated the `v3` branch to match our internal development branch. Please give that one a shot :)

**Comment by dsommers** [comment]
@jameshoulahan Thanks a lot!  This issue is solved by commit ebb04d8a143281e9ce6f1a898f65a03f02b63333.

An less pleasant surprise was that I needed to re-subscribe to almost all mail folders; but I'm happy all my folders are now accessible.

**Comment by dngray** [comment]
Can also confirm this is fixed.

**Comment by LBeernaertProton** [comment]
@dsommers The current v3 code includes a commit that is related to separate feature that was not yet completed, which cause the unsubscribed mailboxes. A revert will be published to the v3 branch as soon as possible.

The issue will be closed as it has been confirmed fixed.
