### ISSUE TITLE
Problems creating (sub)folders

### ISSUE THREAD

**Issue by notDavid** [ProtonMail/proton-bridge#331]
**Example 1**:
1. Open Thunderbird (latest stable version)
2. Right click `Folders` > `New Subfolder` > `test`
3. Nothing happens
4. Folder also does not exist in the proton webclient
5. It seems Proton Bridge crashed or something as you will now get a timeout to the server at 127.0.0.1.
6. Restart Proton Bridge and Thunderbird

**Example 2**:
1. Go to the webclient and create a folder `test230111`
2. In Thunderbird, go to the `test230111` folder and create a subfolder named `testsub`
3. The created subfolder does not appear in Thunderbird
4. In the webclient, i now see a new folder called `test230111/testsub` (instead of a subfolder.) So i now have 2 folders in the root: `test230111` and `test230111/testsub` In Thunderbird i see something weird, see screenshot.
5. The Proton bridge app seems to have crashed again.

I can go on like this forever... creating folders is very buggy!

## Version Information

Using latest stable versions of everything:
Proton Mail Bridge v2.3.0
Thunderbird 102.6.1
macOS Ventura 13.1

Example 2, Thunderbird:
![Thunderbird](https://user-images.githubusercontent.com/1530401/211771908-f06bd740-8528-4f73-a886-9a470ce1477d.png)

Example 2, Webclient:
![Webclient](https://user-images.githubusercontent.com/1530401/211771973-90fef21b-cf07-4b5e-84cf-f9621bf76da3.png)

**Comment by LeehamElectronics** [comment]
> Another bug: simply creating any subfolder via the webclient, stops the Bridge from functioning, and requires restarting the Bridge (and E-mail client.)
> 
> ![Screenshot 2023-01-11 at 13 13 34](https://user-images.githubusercontent.com/1530401/211803885-777e43cf-eb22-49c1-8227-145c299652e3.png)

Do you have logs for this?

**Comment by jameshoulahan** [comment]
Hi @notDavid, thanks for the feedback. Yes, Bridge v2.3.0 has limited subfolder support; for full subfolder support, you'll need to use Bridge v3, which is currently in beta. You can do that by enabling early access in the bridge's settings.

**Comment by gabor-meszaros** [comment]
Hi @notDavid, Thank you for reporting the issue and sorry for the inconvenience. We believe that this issue has been fixed in the current beta. I understand that you do not want to use beta version in a production environment. I will let this issue open until we release Bridge v3 to production, and then you can verify the fix.

**Comment by LBeernaertProton** [comment]
Fix has been released in v3.0.21
