### ISSUE TITLE
3.0.12: `constraint failed: UNIQUE constraint failed: mailboxes.name`

### ISSUE THREAD

**Issue by erri120** [ProtonMail/proton-bridge#337]
```log
time="Feb  2 11:34:20.947" level=info msg="Beginning user sync" start="2023-02-02 11:34:20.9472827 +0100 CET m=+401.959924401" userID="REDACTED"
time="Feb  2 11:34:20.953" level=info msg="Syncing labels" userID="REDACTED"
time="Feb  2 11:34:20.954" level=error msg="Failed to apply update: ent: constraint failed: UNIQUE constraint failed: mailboxes.name" error="ent: constraint failed: UNIQUE constraint failed: mailboxes.name"
time="Feb  2 11:34:20.954" level=warning msg="Failed to sync user" error="failed to sync labels: failed to apply label create update in gluon MailboxCreated: Mailbox.ID = bf315331-527..., Mailbox.Name = Folders: ent: constraint failed: UNIQUE constraint failed: mailboxes.name" userID="REDACTED"
time="Feb  2 11:34:20.955" level=error msg="Failed to sync, will retry later" error="failed to sync: failed to sync labels: failed to apply label create update in gluon MailboxCreated: Mailbox.ID = bf315331-527..., Mailbox.Name = Folders: ent: constraint failed: UNIQUE constraint failed: mailboxes.name" userID="REDACTED"
time="Feb  2 11:34:20.954" level=error msg="Failed to apply update: ent: constraint failed: UNIQUE constraint failed: mailboxes.name" error="ent: constraint failed: UNIQUE constraint failed: mailboxes.name"
time="Feb  2 11:34:20.955" level=error msg="Failed to apply update: ent: constraint failed: UNIQUE constraint failed: mailboxes.name" error="ent: constraint failed: UNIQUE constraint failed: mailboxes.name"
time="Feb  2 11:34:20.955" level=error msg="Failed to apply update: ent: constraint failed: UNIQUE constraint failed: mailboxes.name" error="ent: constraint failed: UNIQUE constraint failed: mailboxes.name"
time="Feb  2 11:34:20.955" level=error msg="Failed to apply update: ent: constraint failed: UNIQUE constraint failed: mailboxes.name" error="ent: constraint failed: UNIQUE constraint failed: mailboxes.name"
time="Feb  2 11:34:20.955" level=error msg="Failed to apply update: ent: constraint failed: UNIQUE constraint failed: mailboxes.name" error="ent: constraint failed: UNIQUE constraint failed: mailboxes.name"
```

Latest preview is stuck in a synchronization loop. This issue is new in 3.0.12 and makes the app unusable. I initially thought https://github.com/ProtonMail/gluon/commit/90330fd766f847afcfbfdcb2e795c3b67a8cb51a was related to this, so I cleaned the database files, but the problem still persisted. PR https://github.com/ProtonMail/gluon/pull/267 might still be related.

**Comment by LBeernaertProton** [comment]
Hey @erri120 , the changes you mentioned from gluon are not part of the Bridge v3.0.12 release.

With 3.0.12 we also changed the default location of the database. If you cleaned them by hand, depending on your operating system, it might be possible that you removed the old database file.

I would recommend you delete the account via Bridge so that all the correct files get removed and try to log in again. 

If the issue still persists, please let us know.

**Comment by mvanhNL** [comment]
Same problem here, no manual delete or cleanup was done. 
time="Feb  3 09:24:40.851" level=error msg="Failed to apply update: ent: constraint failed: UNIQUE constraint failed: mailboxes.name" error="ent: constraint failed: UNIQUE constraint failed: mailboxes.name"

I also noticed this message:

time="Feb  3 09:26:40.983" level=error msg="Failed to sync, will retry later" error="failed to sync: failed to sync labels: failed to apply label create update in gluon MailboxCreated: Mailbox.ID = 39508b56-115..., Mailbox.Name = Folders: ent: constraint failed: UNIQUE constraint failed: mailboxes.name" userID=

**Comment by LBeernaertProton** [comment]
Hey @mvanhNL. Could you remove your account and log in again in Bridge. That should solve the issue.

**Comment by erri120** [comment]
Removing the account and logging back in fixes the issue.
