### ISSUE TITLE
KDE Wallet support

### ISSUE THREAD

**Issue by gudvinr** [ProtonMail/proton-bridge#34]
Currently proton-bridge requires gnome-keyring to run on desktop. Which is very inconvenient to use in KDE since it already has a system to store credentials (which e.g. used by chrome).

Here's [API reference](https://api.kde.org/frameworks/kwallet/html/index.html) of kwallet.

And here's [KDE Wallet Manager](https://userbase.kde.org/KDE_Wallet_Manager) wiki page.

**Comment by jameshoulahan** [comment]
If you don't wish to use `gnome-keyring`, we also support using `pass`. However, I do agree that it would be good if we supported a wider range of keyring software.

As this is already covered by the more general issue #14, I will close this as a duplicate.
