### ISSUE TITLE
"...logged out because of an internal error"

### ISSUE THREAD

**Issue by EpicTMC** [ProtonMail/proton-bridge#342]
Since the last update i keep getting this error:
![image](https://user-images.githubusercontent.com/16276082/218708651-c6d0c9a6-c7a1-425a-a5fb-5a61aea1eb68.png)

i can log in and do 2fa, everything looks ok, macmail app then prompts for the password, copy/paste from bridge dashboard, then the error shows up and takes me back to the login part of the bridge.

Macmini 2018
3.2 GHz 6-Core Intel Core i7
64 GB 2667 MHz DDR4
Macos Ventura 13.2 (22D49)

**Comment by gabor-meszaros** [comment]
Hi @EpicTMC, Thank you for being interested in Bridge. I assume you joined beta, so you have 3.0.12 or 3.0.14 version. If that is the case, can you please remove and add your account again? That will recreate the DB and should solve this issue.

**Comment by EpicTMC** [comment]
> Hi @EpicTMC, Thank you for being interested in Bridge. I assume you joined beta, so you have 3.0.12 or 3.0.14 version. If that is the case, can you please remove and add your account again? That will recreate the DB and should solve this issue.

legend, thank you for the quick resolution.
