### ISSUE TITLE
Bridge GUI does not start and crashes in a Wayland session and NVIDIA hybrid setup

### ISSUE THREAD

**Issue by fthx** [ProtonMail/proton-bridge#344]
Hi,

_Ubuntu 22.04
Ubuntu Wayland session
Nvidia gpu, hybrid mode
Latest Nvidia proprietary driver from Ubuntu_

Bridge GUI does not start. Bridge autostart as a background task is ok.
After clicking on GUI app icon, Bridge seems to crash (nothing happens) and Thunderbird cannot connect anymore to localhost/bridge port.

I can see some similar bug on some apps that do mix up X and Wayland.
This bug does not happen in a pure dGPU setup or any X session.

**Comment by LBeernaertProton** [comment]
Hey @fthx this is probably related to Qt's GPU accelerated rendering, If you are experiencing issues, I would recommend trying to start bridge with the `--software-renderer` which, as the flag states, will use a software based renderer instead. 
Please let us know if that fixes it for you.

**Comment by fthx** [comment]
No!

**Comment by LBeernaertProton** [comment]
Could tell us which version of the bridge you are running?

**Comment by fthx** [comment]
3.0.16 updated from 2.4.8

**Comment by fthx** [comment]
just tried some qt qpa export options but no wazy

**Comment by LBeernaertProton** [comment]
Can you try with `QT_QPA_PLATFORM=xcb protonmail-bridge` ?

**Comment by fthx** [comment]
this one works!

**Comment by fthx** [comment]
I forgot to try the most evident one...

**Comment by LBeernaertProton** [comment]
Happy to hear the issue is solved for you.

**Comment by fthx** [comment]
Well, that's not what I expected, though.   :-)
Of course I can add this QT export in the launcher but I hoped a neat solution to be found. Since recently Nvidia drivers in Ubuntu 22.04 are natively Wayland compatible so my Ubuntu setup is not a hack.

**Comment by LBeernaertProton** [comment]
Unfortunately, this falls outside the scope of what we can address. 

We are using the official release binaries from Qt6 for our builds. If you would like to see this particular issue addressed, I would recommend opening a bug on their issue tracker.

**Comment by fthx** [comment]
OK!

**Comment by fthx** [comment]
Note that this issue does not exist using latest dev Ubuntu 23.04.
