### ISSUE TITLE
Upon start i get a gRPC server error

### ISSUE THREAD

**Issue by rottenpants466** [ProtonMail/proton-bridge#345]
Hi,

I recently performed a clean installation of Windows 11 and then i proceeded to install the latest version of Proton Bridge. The app doesn't open and it shows 2 similar errors.

## Expected Behavior
Proton Bridge should start normaly.

## Current Behavior
When starting the app it shows one of these errors depending on if i start with Administration Rights:

Cannot connectToServer to go backend via gRPC: Server failed to generate certificate on time.

or

Bridge application exited before providing a gRPC service configuration file.

## Possible Solution
I have no idea. Tried to reinstall Bridge again but i get the same error.

## Version Information
Windows 11 Pro 22H2 with latest updates
Proton Bridge v3.0.18

**Comment by gabor-meszaros** [comment]
Hi @rottenpants466, Thank you for reporting this issue. We do not have many gRPC related errors reported to us, so your logs would be very useful. Can you please contact Proton customer support and send your logs to us? You can use the built in report function, or just zip all the log files you have and report it through web. Thank you!

**Comment by gabor-meszaros** [comment]
On Windows, it should be under `%localappdata%\protonmail\bridge\logs` (`C:\Users\username\AppData\Local\protonmail\bridge\logs\`).

**Comment by gabor-meszaros** [comment]
@rottenpants466 I am sorry, I shared a wrong path before. Now I updated it to the correct one.

**Comment by rottenpants466** [comment]
Thank you!

**Comment by rottenpants466** [comment]
Don't know why but bridge creates 2 more users for some reason, is this normal?

<img width="913" alt="Captura de ecrã 2023-02-25 000016" src="https://user-images.githubusercontent.com/62076029/221323365-3b785d13-b44e-4177-8fe6-e0deefb9a3eb.png">

[v3.0.18_82c388a0dd_1677282985.log](https://github.com/ProtonMail/proton-bridge/files/10829844/v3.0.18_82c388a0dd_1677282985.log)

[v3.0.18_82c388a0dd_1677282984.log](https://github.com/ProtonMail/proton-bridge/files/10829845/v3.0.18_82c388a0dd_1677282984.log)

**Comment by rottenpants466** [comment]
Tried other v3 versions same thing happens.

**Comment by andrzejsza** [comment]
Thanks for this report - the extra users' folder is clearly a bug.
After investigation, it turned out that this is due to the path of the user home folder containing accents. Potentially, this is also the reason for the original problem, as bridge-gui would struggle to retrieve the user config, data, and cache folder. We should have a hotfix in the coming days, will post it here.

**Comment by rottenpants466** [comment]
Thank you!

Should i close this issue?

**Comment by andrzejsza** [comment]
let's wait for the fix to be out 👌

**Comment by Babak-mhy** [comment]
I've got the exact same issue!

**Comment by andrzejsza** [comment]
would you mind confirming with the current beta 3.0.19? might be best to first uninstall the current version completely and delete those weird looking user folders...

**Comment by rottenpants466** [comment]
I can report the problem was fixed in 3.0.19 beta 👍 

Proton Bridge starts up normaly and i was able to login. Also no more weird user folders 👍 

Thank you!

**Comment by andrzejsza** [comment]
glad to hear. closing.

**Comment by Zachiah** [comment]
I'm getting the 

> Bridge application exited before providing a gRPC service configuration file.

on MacOS ever since I setup Nix. Any idea why?

**Comment by LBeernaertProton** [comment]
We usually see this error if there is an issue interacting with the macOS keychain.

**Comment by Zachiah** [comment]
> We usually see this error if there is an issue interacting with the macOS keychain.

Thanks for your reply! Do you have any recommendations on first steps to debug this?
