### ISSUE TITLE
Proton Bridge doesn't automatically update folder changes made on Proton website

### ISSUE THREAD

**Issue by AwlsomeAlex** [ProtonMail/proton-bridge#351]
Updating folders on Proton website don't reflect on Proton Bridge client automatically.

## Expected Behavior
Modifying/creating a folder on Proton website should show changes in Thunderbird connected through Proton Bridge.

## Current Behavior
It doesn't. Need to restart both Thunderbird and Proton Bridge for it to take effect.
Trying to interact with a moved folder causes Thunderbird to throw a "Mailbox not found" error.

## Possible Solution
Restarting both applications solves issue, probably rebuilding mailboxes on the fly at startup?

## Steps to Reproduce
1. Create a new folder on Proton website
2. Make new folder a sub folder
3. Observe that changes don't reflect in Thunderbird
4. Restart Proton Bridge and Thunderbird client
5. Observe that changes are made

## Version Information
macOS 13.2.1 (Apple Silicon)
Proton Bridge 3.0.18
Thunderbird 110.0b4

**Comment by LBeernaertProton** [comment]
Hey @AwlsomeAlex unfortunately, this is a limitation of the IMAP protocol and the IMAP client in question. In version 4.1, which is what we support at the moment, there is no way to notify the client that the folders have changed. It is up to the clients to periodically refresh their folder list. 

Thunderbird, Outlook and Apple Mail are known to have this issue. If you restart the client you should see your updated folder/label list.

**Comment by AwlsomeAlex** [comment]
@LBeernaertProton Yup, that's what I'm seeing. Gets corrected when I restart my email client. Thanks!
