### ISSUE TITLE
Failed to migrate old accounts

### ISSUE THREAD

**Issue by skrivbar** [ProtonMail/proton-bridge#352]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

Failed to migrate old accounts from 2.3.0 block storing new account setup in 3.0.17

## Expected Behavior

Startup with account stored i prior session.

## Current Behavior

Startup with no account.

## Possible Solution

Delete old account setup to get out of this "deadlock".

## Steps to Reproduce

1. Use flatpak 2.3.0 on OpenSUSE 15.4
2. Upgrade to 3.0.17 from flatpak on OpenSUSE 15.4
3. Add new account in 3.0.17
4. Restart mail bridge and no account is present.

## Version Information

3.0.17

## Context (Environment)

Need to add account on every startup.

## Detailed Description

`ERRO[Feb 28 02:13:02.044] Failed to migrate old accounts                error="2 errors occurred:\n\t* failed to split api token for user \"...\": malformed API token\n\t* failed to split api token for user \"...\": malformed API token\n\n"
`
## Possible Implementation

Provide information on howto delete old account configuration. Have removed all in ~/.var/app/ch.protonmail.protonmail-bridge. What to delete to get rid of old account configuration.
If failing in upgrade, delete old account configuration.

**Comment by LBeernaertProton** [comment]
Hey @skrivbar , the flatpak version is not officially maintained by us. We can't assist with issues related to that setup.

Regarding the migration. With non-flatpak versions, it should be a seamless transition. If you are experiencing issues with the upgrade from v2 to v3 using non-flatpak binaries, please open another ticket.
