### ISSUE TITLE
App does not sync theme and cursor theme with desktop (Qt + Wayland bug)

### ISSUE THREAD

**Issue by mateitudose** [ProtonMail/proton-bridge#356]
## Expected Behavior
System configuration: Ubuntu 22.04 default config (Wayland is the default window manager)
The app should sync the color of the window border and of the cursor when hovering over the app with the theme of the desktop,

## Current Behavior
Window border color stays white even in dark mode and cursor theme changes when hovering over the app window.

## Possible Solution
Building the app with the latest version of Qt instead of 6.3.2.

## Steps to Reproduce
Simply open the app on Ubuntu 22.04
[Video sample showing the bug](https://user-images.githubusercontent.com/37705192/223155169-faab03bb-9e29-4f3c-be5a-570ea4133f1d.webm)

## Version Information
3.0.19

## Context (Environment)
The Proton Bridge app should integrate nicely with the most used distribution of Linux, given that Wayland is also the successor of Xorg

## Detailed Description
Make the app match the cursor theme and the window border color with the desktop

**Comment by mateitudose** [comment]
`QT_QPA_PLATFORM=xcb` doesn't help as I've found on some forums

**Comment by LBeernaertProton** [comment]
Hey @mateitudose, this seems to be a limitation of Qt. Unfortunately there is nothing we can do to assist. It may help to install https://github.com/FedoraQt/QGnomePlatform on your distro.
