### ISSUE TITLE
The way to run a golng GRPC client

### ISSUE THREAD

**Issue by forfcw** [ProtonMail/proton-bridge#362]
Question:
  Is there a way to start a golang GRPC client instead of QT?  Cpp  project is a little hard for me to integration the proton bridge service

Looking forward to your reply, tks.

**Comment by LBeernaertProton** [comment]
Hey @forfcw, in case you aren't aware you can run the bridge standalone with `bridge -c` or `bridge -n` argument.

You can use our dummy implementation we use for our tests as a reference.

https://github.com/ProtonMail/proton-bridge/blob/master/tests/ctx_bridge_test.go#L248
