### ISSUE TITLE
The Debian package drops a desktop file in the filesystem root

### ISSUE THREAD

**Issue by maaaat** [ProtonMail/proton-bridge#363]
The Debian package `protonmail-bridge` version `3.0.20-1` drops a desktop file in the filesystem root:

```
$ dpkg -L protonmail-bridge
/.
/ch.proton.bridge-gui.desktop
/usr
/usr/bin
/usr/lib/protonmail
[...]
```

That file is identical to `/usr/share/applications/ch.proton.bridge-gui.desktop`, it's probably just a glitch in the build scripts.

**Comment by LBeernaertProton** [comment]
Hey @maaaat thanks for bringing this to our attention, we'll try to resolve this as soon as we are able.
