### ISSUE TITLE
Auto Logs out everytime I restart my computer.

### ISSUE THREAD

**Issue by PrivacyOsint2** [ProtonMail/proton-bridge#367]
I am getting really annoyed that when I log into my computer in fedora 36 proton asks me my password every time plus my otp. There is no option to tell it to stop asking for my password and otp code. 

If I quit out of the app, it asks for my password and otp code again.

I am tried of putting in my password and otp code.

How do I stop this? It always shows this page and its annoying. I press "Got it". Next asking for my password then my otp code...
After a quit or reboot my computer it shows the same thing.. I am really tired of this daily..

I have removed the app and reinstalled it. Does nothing. Remove the cache folders and tried older versions still nothing.

![image](https://user-images.githubusercontent.com/93969855/226236493-35408fdd-c266-4d12-81eb-ba0492f59483.png)
![image](https://user-images.githubusercontent.com/93969855/226237287-44928029-9872-4560-a050-c745363c6d94.png)

**Comment by LBeernaertProton** [comment]
Hey @PrivacyOsint2 can you please state your operating system and bridge version.

**Comment by LBeernaertProton** [comment]
Hey @PrivacyOsint2 this is the same issue as reported in #359. Closing as duplicate.
