### ISSUE TITLE
In app Bridge update breaks it.

### ISSUE THREAD

**Issue by artelse** [ProtonMail/proton-bridge#369]
Got notification of an update on the bridge. It then won't start any longer, breaking my protonmail completely.

## Expected Behavior
An update should just update the app without breaking functionality.

## Current Behavior
The bridge has been working for years without problems.

## Possible Solution
Fix the app.
EDIT: found version 2.3.0. is the latest that still works.

## Version Information
macOS version is 10.13 and latest bridge is 3.0.21. I don't know what version was running, but seem to remember a version 3.x The bridge app now has a cross through it, so it won't launch because of a macOS version mismatch.

**Comment by gabor-meszaros** [comment]
Hi @artelse, Thank you for your interest in Bridge and I am sorry to hear that you have problems with the update. The issue tracker is ONLY used for reporting bugs with technical details. For high level troubleshooting, please contact our customer support: https://proton.me/support/contact
Customer support will reach out to us if they cannot resolve the problem.
