### ISSUE TITLE
[Thunderbird] "folders" and "labels" not syncing

### ISSUE THREAD

**Issue by Heziode** [ProtonMail/proton-bridge#37]
Few days ago, I have installed Thunderbird and added my Visionary account.

The problem is: "folders" and "labels" not synchronized.
I can sends emails, received new emails, but I cannot get other emalis.

OS: Archlinux (5.6.8-arch1-1)
Bridge version: 1.2.6
Thunderbird version: 68.7.0 (64 bits)

**Comment by jameshoulahan** [comment]
Hi! If you haven't already, please try to restart thunderbird. If that is no help, please contact bridge@protonmail.ch for more assistance.
