### ISSUE TITLE
Display bug with tray icon on Mate Desktop

### ISSUE THREAD

**Issue by Mezalor** [ProtonMail/proton-bridge#372]
I reported by mail more than a year ago a display bug on mate desktop that seemed to be known by the proton bridge support. This bug was introduced with proton bridge version 2 and I was hoping that it would be fixed with version 3.

## Expected Behavior
When you click on the proton bridge tray icon in the notification area a panel should open with various informations. It also allows to open quickly the proton bridge window.

## Current Behavior
With Mate desktop (for example in Ubuntu Mate 20.04 or 22.10) when you click on the proton bridge icon an empty panel opens as on the pictures below

![bug tray icon](https://user-images.githubusercontent.com/96955785/227802318-1fd0071c-2644-4335-b291-b89be87fdd11.png)
![bug tray icon with Menta](https://user-images.githubusercontent.com/96955785/227802328-0bdcc5e2-0c6d-46e5-96f8-0f8c211bfe77.png)

## Steps to Reproduce
Just install Ubuntu Mate in a VM then proton bridge and click on the proton bridge icon on the top right.

## Version Information
proton-bridge 3.0.21

**Comment by LBeernaertProton** [comment]
Hey @Mezalor we are aware that this tray menu is a bit problematic and are currently working on rewriting it. We will try to release this as soon as we are able.

In the mean time, can you check if starting bridge-gui with software renderer `--software-renderer` if this solves the issue?

**Comment by Mezalor** [comment]
Thanks for the quick answer.
I have the same issue with the `--software-renderer` option.

**Comment by ChrisStevens22** [comment]
I have had the same issue as above for a while. Even with the latest version or ProtonMail Bridge on Ubuntu 22.05.3 and Mate desktop. Just tried to uninstall and reinstall yesterday and the only way to get the app to show the screen is to manually invoke the "bridge-gui" app.

**Comment by Mezalor** [comment]
I just updated proton bridge to version 3.2.0 and that fixes the issue. Tanks !
