### ISSUE TITLE
Bridge fails to launch on Debian testing: Cannot find libOpenGL.so.0

### ISSUE THREAD

**Issue by aleuffre** [ProtonMail/proton-bridge#375]
## Expected Behavior
Protonmail Bridge launches correctly

## Current Behavior
```
❯ protonmail-bridge
/home/username/cache/protonmail/bridge/updates/3.0.21/bridge-gui: error while loading shared libraries: libOpenGL.so.0: cannot open shared object file: No such file or directory
FATA[Apr  7 11:30:30.123] Failed to launch                              error="exit status 127" exe_path=/home/username/.cache/protonmail/bridge/updates/3.0.21/bridge-gui exe_to_launch=bridge-gui launcher_path=/home/username/.cache/protonmail/bridge/updates/3.0.21/proton-bridge launcher_version=3.0.21
FATA[Apr  7 11:30:30.125] Failed to launch                              error="exit status 1"
```

Do note that after clearing the cache (`rm -rf .cache/*`)  the app runs normally, and a notification appears that an update exists. When restarting and applying the update, the error comes back again.

Error also persists if I install the 3.0.21 .deb package from the website.

## Possible Solution
Not sure if there's just an undeclared dependency, but manually installing libopengl0 `sudo apt install libopengl0` fixed the issue, though the application displays with an unusual border, unlike before.

Old border (v2.3.0): 
![image](https://user-images.githubusercontent.com/78726989/230586370-6d51b0e7-6921-458a-841a-c3337b31d9f0.png)

New Border (v3.0.21): 
![image](https://user-images.githubusercontent.com/78726989/230585786-bef7c0f3-7318-4265-9de6-43904c230254.png)

Also, not sure if relevant but on the previous versions I would get this warning:
```
WARN[Apr  7 11:41:11.388] Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.  pkg=frontent/qml
```
I do not get it anymore on the current version.

## Version Information
3.0.21

On debian testing, fully up to date with apt. 
Gnome version 43.3, using Wayland

**Comment by LBeernaertProton** [comment]
hey @aleuffre. This is a Qt6 specific issue that we can't fix.  You can try to apply the suggestion mentioned in #356.
