### ISSUE TITLE
Flatpak on Flathub is very out of date

### ISSUE THREAD

**Issue by Anvil5465** [ProtonMail/proton-bridge#377]
## Expected Behavior
Flatpak on Flathub should be up to date with the current release of the Proton Bridge.

## Current Behavior
The Proton Bridge flatpak is still on version 2.3.0 (current version is 3.0.21)

## Possible Solution
I'm not sure if this is an official flatpak or not, but either way, Proton shouldn't allow such an out of date package to exist on a website as popular as Flathub. If Proton isn't already the Flathub publisher, Proton should take over distribution on Flathub or request that the current publishers either update the package or remove it. If Proton is the publisher, Proton should update it.

## Steps to Reproduce
https://flathub.org/apps/details/ch.protonmail.protonmail-bridge

**Comment by LBeernaertProton** [comment]
Unfortunately, the flatpack package is not maintained by us at the moment. Please direct your concerns to the author of that repository.
