### ISSUE TITLE
synchronising does not complete

### ISSUE THREAD

**Issue by jknockaert** [ProtonMail/proton-bridge#378]
I installed Bridge version 3.1.1 on macos 13.3.1. After resetting Bridge it begins synchronising at a steady state but does not complete the sync. A first attempt did not get beyond the 13% mark, a second attempt got to 18%. After this point no further synchronising happens. Restarting Bridge does not make a change.

**Comment by LBeernaertProton** [comment]
Hey @jknockaert we have also noticed that, depending on the size of your messages and the amount of messages, sometimes the sync *may* seem like it is stuck, but it's actually still working. It can also happen that the progress jumps very large intervals (e.g: 7% to 80%). 

Once the sync has completed, it will never run again unless you remove and re-add the account. You can verify that the sync has completed by checking the logs.

**Comment by jknockaert** [comment]
@LBeernaertProton Well I was monitoring the network activity of Bridge and up until it got stuck there was a steady incoming stream which dropped to zero after it got stuck and stayed there for a long time (I think I waited for one hour) until I reset Bridge again. After resetting Bridge for the third time it got stuck again this time at 14% and zero network activity since...

**Comment by LBeernaertProton** [comment]
Without access to the logs we can't establish a reasonable cause. Please provide logs from your sync attempt.

**Comment by LBeernaertProton** [comment]
Please provide the logs or in case you don't feel comfortable, contact customer support and share your logs through that channel. 

Unless I can see the whole picture, I won't be able to make any assessments.

**Comment by LBeernaertProton** [comment]
@jknockaert we have fixed an issue that could prevent sync to complete. Thank you for your costumer service reports.

The fix is available as a pre-release here: https://github.com/ProtonMail/proton-bridge/releases/tag/v3.1.3.

Please let us know if this solves the issue for you.

**Comment by jknockaert** [comment]
The issue is fixed for me in 3.1.3.
