### ISSUE TITLE
Indicator applet UI is surprising on Gnome

### ISSUE THREAD

**Issue by kortschak** [ProtonMail/proton-bridge#379]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

## Expected Behavior

A single click on applets in the indicator applet bar on Gnome should open a theme-consistent menu.

## Current Behavior

A single click does nothing. A double click brings a theme inconsistent pane which is not really a menu, but which has an almost dark patterned menu button at the bottom right. ~This menu does not close when the outer pane is dismissed, remaining present when the applet indicator icon is double clicked again to open it.~

## Steps to Reproduce

1. File issue #255
    First issue:
    1. Single click on the applet indicator icon in Gnome.
    2. :cricket: 

    ~Second issue:~
    1. ~Double click on the icon.~
    2. ~Click on the three dots at the bottom right of the pane.~
    3. ~Click away.~
    4. ~Double click on the applet indicator icon.~
2. Wait one year.
3. Have original issue closed without investigation on the basis that the OS version is no longer supported and despite that the issue is a design issue and the code that does the work that is at issue has not been changed.
4. Install the latest version on a 22.04 VM and mess around for half an hour getting indicator applets to work with the full expectation that the issue will still be present, because you know, that's how not changing code impacts on changing behaviour.
5. See, surprising no-one, that indeed the design issue is still present. The second issue of not correctly updating pane state is resolved, presumably due to fixes in Qt or Gnome.

## Version Information

v3.0.21

## Context (Environment)

Ubuntu 22.04

**Comment by LBeernaertProton** [comment]
@kortschak In v3.2.0 we replaced with a native context menu. Does this solve the issue for you?

**Comment by kortschak** [comment]
I am unable to run the GUI version, so I run as a service now. I don't know if this fixes the issue.

**Comment by kortschak** [comment]
Ideally, you could show the change that is proposed to fix it and possibly show screenshots of the effect of the change. I think I've done enough debugging for ProtonMail.
