### ISSUE TITLE
proton-bridge 3.021 source build fails on vcpkg

### ISSUE THREAD

**Issue by doggodanubus** [ProtonMail/proton-bridge#380]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

## Expected Behavior
I  build the linux gui version and get a working program without issue. 2.3.0 did that. 

## Current Behavior
Fails because vcpkg is missing, wrong, etc
Snippet of output

./build.sh: line 61: dev: command not found
+ git submodule update --init --recursive /home/jcaldwel/Downloads/proton-bridge-3.0.21/internal/../extern/vcpkg
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
+ check_exit 'Failed to initialize vcpkg as a submodule.'
+ '[' 128 -ne 0 ']'
+ echo 'Process failed: Failed to initialize vcpkg as a submodule.'
Process failed: Failed to initialize vcpkg as a submodule.
+ rm -r ./cmake-build-release

## Possible Solution
Maybe build it on a current distributions before deploying it for each distribution and ensure it works on the major ones? 

## Steps to Reproduce
1) See the notice about updating
2) Crawl around the obtuse websites for the version listed in the update notice for the source package of that version. When you find it then 
3) Try and build it. 

## Version Information
3.0.32 source file from that is packaged and stored on this git

## Context (Environment)
I use it with a local mail client. 

## Detailed Description
Fix the source build.

**Comment by LBeernaertProton** [comment]
@doggodanubus are you building using `make build-gui` ?

**Comment by doggodanubus** [comment]
tower:proton-bridge$ make build-gui
go build -tags='' -ldflags '-X github.com/ProtonMail/proton-bridge/v3/internal/constants.Version=3.1.1+git -X github.com/ProtonMail/proton-bridge/v3/internal/constants.Revision=6fcea2ad83 -X github.com/ProtonMail/proton-bridge/v3/internal/constants.BuildTime=2023-04-24T07:54:18-0400 -X "github.com/ProtonMail/proton-bridge/v3/internal/constants.FullAppName=Proton Mail Bridge" -X github.com/ProtonMail/proton-bridge/v3/internal/constants.BuildEnv=dev' -o "proton-bridge" "./cmd/Desktop-Bridge/"
mv proton-bridge bridge
cd internal/frontend/bridge-gui/bridge-gui && \
	BRIDGE_APP_FULL_NAME="Proton Mail Bridge" \
	BRIDGE_VENDOR="Proton AG" \
	BRIDGE_APP_VERSION=3.1.1+git \
	BRIDGE_REVISION=6fcea2ad83 \
	BRIDGE_DSN_SENTRY= \
 		BRIDGE_BUILD_TIME=2023-04-24T07:54:18-0400 \
	BRIDGE_GUI_BUILD_CONFIG=Release \
	BRIDGE_BUILD_ENV=dev \
	BRIDGE_INSTALL_PATH=/home/xxxxxxxx/Downloads/proton-bridge/cmd/Desktop-Bridge/deploy/linux \
	./build.sh install
++ realpath ../../../..
++ START_DIR=/home/xxxxxxxx/Downloads/proton-bridge/internal/frontend/bridge-gui/bridge-gui
+++ basename ../../../..
++ BASENAME=..
+++ dirname ../../../..
++ cd ../../..
+++ readlink ..
++ LNK=
++ '[' '' ']'
++ REALPATH=/home/xxxxxxxx/Downloads/proton-bridge/internal/..
++ cd /home/xxxxxxxx/Downloads/proton-bridge/internal/frontend/bridge-gui/bridge-gui
++ echo /home/xxxxxxxx/Downloads/proton-bridge/internal/..
+ BRIDGE_REPO_ROOT=/home/xxxxxxxx/Downloads/proton-bridge/internal/..
+ BRIDGE_INSTALL_PATH=/home/xxxxxxxx/Downloads/proton-bridge/cmd/Desktop-Bridge/deploy/linux
+ BRIDGE_APP_VERSION=3.1.1+git
+ BRIDGE_APP_FULL_NAME='Proton Mail Bridge'
+ BRIDGE_VENDOR='Proton AG'
+ BUILD_CONFIG=Release
++ echo ./cmake-build-Release
++ tr '[:upper:]' '[:lower:]'
+ BUILD_DIR=./cmake-build-release
+ VCPKG_ROOT=/home/xxxxxxxx/Downloads/proton-bridge/internal/../extern/vcpkg
++ git rev-parse --short=10 HEAD
+ BRIDGE_REVISION=6fcea2ad83
+ BRIDGE_DSN_SENTRY=
+ BRIDGE_BUILD_TIME=2023-04-24T07:54:18-0400
+ BRIDGE_BUILD_ENV=
+ dev
./build.sh: line 61: dev: command not found
+ git submodule update --init --recursive /home/xxxxxxxx/Downloads/proton-bridge/internal/../extern/vcpkg
+ check_exit 'Failed to initialize vcpkg as a submodule.'
+ '[' 0 -ne 0 ']'
+ echo submodule udpated
submodule udpated
+ VCPKG_EXE=/home/xxxxxxxx/Downloads/proton-bridge/internal/../extern/vcpkg/vcpkg
+ VCPKG_BOOTSTRAP=/home/xxxxxxxx/Downloads/proton-bridge/internal/../extern/vcpkg/bootstrap-vcpkg.sh
+ /home/xxxxxxxx/Downloads/proton-bridge/internal/../extern/vcpkg/bootstrap-vcpkg.sh -disableMetrics
Downloading vcpkg-glibc...
+ check_exit 'Failed to bootstrap vcpkg.'
+ '[' 0 -ne 0 ']'
+ [[ linux-gnu == \d\a\r\w\i\n* ]]
+ [[ linux-gnu == \l\i\n\u\x* ]]
+ /home/xxxxxxxx/Downloads/proton-bridge/internal/../extern/vcpkg/vcpkg install sentry-native:x64-linux grpc:x64-linux --clean-after-build
Computing installation plan...
The following packages are already installed:
    grpc[codegen,core]:x64-linux -> 1.48.0
    sentry-native[core]:x64-linux -> 0.4.18
grpc:x64-linux is already installed
sentry-native:x64-linux is already installed
Restored 0 package(s) from /home/xxxxxxxx/.cache/vcpkg/archives in 2.154 us. Use --debug to see more details.

Total elapsed time: 29.98 ms

grpc provides CMake targets:
    # this is heuristically generated, and may not be correct
    find_package(gRPC CONFIG REQUIRED)
    # note: 7 additional targets are not displayed.
    target_link_libraries(main PRIVATE gRPC::gpr gRPC::grpc gRPC::grpc++ gRPC::grpc++_alts)

    find_package(modules CONFIG REQUIRED)
    target_link_libraries(main PRIVATE re2::re2 c-ares::cares)

sentry-native provides CMake targets:
    # this is heuristically generated, and may not be correct
    find_package(sentry CONFIG REQUIRED)
    target_link_libraries(main PRIVATE sentry::sentry sentry::breakpad_client)

+ check_exit 'Failed installing gRPC for Linux / Intel x64'
+ '[' 0 -ne 0 ']'
+ /home/xxxxxxxx/Downloads/proton-bridge/internal/../extern/vcpkg/vcpkg upgrade --no-dry-run
All installed packages are up-to-date with the local portfiles.
+ [[ linux-gnu == \d\a\r\w\i\n* ]]
+ BRIDGE_CMAKE_MACOS_OPTS=
+ cmake -DCMAKE_BUILD_TYPE=Release '-DBRIDGE_APP_FULL_NAME=Proton Mail Bridge' '-DBRIDGE_VENDOR=Proton AG' -DBRIDGE_REVISION=6fcea2ad83 -DBRIDGE_DSN_SENTRY= -DBRIDGE_BRIDGE_TIME= -DBRIDGE_BUILD_ENV=dev -DBRIDGE_APP_VERSION=3.1.1+git '' -G Ninja -S . -B ./cmake-build-release
CMake Warning:
  Ignoring empty string ("") provided on the command line.


-- BRIDGE_REPO_ROOT is /home/xxxxxxxx/Downloads/proton-bridge/internal/frontend/bridge-gui/bridge-gui/../../../..
-- VCPKG_ROOT is /home/xxxxxxxx/Downloads/proton-bridge/internal/frontend/bridge-gui/bridge-gui/../../../../extern/vcpkg
-- The CXX compiler identification is GNU 12.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- App name is Proton Mail Bridge
-- App vendor is Proton AG
-- Bridge version is 3.1.1+git
-- Found qmake at /usr/bin/qmake
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Found OpenGL: /usr/lib64/libOpenGL.so   
-- Found WrapOpenGL: TRUE  
-- Found XKB: /usr/lib64/libxkbcommon.so (found suitable version "1.4.1", minimum required is "0.5.0") 
-- Found WrapVulkanHeaders: /usr/include  
-- Using Qt 6.4.3
-- Found OpenSSL: /home/xxxxxxxx/Downloads/proton-bridge/extern/vcpkg/installed/x64-linux/lib/libcrypto.a (found suitable version "3.0.5", minimum required is "3")  
-- Found ZLIB: optimized;/home/xxxxxxxx/Downloads/proton-bridge/extern/vcpkg/installed/x64-linux/lib/libz.a;debug;/home/xxxxxxxx/Downloads/proton-bridge/extern/vcpkg/installed/x64-linux/debug/lib/libz.a (found suitable version "1.2.12", minimum required is "1")  
-- Bridge version is 3.1.1+git
-- Found qmake at /usr/bin/qmake
-- Found Protobuf: /home/xxxxxxxx/Downloads/proton-bridge/extern/vcpkg/installed/x64-linux/tools/protobuf/protoc (found version "3.21.3.0") 
-- Using protobuf 3.21.3.0
-- Found c-ares: /home/xxxxxxxx/Downloads/proton-bridge/extern/vcpkg/installed/x64-linux/share/c-ares/c-ares-config.cmake (found version "1.18.0") 
-- Found RE2 via CMake.
-- Using gRPC 1.48.0
-- protoc found /home/xxxxxxxx/Downloads/proton-bridge/extern/vcpkg/installed/x64-linux/tools/protobuf/protoc
-- grpc_cpp_plugin 
-- grpc_cpp_plugin found at /home/xxxxxxxx/Downloads/proton-bridge/extern/vcpkg/installed/x64-linux/tools/grpc/grpc_cpp_plugin
-- Configuring done (2.2s)
-- Generating done (0.0s)
CMake Warning:
  Manually-specified variables were not used by the project:

    BRIDGE_BRIDGE_TIME


-- Build files have been written to: /home/xxxxxxxx/Downloads/proton-bridge/internal/frontend/bridge-gui/bridge-gui/cmake-build-release
+ check_exit 'CMake failed'
+ '[' 0 -ne 0 ']'
+ cmake --build ./cmake-build-release
[40/40] Linking CXX executable bridge-gui
+ check_exit 'build failed'
+ '[' 0 -ne 0 ']'
+ '[' install == install ']'
+ cmake --install ./cmake-build-release
-- Install configuration: "Release"
-- Installing: /home/xxxxxxxx/Downloads/proton-bridge/cmd/Desktop-Bridge/deploy/linux/bridge-gui
-- Set runtime path of "/home/xxxxxxxx/Downloads/proton-bridge/cmd/Desktop-Bridge/deploy/linux/bridge-gui" to "$ORIGIN:$ORIGIN/../lib64:$ORIGIN/lib"
CMake Error at cmake-build-release/cmake_install.cmake:87 (file):
  file INSTALL cannot find "/usr/qml": No such file or directory.


+ check_exit 'install failed'
+ '[' 1 -ne 0 ']'
+ echo 'Process failed: install failed'
Process failed: install failed
+ rm -r ./cmake-build-release
+ exit 1
make: *** [Makefile:156: cmd/Desktop-Bridge/deploy/linux/bridge] Error 1

**Comment by LBeernaertProton** [comment]
Can you also let us know which distribution you are compiling this on as we are unable to reproduce the issue.

**Comment by LBeernaertProton** [comment]
Closed due to inactivity
