### ISSUE TITLE
Window opens in --no-window mode when update is available

### ISSUE THREAD

**Issue by petrmanek** [ProtonMail/proton-bridge#381]
## Expected Behavior
No window should be opened and the bridge should run silently in the background.

## Current Behavior
A window opens with the login screen (with the user logged out, why?) and a popup notifying of the update.

## Possible Solution
Check the `--no-window` flag before opening any GUI on Bridge startup. Or possibly use libnotify to send a notification to the user without having to open an actual window.

## Steps to Reproduce
1. Install older version of the Bridge (at least 1 version older than latest)
2. Run `proton-bridge --no-window`
3. Observe that a window opens

## Version Information
Arch Linux package v2.3.0-1, arch x86_64

## Context (Environment)
I run my Bridge from a shell script that launches Bridge silently in the background shortly before I run Thunderbird. This feature disrupts the startup sequence and I have to kill everything. I update my PC regularly -- the popup GUI serves no purpose in my case.

## Detailed Description
From my point of view, this is just a simple UI bug. It can be easily fixed by adding a single check.

## Possible Implementation
N/A

**Comment by LBeernaertProton** [comment]
Hey @petrmanek v2 is no longer supported. Are you able to reproduce this in v3?

**Comment by petrmanek** [comment]
@LBeernaertProton Turns out that AUR is for _some reason_ [holding the source package at v2](https://aur.archlinux.org/packages/protonmail-bridge#comment-906123), so I never got a chance to test v3 until recently. I installed v3 from a binary package, and have been using it for nearly a week. The bug has not appeared.

For that reason, I am closing this for now. If I see it in the future, I will re-open and pick this up here.
