### ISSUE TITLE
v3.2.0: GODT-2552, GODT-2553, GODT-2555, GODT-2556: Add telemetry.

### ISSUE THREAD

**Issue by AwlsomeAlex** [ProtonMail/proton-bridge#388]
Can you further explain this?

What telemetry is now being collected when using Proton Bridge?

**Comment by andrzejsza** [comment]
those tickets are about improved diagnostic data collection and making sure that Bridge follows global Proton telemetry setting (the one the users can set in the web app). Also, we've added the same local setting in Bridge with 3.2.0
Might be worth reading:
https://proton.me/legal/privacy#2-data-collection-and-usage
and
https://www.reddit.com/r/ProtonMail/comments/wppro6/why_does_proton_collect_telemetry_by_default/

Bridge doesn't do anything differently here, and as pointed out in one of the other threads:

> This data contains no personally identifiable information, but only technical details that help our developers fix bugs and improve the service more efficiently: timestamps of events (e.g. app crashes), browser version, OS version etc.

(in Bridge case we're taking about client version, of course).
