### ISSUE TITLE
Restore a way to disable local caching

### ISSUE THREAD

**Issue by primalmotion** [ProtonMail/proton-bridge#397]
In previous version of Bridge, it was possible to disable local caching. It was great when running it on small devices. Now I can't anymore, and this is a waste of space. Proton caches the mails, my client caches the mails. I have basically 2 copies of my mailbox, consuming gigabytes of data on a small 32GB phone.

## Expected Behavior
It should be possible to disable (or at least drastically limit) caching of emails.

## Current Behavior
Eats all my drive

## Possible Solution
Put back the option

## Steps to Reproduce
just start the app, it caches everything.

## Version Information
3.2.0

## Context (Environment)
Running proton bridge on a small mobile device.

**Comment by LBeernaertProton** [comment]
Unfortunately, the cache is currently required for v3's performance.  V2 was plagued with issues related to a lack of cache. We have no plans to restore this feature.

It's great to see bridge running in unexpected places, but a 32GB mobile phone with Linux is not among the targets we are considering when developing this piece of software.

**Comment by primalmotion** [comment]
I understand. Linux phones are becoming a real thing, so maybe in the future, you should start considering them a bit ;) In the meantime I have installed hydroxide on my servers. I would have installed proton-bridge but I could not find a way to make it listen on 0.0.0.0. 127.0.0.1 seems hardcoded

**Comment by LBeernaertProton** [comment]
This is by design, bridge is meant to be run on the same machine you 
will be accessing your mails from.
