### ISSUE TITLE
Account support without decryption (encrypted email pass through)

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#4]
Offer two sets of credentials for each IMAP account, one standard and one for passing message without doing decryption.

It is very useful for doing an encrypted backup or if you want to do encryption/decryption in the client.

**Comment by cuthix** [comment]
Thanks for this idea. We will discuss this.

**Comment by ettom** [comment]
Why would two sets of credentials be needed for this? Let's say I recieve an email that is encrypted to my own PGP key. Currently, Bridge mangles the encrypted message and wraps it html with a message :
```
Decryption error
Decryption of this message's encrypted content failed.
openpgp: incorrect key
```
The PGP message that follows is mangled and cannot be decrypted.
However, in the web client the same message is not mangled and can be decrypted with `gpg -d`. I find this behaviour very odd. Why is Bridge altering the content of the messages? Sending already encrypted emails fails too:
```
msmtp: the server did not accept the mail
msmtp: server message: 554 Error: transaction failed, blame it on the weather: backend: cannot create draft: cannot create attachment: Invalid input
```
I'd very much like to see this fixed. There should at least be an option to let incoming email pass through as-is.

**Comment by exander77** [comment]
@ettom You have a separate issue, my feature request is about access to encrypted messages which Proton Bridge can decrypt. Yours is about messages which it cannot decrypt. And you should report that bug.

I have just compiled a list of all bugs I have encountered: https://github.com/ProtonMail/proton-bridge/issues/27

**Comment by ettom** [comment]
Right, I misunderstood. Continued in #28

**Comment by andrzejsza** [comment]
Messages encrypted by 3rd party keys is a separate discussion. as for the two set credentials option - we won't be looking into this.

**Comment by exander77** [comment]
Other person requesting this:
https://www.reddit.com/r/ProtonMail/comments/qixor9/offering_pgp_crypted_mails_over_imap/

**Comment by ploum** [comment]
To clarify: it’s not about messages encrypted by a 3rd party key. It’s about downloading your Protonmail PGP private key, importing it in Thunderbird and use a straight IMAP.

There might be conceptual issues preventing this (and I would be genuinely curious to hear them) or this might be a choice to not develop such a feature which is, I agree, very niche.

Maybe it worth focusing on publishing a stable API between PM’s servers and the bridge to make the development of independent bridges easier (and, why not, having someday out-of-the-box Protonmail support in Thunderbird)
