### ISSUE TITLE
Unable to build: collect2 errors with "ld: cannot find -lGL"

### ISSUE THREAD

**Issue by jwflory** [ProtonMail/proton-bridge#40]
# Summary

`make build` does not successfully build the project

# Background

I tried to build the project today on Fedora 32 with Go v1.14.2. Running `make build` starts to pull in dependencies for the build, but then `collect2` fails. I'm not enough of a Go developer to figure out why.

This blocks me from packaging ProtonMail Bridge for Fedora and EPEL (CentOS/RHEL).

# Details

There is a short-term fix and long-term fix I see:

> **Short-term fix**: Figure out reason for build failure in stacktrace (below) and reproduce a clean build of ProtonMail Bridge

This gets me to successfully build proton-bridge in a way I can partially package for Fedora, but still makes it difficult to follow because of Fedora's [Golang Packaging Guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/Golang/).

> **Long-term fix**: Better separation and reproducibility of build steps

It would be better for me as a packager if proton-bridge worked with the [Golang Packaging Guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/Golang/) and macros in Fedora. Being able to `go get` the application and automatically detect dependencies from `go.sum` would require less hacking together on my end. It would be easier to package.

# Outcome

@jwflory can successfully reproduce a build of proton-bridge for packaging in Linux distributions

**Comment by jameshoulahan** [comment]
Hi, the build issue with `make build` is likely solved by https://github.com/ProtonMail/proton-bridge/issues/20. Can you confirm?

**Comment by jwflory** [comment]
@jameshoulahan Installing the dependencies fixed the build issue. I was able to replicate locally. Closing this issue!
