### ISSUE TITLE
tag v3.3.0 does not belong to any branch on this repository.

### ISSUE THREAD

**Issue by themobiusproject** [ProtonMail/proton-bridge#400]
I believe that `git push --tags` was run but not `git push` or somehow that commit is not in a branch. The most recent commit in master is May 15th where v3.3.0 was released early June (three weeks ago by what github is telling me).

## Expected Behavior
```
/path/to/proton-bridge $ git checkout v3.3.0
HEAD is now at 419a442 chore: Stone Bridge 3.3.0 changelog.
```

## Current Behavior
```
/path/to/proton-bridge $ git checkout v3.3.0
error: pathspec 'v3.3.0' did not match any file(s) known to git
```

## Possible Solution
`$ git push`

## Steps to Reproduce
1. `git clone https://github.com/ProtonMail/proton-bridge.git`
2. `cd proton-bridge`
3. `git checkout v3.3.0`

**Comment by LBeernaertProton** [comment]
Hey @themobiusproject, thanks for the heads up. The tag is now available.
