### ISSUE TITLE
Bridge pops up on any notification action being triggered

### ISSUE THREAD

**Issue by karcsesz** [ProtonMail/proton-bridge#401]
Updated to Bridge v3.3.0 on my Linux laptop running Manjaro Plasma using the self-updater, and I've noticed that any time I click on a desktop notification, Bridge pops into the foreground.

## Expected Behavior
Bridge should only pop up for actions on notifications created by it.

## Current Behavior
Bridge pops up on any notification action being triggered.

## Possible Solution
It's possible the dbus event filtering is broken?

## Steps to Reproduce
1. Launch Proton Mail Bridge v3.3.0
2. `notify-send -A test test`
3. Click the button on the notification
4. Bridge pops into foreground

## Version Information
Proton Mail Bridge v3.3.0 (br-149)
Broken on both the self-updated version and after running a full update from AUR [`protonmail-bridge-bin`](https://aur.archlinux.org/packages/protonmail-bridge-bin)

## Context (Environment)
Only able to test on KDE Plasma v5.27 as shipped by Manjaro, but the issue is likely also present on other desktop environments.

**Comment by LBeernaertProton** [comment]
Hey @karcsesz , thanks for reporting this issue and providing repo steps. We have verified this behavior and are tracking it internally as GODT-2751.

**Comment by mchilson** [comment]
Having the same issue on Ubuntu Budgie 23.04

**Comment by mvv588** [comment]
Same on Linux Mint 21 Cinnamon.

**Comment by LBeernaertProton** [comment]
Upon further investigation, this seems to be a be a [bug in Qt](https://bugreports.qt.io/browse/QTBUG-112170). 

Until Qt addresses the issue, there is nothing we can do unfortunately.

**Comment by egerlach** [comment]
@karcsesz @mvv588 @mchilson If you're willing, you can sign up to the qt bugtracker and add your vote. Since the bug is in Qt, +1s here will have no effect.

**Comment by egerlach** [comment]
As a workaround, I created `~/.config/systemd/user/protonmail-bridge.service` which contains:

```
[Unit]
Description=Proton Mail Bridge

[Service]
ExecStart=/usr/bin/protonmail-bridge --noninteractive
Restart=on-failure
RestartSec=10
StandardError=append:///home/<username>/.local/share/protonmail/bridge-v3/logs/noninteractive.log

[Install]
WantedBy=default.target
```

and then ran

`systemctl --user enable protonmail-bridge.service` and `systemctl --user start protonmail-bridge.service`

I then disabled the autostart for ProtonMail in System Settings. I *think* I now have a running ProtonMail Bridge without a GUI... so far so good, but I can't promise that I didn't get something wrong in that systemd unit.

**Comment by mvv588** [comment]
Seems to be fixed on my system since the last bridge update, it is also possible a update in Linux Mint resolved it.

**Comment by karcsesz** [comment]
Same here, the issue is no longer present on version 3.3.2.
Thank you!

**Comment by karcsesz** [comment]
Ah, it was worked around in 6359b8639e17668af7c9f026266cdd80bdf84141
Hope Qt can push a proper fix soon
