### ISSUE TITLE
Publish protonmail-bridge.desktop in git

### ISSUE THREAD

**Issue by jwflory** [ProtonMail/proton-bridge#41]
I am trying to package ProtonMail Bridge for Fedora. I see in the official RPM from ProtonMail, there is a `.desktop` file included in the RPM:

```desktop
[Desktop Entry]
Type=Application
Version=1.1
Name=ProtonMail Bridge
GenericName=ProtonMail Bridge for Linux
Comment=The Bridge is an application that runs on your computer in the background and seamlessly encrypts and decrypts your mail as it enters and leaves your computer.
Icon=/usr/share/icons/hicolor/scalable/apps/protonmail-bridge.svg
Exec=protonmail-bridge
Terminal=false
Categories=Office;Email;Network
StartupWMClass=protonmail-bridge
```

It would be nice for downstream packagers if this file, along with the `Icon` SVG, were available in upstream.

**Comment by jameshoulahan** [comment]
This is a good request and I don't see a reason why we can't include these in the bridge repo itself. I've opened an issue internally

**Comment by A6GibKm** [comment]
Note that the .desktop file is invalid according to `desktop-file-validate` and has an extra newline at the end.

**Comment by jameshoulahan** [comment]
@A6GibKm we recently improved the `.desktop` file. The version of this file distributed with `v1.2.7-beta` (released yesterday) validates fine with just a `hint`. But I'll take note about the extra newlines, good catch.

**Comment by andrzejsza** [comment]
it took a while - done in 1.6.3.
