### ISSUE TITLE
When will gluon v0.17 be integrated?

### ISSUE THREAD

**Issue by petrmanek** [ProtonMail/proton-bridge#411]
Hello, is there an ETA or a milestone for integrating gluon v0.17?

I am currently using the latest PM Bridge, finding myself limited by https://github.com/ProtonMail/gluon/issues/380, which was fixed upstream in the latest version, however this has not make its way to the Bridge yet. I am working around the issue using regexes for now, but it would be helpful to have an overview of when a proper solution can be expected.

Related discussion: https://github.com/imapsync/imapsync/issues/403

**Comment by LBeernaertProton** [comment]
Hey. It it scheduled for inclusion in v3.5. Unfortunately, I can't make any promises on the release date for that update.
