### ISSUE TITLE
Bridge for linux stuck in synchronizing state (Synchronizing 0%)

### ISSUE THREAD

**Issue by Maltstar** [ProtonMail/proton-bridge#413]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

ProtonMail Emails can no be accessed  on linux anymore from thunderbird using the proton bridge.

Email client does not show emails from protonmail.

## Expected Behavior
Bridge shows the status synchronized.
The emails from the protonmail account are synchronized and  can be seen in thunderbird

## Current Behavior
When the bridge is started it gets stuck in the synchronizing state (Synchronizing 0%),  so that the bridge does not synchronized emails from server
I am also using Thunderbird to see my emails, wherever I click, the content is erased, if I click on inbox, it becomes empty.

## Steps to Reproduce
1. Start the bridge
2. Open Thunderbird
3.
4.

## Version Information
Protonmail Bridge v3.3.2 (br-157)
Thunderbird/102.13.0 (Ubuntu 22.04.2 LTS)
Ubuntu Mate (Ubuntu 22.04.2 LTS)

## Context (Environment)
I can not access my mail via the mail client thunderbird.
It happens on 25 July on afternoon. On the morning it was perfectly working, then on the afternoon around 3:00 PM not anymore

**Comment by LBeernaertProton** [comment]
Hey @Maltstar there was a server outage issue. All connections are currently throttled.  The situation should improve gradually.
