### ISSUE TITLE
Received invalid UTF-8 Command on login

### ISSUE THREAD

**Issue by Red-S2** [ProtonMail/proton-bridge#417]
## Expected Behavior
Thunderbird detects protonbridge and I can read my Emails

## Current Behavior
Thunderbird detects protonbridge which says : 

WARN[Aug  9 20:54:25.610] Captured message                              message="Received invalid UTF-8 command" reportID=36b9e606fe294fcfa42e4f5c1e2518b4

on login attempts

## Steps to Reproduce
1. get proton-bridge-nokeychain from the aur
2. try to login using the suggested configuration from Thunderbird

## Version Information
protonmail-bridge-nokeychain-3.0.20-1
thunderbird 115.1.0-1

**Comment by LBeernaertProton** [comment]
Hey @Red-S2, please update your bridge version. This issue has been fixed somewhere between 3.1 and 3.2.
