### ISSUE TITLE
Please tag releases with git tags

### ISSUE THREAD

**Issue by jwflory** [ProtonMail/proton-bridge#42]
Hi,

It would be great if upstream could use git tags for new software releases. This will make it easier to package for downstream Linux distributions and will also allow for updates to be tracked in [release-monitoring.org](https://release-monitoring.org/).

Thanks!

**Comment by jameshoulahan** [comment]
https://github.com/ProtonMail/proton-bridge/issues/35 and https://github.com/ProtonMail/proton-bridge/issues/10

Will be tagged from now on 🙂

**Comment by jwflory** [comment]
Awesome. I look forward for the next release so I can move forward with packaging in Fedora. :smile:
