### ISSUE TITLE
Server did not provide gRPC service configuration in time. (Ubuntu 23.04)

### ISSUE THREAD

**Issue by janjaromirhorak** [ProtonMail/proton-bridge#422]
Protonmail Bridge does not start - it hangs for a while and then shows a popup saying `Server did not provide gRPC service configuration in time.`.

## Expected Behavior
Protonail Bridge starts normally.

## Current Behavior
Protonmail Bridge does not start - it hangs for a while and then shows a popup saying `Server did not provide gRPC service configuration in time.`. I am using pass as the keychain of choice. This behavior has been consistent for me on the following versions: `3.3.2-1` and `3.4.2-1`. I am running Ubuntu 23.04 and I have followed [the official docs](https://proton.me/support/installing-bridge-linux-deb-file) for installing the bridge.

This is what I see after running `protonmail-bridge` in the terminal:

```
INFO[Sep 11 17:57:18.728] bridge-gui starting
INFO[Sep 11 17:57:18.728] Using Qt 6.3.2
INFO[Sep 11 17:57:18.733] lock file created /home/[USERNAME]/.cache/protonmail/bridge-v3/bridge-v3-gui.lock
INFO[Sep 11 17:57:18.733] New Sentry reporter - id: MHdRfeTrprEO1J6GpE8ZJdIU4Q2513qP5B/Kk3dVAjE=.
DEBU[Sep 11 17:57:18.735] Bridge executable path: /usr/lib/protonmail/bridge/bridge
INFO[Sep 11 17:57:18.735] Launching bridge process with command "/usr/lib/protonmail/bridge/bridge" --grpc --parent-pid 6267 --session-id 20230911_175718698 --launcher /usr/lib/protonmail/bridge/proton-bridge
INFO[Sep 11 17:57:18.735] Retrieving gRPC service configuration from '/home/[USERNAME]/.config/protonmail/bridge-v3/grpcServerConfig.json'
time="2023-09-11T17:57:18+02:00" level=warning msg="Failed to add test credentials to keychain" error="failed to create item: Object does not exist at path “/org/freedesktop/secrets/collection/login”" helper="*keychain.SecretServiceDBusHelper"
reportID: 5c81b95f7eb34a7f522f17300923582b Captured exception :waitAndRetrieveServiceConfig(): Server did not provide gRPC service configuration in time.
FATA[Sep 11 18:00:34.033] Failed to launch                              error="exit status 1" exe_path=/usr/lib/protonmail/bridge/bridge-gui exe_to_launch=bridge-gui launcher_path=/usr/lib/protonmail/bridge/proton-bridge launcher_version=3.4.2
```

## Steps to Reproduce

1. Follow the [instructions](https://proton.me/support/installing-bridge-linux-deb-file) to install protonmail-bridge on Ubuntu 23.04.
2. Launch protonmail-bridge, find out that a password manager in required, install `pass` from repository.
3. Launch protonmail-bridge, everything works fine.
4. Restart computer, protonmail-bridge fails to launch.

## Version Information

- protonmail-bridge: `3.4.2` or `3.3.2`
- pass: `1.7.4`
- Ubuntu `23.04`

**Comment by LBeernaertProton** [comment]
Is it possible that the `pass` service is not initialized after reboot?

I'm not very familiar with pass, but I recall that with KeePassXC one needs to unlock the vault before the service becomes available.

**Comment by janjaromirhorak** [comment]
It is possible that the bridge starts before pass does, but even restarting the bridge (thus starting it after pass is already initialized) didn't help.

Currently, after several restarts, everything now seems to work without issues. Since I am not able to provide steps for reliably reproduce this problem, I will close this issue.

**Comment by ckpinguin** [comment]
Just had the same on my Mac. Was the first time since 2 months, but reproducing it, as said, is not really possible.

**Comment by petrmanek** [comment]
Unfortunately, I am now seeing this issue reliably after updating to Qt 6.8 and the latest bridge.

First, the Bridge refuses to start due to #500. When I run it in `--cli` mode, it starts and synchronizes, but after a moment I see the following box pop up of nowhere:

![20241017_09h18m18s_grim](https://github.com/user-attachments/assets/9347b657-c8b7-4045-a166-3a515560e9a3)

I am running the latest (as of writing) Arch Linux:

 - kernel 6.11.3
 - pass 1.7.4
 - protonmail-bridge 3.14.0
 - qt 6.8.0

**Comment by petrmanek** [comment]
Perhaps one more useful update for troubleshooting this. Here are some logs that I see in stdout:

```
[...]
INFO[Oct 17 09:15:08.315] Launching bridge process with command "/usr/lib/protonmail/bridge/bridge" --grpc --parent-pid 604567 --cli --launcher protonmail-bridge --session-id 20241017_091508296
INFO[Oct 17 09:15:08.315] Retrieving gRPC service configuration from '/home/petr/.config/protonmail/bridge-v3/grpcServerConfig.json'
WARN[Oct 17 09:15:09.411] Failed to add test credentials to keychain    error="failed to open secretservice session: The name is not activatable" helper="*keychain.SecretServiceDBusHelper"
[... after 3min ...]
reportID: 00000000000000000000000000000000 Captured exception :waitAndRetrieveServiceConfig(): Server did not provide gRPC service configuration in time.
```

**Comment by albohlabs** [comment]
@petrmanek As mentioned in https://github.com/ProtonMail/proton-bridge/issues/500#issuecomment-2426689411 you can start the bridge with `protonmail-bridge-core -n`, which works for me at the moment.

**Comment by jaredmo** [comment]
@albohlabs That only works if the user has already configured the email client.

**Comment by petrmanek** [comment]
> @petrmanek As mentioned in [#500 (comment)](https://github.com/ProtonMail/proton-bridge/issues/500#issuecomment-2426689411) you can start the bridge with `protonmail-bridge-core -n`, which works for me at the moment.

My current mitigation is to run `proton-bridge --cli` and just _not click_ on OK in the Qt error message dialog. Turns out that if you do not close the message box, the Bridge still continues to work and normally sync messages in both directions. Who would've thought!
