### ISSUE TITLE
Bridge not functioning with KeePassxc version  2.7.6

### ISSUE THREAD

**Issue by jontyms** [ProtonMail/proton-bridge#425]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

Bridge successfully creates a secret in keepassxc on first launch. Upon successive launches bridge complains of missing secret service.
## Expected Behavior

Correctly reads secret from keepassxc
## Current Behavior

```
INFO[Sep 23 21:34:02.240] bridge-gui starting
INFO[Sep 23 21:34:02.240] Using Qt 6.3.2
INFO[Sep 23 21:34:02.251] lock file created /home/user/.cache/protonmail/bridge-v3/bridge-v3-gui.lock
INFO[Sep 23 21:34:02.251] New Sentry reporter - id: *******.
DEBU[Sep 23 21:34:02.256] Bridge executable path: /usr/lib/protonmail/bridge/bridge
INFO[Sep 23 21:34:02.256] Launching bridge process with command "/usr/lib/protonmail/bridge/bridge" --grpc --parent-pid  ***--session-id  **** --launcher /usr/lib/protonmail/bridge/proton-bridge
INFO[Sep 23 21:34:02.256] Retrieving gRPC service configuration from '/home/user/.config/protonmail/bridge-v3/grpcServerConfig.json'
time="2023-09-23T21:34:02-04:00" level=info msg="Migrating keychain helper"
ERRO[Sep 23 21:34:02.429] Could not load/create vault key               error="could not get keychain item: failed to get secret: org.freedesktop.Secret.Error.IsLocked"
WARN[Sep 23 21:34:02.446] The vault key could not be retrieved; the vault will not be encrypted 
```

## Steps to Reproduce

1. Make sure keepassxc is running unlocked with secret service enabled
2. start bridge
4. Restart bridge
5. Wallet error is shown

## Context (Environment)

Arch Linux

## Version Information

KeePassxc 2.7.6
Bridge 3.4.2

https://github.com/ProtonMail/proton-bridge/issues/359#issuecomment-1596327468

**Comment by LBeernaertProton** [comment]
Hey @jontyms, could you confirm if you also [created this file](https://github.com/ProtonMail/proton-bridge/issues/359#issuecomment-1602078417) ?

**Comment by jontyms** [comment]
Yes it exists
```
{
  "Helper": "secret-service-dbus"
}
```

**Comment by jontyms** [comment]
A reinstall fixed the issue
