### ISSUE TITLE
Support RFC 8551 (S/MIME) V4.0 Message Specification (for EnvelopedData / Protected Headers)

### ISSUE THREAD

**Issue by jwflory** [ProtonMail/proton-bridge#43]
In Thunderbird with Enigmail and a GPG key, I can encrypt my emails and header data, like subjects, with [Autocrypt][1]. I would like ProtonMail Bridge to support [RFC 8551][2] / [Autocrypt Protected Headers][3] so my header data remains confidential and so I can reply to encrypted subjects with clients that support that protocol.

## Expected Behavior

1. Alice has a GPG key, Bob has a ProtonMail account with ProtonMail Bridge and Thunderbird
1. Alice encrypts a message with [Protected Headers][3] with Bob's public key
1. Alice's encrypted message passes through ProtonMail servers and to ProtonMail Bridge on Bob's computer
1. Bob receives encrypted email from Alice
1. Bob successfully decrypts Alice's message with [Protected Headers][3] like the Subject: field

## Current Behavior

1. Alice has a GPG key, Bob has a ProtonMail account with ProtonMail Bridge and Thunderbird
1. Alice encrypts a message with [Protected Headers][3] with Bob's public key
1. Alice's encrypted message passes through ProtonMail servers and to ProtonMail Bridge on Bob's computer
1. Bob receives encrypted email from Alice
1. Bob successfully decrypts Alice's message, _but_ details like the email subject and some other metadata is lost.

## Possible Solution

Not sure if this is an upstream issue with ProtonMail server software, or if this kind of email metadata can be decrypted by ProtonMail Bridge. But any solution that provides me with two-way encrypted email support through ProtonMail Bridge, I am happy.

For what it is worth, I am a Visionary subscriber. I prefer to submit feedback as an open source bug instead of starting with support. (This is similar to how Red Hat encourages their customers to collaborate upstream on Red Hat's open source products.) But happy to direct this where it will be heard.

## Context (Environment)

It affects me in two ways:

1. Difficult to communicate with non-ProtonMail PGP users who use [Protected Headers][3] to encrypt email subjects
1. Leaves [one vector of discussion exposed][2] in non-ProtonMail email server transit

It would make me feel more secure if I could trust that metadata like email subject is also encrypted by default.

## Detailed Description

* [PROPOSED STANDARD RFC 8551][2]: See [sections 2.4.3 and 2.4.4][4] on EnvelopedData and AuthEnvelopedData Content Types
* [Protected Headers for Cryptographic E-mail][3]: Draft RFC under review for Autocrypt Protected Headers
* [autocrypt/protected-headers][5]: GitHub project where spec is better defined

## Possible Implementation

Not sure if the bridge could handle this metadata locally on the client or if it needs to be processed upstream in the server. But the desired user experience is the email subject is either decrypted by default, or (current behavior in Thunderbird+Enigmail), the subject decrypts once I open the email.

---

[1]: https://github.com/autocrypt
[2]: https://tools.ietf.org/html/rfc8551
[3]: https://datatracker.ietf.org/doc/draft-autocrypt-lamps-protected-headers/
[4]: https://tools.ietf.org/html/rfc8551#section-2.4.3
[5]: https://github.com/autocrypt/protected-headers

**Comment by andrzejsza** [comment]
We really like this idea, but have no bandwidth for this (3 years later...). Closing the issue.
