### ISSUE TITLE
option to disable saving sent messages

### ISSUE THREAD

**Issue by jknockaert** [ProtonMail/proton-bridge#430]
When sending a message bridge automatically saves the message in the Sent folder. Some email clients do this already independently from bridge, resulting in all sent messages being saved twice.

## Expected Behavior
It would be helpful if there would be an option in Bridge to disable automatically saving the sent message.

## Current Behavior
Bridge saves a copy of each sent message in the Sent folder; this cannot be disabled.

## Possible Solution
Add an option in the settings.

## Version Information
Am using Bridge version 3.4.2.

**Comment by LBeernaertProton** [comment]
Unfortunately this is not possible to implement. The messages that end up in the sent folder need to match the output of the transformations the Proton backend performs. 

For instance, if we were to use the message from the IMAP client as is, we would lose the information regarding the Proton Message ID, making it impossible for us to identify the message.

In bridge we perform message de-duplication to ensure  that, in case the IMAP client doesn't have an option to disable this, you do not see duplicate messages in your sent folder.

**Comment by jknockaert** [comment]
Well in my case automatic deduplication seems not to be working properly. Am using Mailmate as email client, and I end up with plenty duplicates in my Sent messages folder.

**Comment by jknockaert** [comment]
Looking at it deduplication seems to fail mostly (maybe only) for messages with an attachment. Should I open a separate issue for this?

**Comment by LBeernaertProton** [comment]
@jknockaert we have a couple of fixes in 3.5 which correct a problem in the dedup. I would kindly ask to try again with 3.5 once it reaches stable release and if you still have issues, open a separate ticket.
