### ISSUE TITLE
tag v3.5.3 does not belong to any branch on this repository.

### ISSUE THREAD

**Issue by themobiusproject** [ProtonMail/proton-bridge#432]
I am mostly copying/pasting from the last time I reported this issue #400. If there is a preferred way for me to report that it wasn't pushed correctly, please let me know.

I believe that `git push --tags` was run but not `git push` or somehow that commit is not in a branch.

## Expected Behavior
```
/path/to/proton-bridge $ git checkout v3.5.3
HEAD is now at ...
```

## Current Behavior
```
/path/to/proton-bridge $ git checkout v3.5.3
error: pathspec 'v3.5.3' did not match any file(s) known to git
```

## Possible Solution
`$ git push`

## Steps to Reproduce
1. `git clone https://github.com/ProtonMail/proton-bridge.git`
2. `cd proton-bridge`
3. `git checkout v3.5.3`

**Comment by LBeernaertProton** [comment]
@themobiusproject Thanks for the report. This should be fixed now.
