### ISSUE TITLE
`bufio: buffer full`

### ISSUE THREAD

**Issue by mrusme** [ProtonMail/proton-bridge#437]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

## Expected Behavior
It should be possible to import mails via Proton Bridge or the Import Export tool.

## Current Behavior
Some emails seem impossible to import via either of the two tools. The mails are valid emails from another IMAP server. Tried importing via drag and drop in Thunderbrid (from IMAP to Proton Bridge) as well as via EML download and import via Import Export tool. Both times I get the `bufio` error. Here is the exact error from the Import Export tool:

```
failed to import: failed to parse message: failed to create new parser: bufio: buffer full
```

## Possible Solution
None found so far, cannot import all mails, blocked by that.

## Steps to Reproduce
Reproducing it seems hard as it doesn't happen with *every* mail but only with some. As the emails that this happens with are private, I cannot share them publicly on GitHub. However, from my observation, these emails have in common that they use special characters (ñ, á, í, etc) as well as contain HTML and sometimes a relatively large (~10 mb) attachment.

## Version Information
Proton Bridge 3.5.4 (br-177), Import Export 1.3.3

## Context (Environment)
macOS 14.1

**Comment by LBeernaertProton** [comment]
Hey @mrusme, can you check if you have enough free space/ram on your machine when performing these operations?

Initial observations seem to indicate this error happens in circumstances where there is not enough RAM or free disk space in the temporary file directory.

What are the specs of your machine?

**Comment by mrusme** [comment]
Hey there @LBeernaertProton, thank you for the fast reply! Specs are 2018 15" MacBook Pro, 32 GB 2400 MHz DDR4, 256 GB free disk space. There *should* be enough space, but I will double-check what the exact memory stats are when this happens!

**Comment by LBeernaertProton** [comment]
@mrusme did you manage to reproduce the issue?

**Comment by mrusme** [comment]
@LBeernaertProton *unfortunately* I didn't yet. Still looking to hit *that special email* that makes the bridge go booh. If you'd like feel free to close this issue and I will re-open it as soon as I see it happening again, hopefully being able to provide further insights.
