### ISSUE TITLE
Create official Fedora / EPEL package

### ISSUE THREAD

**Issue by jwflory** [ProtonMail/proton-bridge#44]
I'm opening this issue as an initial discussion point for landing `protonmail-bridge` as an official package in Fedora and Fedora EPEL (for CentOS/RHEL). I think this would make ProtonMail Bridge more accessible for many Linux users. It would also ensure compliance with Fedora's licensing guidelines for best open source practices.

I have started to test building a RPM spec. It is my first time packaging a Golang app for Fedora. It is taking me some time to figure it out, but I am working with the Packaging Guidelines:

https://docs.fedoraproject.org/en-US/packaging-guidelines/Golang/

If upstream has an RPM spec for ProtonMail Bridge, it would also be nice to consider committing this to the source repo. I am also happy to contribute RPM spec improvements back upstream that comply with the Fedora Packaging Guidelines.

**Comment by jwflory** [comment]
Hi, as an update, I am looking at building a package and submitting it for distribution to default repositories for Fedora, CentOS, and RHEL. I hope to begin this process later in August once I finish a working RPM spec.

Is there an interest upstream to co-maintain the official package? I can help upstream navigate the process if so, I have been packaging for Fedora for a few years already.

**Comment by A6GibKm** [comment]
I would appreciate if you share the manifest once available (and working) to see if I can port it to the Flatpak distribution.

**Comment by jwflory** [comment]
@A6GibKm Sure. Like all Fedora RPM specs, it will be published in Fedora's dist-git repositories for packages once it is packaged. I'll probably do some earlier testing before then though.

https://src.fedoraproject.org/dashboard/projects

**Comment by dsommers** [comment]
Let me know if you need some help, @jwflory.  I was about to start doing the same.

**Comment by jwflory** [comment]
@dsommers I made a start on this months ago, but did not finish. Do you have a RPM spec written? I am happy to co-maintain with you as a Fedora packager if you want to work together. 👍🏻 Not sure if you are already an active Fedora packager, but I can help you get started if not!

**Comment by A6GibKm** [comment]
Please share if you have anything that half works, I could use that as an idea to build from source on flathub.

**Comment by dsommers** [comment]
@jwflory I didn't get started writing anything yet, I wanted to see if anyone else had picked up this task.

I'm the maintainer of a few Fedora/EPEL packages (openvpn, eurephia) plus I have a few more in [Fedora Copr](https://copr.fedorainfracloud.org/coprs/dsommers/).  I've also maintained a couple of packages during my years at Red Hat.  I'm also paying attention to the fedora-devel mailing list.  It's mostly been C/C++ or Python projects I've been involved in.  SO I would claim I know the basics of RPM packaging and do try to adhere to the Fedora Packaging guidelines in all I do.

But would be really I'm happy to be involved in Proton Bridge packaging.  If you have something written, I could start with that (share a git repo or a gist).  I just need to read up a bit on golang packaging, as I've never done this kind of packages before.

@A6GibKm anything we should beware of in regards to the .spec file for flatpak?   But not sure I see the advantage of flatpaks when we will provide native packages.  Anyhow, that's your call in the end :slightly_smiling_face:

**Comment by Germano0** [comment]
There are too many libraries to package.
`$ go2rpm github.com/ProtonMail/proton-bridge`
and then when running mock build against the spec file generated by go2rpm I got:

```
No matching package to install: 'golang(github.com/0xAX/notificator)'
No matching package to install: 'golang(github.com/ProtonMail/go-appdir)'
No matching package to install: 'golang(github.com/ProtonMail/go-autostart)'
No matching package to install: 'golang(github.com/ProtonMail/go-imap-id)'
No matching package to install: 'golang(github.com/ProtonMail/go-rfc5322)'
No matching package to install: 'golang(github.com/ProtonMail/go-vcard)'
No matching package to install: 'golang(github.com/ProtonMail/gopenpgp/v2/crypto)'
No matching package to install: 'golang(github.com/abiosoft/ishell)'
No matching package to install: 'golang(github.com/allan-simon/go-singleinstance)'
No matching package to install: 'golang(github.com/cucumber/godog/gherkin)'
No matching package to install: 'golang(github.com/emersion/go-imap)'
No matching package to install: 'golang(github.com/emersion/go-imap-appendlimit)'
No matching package to install: 'golang(github.com/emersion/go-imap-idle)'
No matching package to install: 'golang(github.com/emersion/go-imap-move)'
No matching package to install: 'golang(github.com/emersion/go-imap-quota)'
No matching package to install: 'golang(github.com/emersion/go-imap-specialuse)'
No matching package to install: 'golang(github.com/emersion/go-imap-unselect)'
No matching package to install: 'golang(github.com/emersion/go-imap/backend)'
No matching package to install: 'golang(github.com/emersion/go-imap/client)'
No matching package to install: 'golang(github.com/emersion/go-imap/server)'
No matching package to install: 'golang(github.com/emersion/go-mbox)'
No matching package to install: 'golang(github.com/emersion/go-message)'
No matching package to install: 'golang(github.com/emersion/go-sasl)'
No matching package to install: 'golang(github.com/emersion/go-smtp)'
No matching package to install: 'golang(github.com/emersion/go-textwrapper)'
No matching package to install: 'golang(github.com/getsentry/sentry-go)'
No matching package to install: 'golang(github.com/jameskeane/bcrypt)'
No matching package to install: 'golang(github.com/jaytaylor/html2text)'
No matching package to install: 'golang(github.com/nsf/jsondiff)'
No matching package to install: 'golang(github.com/therecipe/qt/core)'
No matching package to install: 'golang(github.com/therecipe/qt/gui)'
No matching package to install: 'golang(github.com/therecipe/qt/qml)'
No matching package to install: 'golang(github.com/therecipe/qt/widgets)'
```

**Comment by dsommers** [comment]
@Germano0 Using tools like `go2rpm` are not really an accepted way to get a package upstream distributions.  It can help, to reach that goal - as you get some of the needed generic stuff done.  But as you see, it requires quite a some work afterwards anyhow.  And it does not account for Go dependencies already packaged, and those existing packages should normally be preferred over bundling your own dependencies.

As a starting point, always look at the packaging guidelines first .... https://docs.fedoraproject.org/en-US/packaging-guidelines/Golang/  Adhering to these guidelines is the bare minimum to get the .spec file through a peer-review.

**Comment by Germano0** [comment]
@dsommers go2rpm is a tool that most of times does the most of the work on the spec file. I have done fedora package review of more than 10 Go libraries and I am the comaintainer of bettercap which is written in Go

**Comment by A6GibKm** [comment]
Here https://github.com/flathub/ch.protonmail.protonmail-bridge/pull/46/files, you can find the sources of all the required modules. At least with the versions required in a past version.

**Comment by cuthix** [comment]
Hi, (mostly copied from #72)
after discussion within other products we decided to maintain Fedora / EPEL package, hence I will close this issue. We might reconsider this in future and if so we will inform you. Right now our priority is to create deb and rpm repositories common for all proton products.

Nevertheless, I opened internal issue (GODT-975) with these tasks:
* create tgz with vendor sources in CI
* add package metadata: .desktop, .plist, .aip
* add more build instructions about install from source

Even though we are not going to maintain Fedore/EPEL package we will try to make your life easier.

**Comment by dsommers** [comment]
I'm confused .... I presume you meant "we decided to **not** maintain Fedora / EPEL package", @cuthix.

But what does this even mean: "Right now our priority is to create deb and rpm repositories common for all proton products." ?  Is this just a status quo situation?  If so, then you have not fully grasped the challenges of .deb/.rpm packaging.

Also, the Fedora/EPEL packaging .... that's really not something which you (ProtonMail) need to do.  This is something the Fedora community typically does for you.

**Comment by AJCxZ0** [comment]
> I'm confused

I am also confused, but came here from the issue (#72) and thought that the details which @cuthix replaced such as "Fedore/EPEL package"[sic] were made with insufficient attention to the surrounding text, but looking more closely at the differences it's just conflicting.

It appears that the Proton folks don't quite understand how software is properly managed on Linux platforms, even after advice from users. At least it seems that Proton will release a useful tarball with which packagers can easily work.
