### ISSUE TITLE
Issues importing mails with Import/Export App

### ISSUE THREAD

**Issue by HyperCriSiS** [ProtonMail/proton-bridge#445]
I could not find the specific repo, is this the right place?

## Version Information
Import/Export App v1.3.3

## Detailed Description
On Windows 11 I want to import Mails to Proton which exported from Thunderbord as eml files.

**Many Mails can't be imported because of two different errors:**
failed to import: failed to parse message: failed to create new parser: message: malformed MIME header key
or
failed to import: failed to parse message: failed to create new parser: unexpected EOF

Mostly older mails are affected, but also all mails from Paypal for example.
Is there anything else I can provide to help fixing the issue?

Some mails which throw errors with the import app can be imported via drag and drop into the mailbox within Thunderbird.
But also there I have issues with many. 
Showing for example this error:
![D2bKXxCFBw](https://github.com/ProtonMail/proton-bridge/assets/11708192/38eeea93-08c4-4aeb-8214-9d9d3720420b)

The error report within import/export app could not be sent:
![proton-ie_d4WOkkGfFM](https://github.com/ProtonMail/proton-bridge/assets/11708192/33870454-3630-4614-b5f3-67d74a1c1c06)

Thanks 
Hyper

**Comment by LBeernaertProton** [comment]
Hey @HyperCriSiS , the import-export tool is considered EOL (end of life). It will not receive any more updates. 

For your importing needs, please use Bridge.

For exporting you can use the [new export tool](https://proton.me/support/proton-mail-export-tool).
