### ISSUE TITLE
Bridge transparent Window on Fedora 39 KDE Plasma / Wayland

### ISSUE THREAD

**Issue by Jiter** [ProtonMail/proton-bridge#448]
Proton Bridge opens with transparent/flickering window on Fedora 39, using Wayland display server and NVIDIA driver. Works fine with Xorg.

NVIDIA GeForce GTX 1070
NVIDIA 545.29.06  driver
Fedora Linux 39
64-bit
KDE-Plasma: 5.27.9
Wayland

## Expected Behavior

Proton Bridge window should display contents correctly.

## Current Behavior

Proton Bridge opens with transparent window and flickers.

![grafik](https://github.com/ProtonMail/proton-bridge/assets/13871427/e7ba0804-83f0-499d-87a3-6237edec65ae)

Contextmenu in the Task-Bar Works flawlessly.

![grafik](https://github.com/ProtonMail/proton-bridge/assets/13871427/0a1133a7-cfc6-4f3f-9037-17e521fd3648)

## Possible Solution

No idea. I tried starting with the `--software-renderer`-Flag. The behavior is the same.

## Steps to Reproduce

1.     Open application over CLI or Application-Menu.
2.     Window opens, and is transparent and flickers.

## Version Information

Version 3.8.1 (br-187)

## Context (Environment)

Stops me seeing settings from Proton Bridge.
Together with the issue of lost Settings/Vault at startup its unusable.

**Comment by LBeernaertProton** [comment]
Hey, just to confirm, did you start bridge as `protonmail-bridge  --software-renderer` when no other instances of bridge were running?

**Comment by Jiter** [comment]
> Hey, just to confirm, did you start bridge as `protonmail-bridge --software-renderer` when no other instances of bridge were running?

I checked now that no other Instance is running.
When I start `protonmail-bridge --software-renderer` now everything works as expected!

That are good news!

I now will start the Application with `--software-renderer` Argument.
