### ISSUE TITLE
Uninstalling Bridge on Windows does not remove Startup Program

### ISSUE THREAD

**Issue by WizardOfMenlo** [ProtonMail/proton-bridge#45]
When uninstalling ProtonMail Bridge on Windows 10, the Startup Item does not get completely removed. It now shows up as a generic Program, and examining the Command Line command it still is trying to run Desktop-Bridge.exe

## Expected Behavior

After removing the program, I think that the startup item should be removed as well, as otherwise it is quite hard to get rid of it (despite not being particularly impactful). 

## Current Behavior

The startup menu persists in the Startup tab of Task Manager (and a corresponding regedit key ```Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\StartupFolder``` which, after being deleted, pops up again on reboot)

## Steps to Reproduce

1. Install ProtonMail Bridge on Windows 10 (Respectively, 1.2.6 and Version 1909)
2. Ensure the run at Startup option is checked in Settings
3. Uninstall ProtonMail (right clicking in Start Menu)
4. Check Task Manager for a weird item that is still bound to ```Desktop-Bridge.exe``` (screenshot below)

## Context (Environment)

This just randonmly happened to me while cleaning up my PC.  It's probably just a small oversight in the uninstall code, and I have found a workaround, but felt it would be nice to let you guys know. 

## Detailed Description

Ensure that when uninstalling the Startup element is removed. 

## Workaround
As a workaround, the user can reinstall proton mail, uncheck the run at Startup option and then uninstall again. This cleans up everything very nicely. If this works in general it should be quite easy to implement this fix!

## Screenshot

![Capture](https://user-images.githubusercontent.com/9511741/81446453-338b6600-917b-11ea-9cdb-cdb9216c72c2.PNG)

**Comment by jameshoulahan** [comment]
Thanks for bringing this to our attention! We'll see what we can do to ensure the startup entry is removed too during uninstallation.

(Ref GODT-347)

**Comment by andrzejsza** [comment]
This has been fixed in 1.6.5 - let us know if otherwise ;-)
