### ISSUE TITLE
Failed to parse addresses prevents importing of emails

### ISSUE THREAD

**Issue by yu-tendo** [ProtonMail/proton-bridge#451]
## Description of the problem
The email cannot be imported with the Proton Mail Bridge due to a parsing error of the address fields. When moving the message (with Thunderbird), one of the following error messages is printed:

1. failed to retrieve addresses from literal:failed to parse addresses for 'To': [Error offset=8197]: expected ':' for group start: known recovered message, possible duplication. (see attached example, issue-1.txt)
2. failed to retreive addresses from literal:failed to parse addresses fo'Cc': [Error offset=98]: expected byte value 3f: known recovered message, possible duplication. (see attached example, issue-2.txt)
3. failed to retrieve addresses from literal:failed to parse addresses for 'Cc': [Error offset=45]: expected atext char for atom: known recovered message, possible duplication. (see attached example, issue-3.txt)
4. failed to retrieve addresses from literal:failed to parse addresses for 'To': [Error offset=45]: expected atext char for atom: known recovered message, possible duplication. (see attached example, issue-4.txt)

## Comment
I am not sure if it is possible to fix these issues, as it might be the case that the e-mails are simply faulty (i.e., the respective issue cannot be corrected automatically). However, identifying manually the faulty e-Mails while actually moving thousands of e-Mails is very time-consuming. Thus, I would expect that at least the email-moving process is not interrupted and the faulty emails are skipped. Assuming the bridge cannot handle the parsing issue, I suggest that a respective FAQ entry (or similar) is created covering an explanation of the issue and how to potentially manually fix this issue (otherwise users will keep opening new issues).

Related to Issue 2:
It seems to be valid to use the following format in the address field:
> =?utf-8?b?U3Ryw6FuZ8OpIE7DpG3DqQ==?= \<test@example.com\>

It seems the bridge does not support this format (=?charset?encoding?encoded-text?=) (It is not restricted to utf-8). 

## Version Information
Proton Mail Bridge v3.8.1 (br-187)
Thunderbird 115.6.0 (64-bit)
Microsoft Windows 10

## File Attachments
[issue-1.txt](https://github.com/ProtonMail/proton-bridge/files/13746518/issue-1.txt)
[issue-2.txt](https://github.com/ProtonMail/proton-bridge/files/13746519/issue-2.txt)
[issue-3.txt](https://github.com/ProtonMail/proton-bridge/files/13746516/issue-3.txt)
[issue-4.txt](https://github.com/ProtonMail/proton-bridge/files/13746517/issue-4.txt)

**Comment by LBeernaertProton** [comment]
Thanks for the detailed report. We will look into the first 2 issues. 

Regarding 3 & 4, it seems to be related to `addr1,,addr2`. Which is not a valid address list.

**Comment by LBeernaertProton** [comment]
Internally tracked as GODT-3179

**Comment by LBeernaertProton** [comment]
After discussing with my colleagues, it was agreed that at this point in time, we won't relax the parsing rules.
