### ISSUE TITLE
Unexpected behaviour when copying / deleting email

### ISSUE THREAD

**Issue by zwets** [ProtonMail/proton-bridge#456]
I occasionally send myself email, e.g. from my phone (with ProtonMail) so I can handle this on my laptop (with Thunderbird over Bridge). I recently noticed that when I then delete the message from my Sent mail (mainly because it stands out as it is marked "Unread"), it also disappears from my Inbox.

This is not what I would expect. I expect the messages in my Sent and Inbox folders to be **copies**, without spooky action at a distance deleting one when I delete the other. This is how every IMAP provider I know works.

This would still be true if there were only a single canonical copy of the message and 'Sent' and 'Inbox' were labels (rather than folders). Removing the 'Sent' label from a message shouldn't also remove the 'Inbox' label, nor should it delete the message.

Likely related: I regularly make for-the-record copies of emails I receive into an archive folder. Then, when I've handled the email in my Inbox, I delete it there. This works for every email account except Proton over Bridge. With Proton when I do "Copy To ..." in Thunderbird, then after a few moments, the original copy in my Inbox **disappears**.

This is not what I expect, and it caused me to lose email when I recently "copied" messages back from my archive folder to my inbox, thinking I had mistakenly done a "Move To". When I later deleted the copies from my inbox, little did I realise that I had just deleted the _only_ copies. 

I think this behaviour doesn't match any user's expectation of how mail folders work, nor does it match the behaviour of any IMAP provider I know. But most importantly, it goes counter to the widely held understanding of "making a copy", with possibly dire consequences.

---

PS: all this notwithstanding, I sincerely appreciate you and your colleagues' work on ProtonMail Bridge and the other Proton products. I'm a happy paying customer!

**Comment by LBeernaertProton** [comment]
Hey @zwets , unfortunately this is not a Bridge specific behavior. You can also reproduce this on other clients (web/mobile).

This is currently an API limitation. I have reached out to the respective colleagues.

**Comment by LBeernaertProton** [comment]
This seems to be by design. There's nothing we can change from a Bridge perspective.
