### ISSUE TITLE
version 3.8.2 rpm file | certificate issue

### ISSUE THREAD

**Issue by alexknop** [ProtonMail/proton-bridge#460]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

```
$sudo dnf install -y Downloads/protonmail-bridge-3.8.2-1.x86_64.rpm 
RPM: error: Verifying a signature using certificate D51E64D3E63EDC3EEF7864CEE2C75D68E6234B07 (Proton Technologies AG (ProtonMail Bridge developers) <bridge@protonmail.ch>):
RPM:   1. Certificiate E2C75D68E6234B07 invalid: certificate is not alive
RPM:       because: The primary key is not live
RPM:       because: Expired on 2024-02-02T13:40:50Z
RPM:   2. Key E2C75D68E6234B07 invalid: key is not alive
RPM:       because: The primary key is not live
RPM:       because: Expired on 2024-02-02T13:40:50Z
Error: Transaction test error:
  package protonmail-bridge-3.8.2-1.x86_64 does not verify: Header V4 RSA/SHA256 Signature, key ID e6234b07: NOTTRUSTED
```
## Expected Behavior
Install should succeed

## Steps to Reproduce
Install rpm file on a RedHat distro

## Version Information
3.8.2

## Context (Environment)
Fedora 39

**Comment by egitt** [comment]
I got the same issue on my system, too. Also Fedora 39, certificate is expired!

**Comment by SnailVendor** [comment]
Same issue for me, on Nobara 39 (fork of Fedora 39)

**Comment by LBeernaertProton** [comment]
We apologize for the inconvenience, we had to update our installer keys.  You will need to remove the old key from your system before you install the rpm.

Run this snippet to list the available keys:
```
rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'
```

Which should produce something such as:
```
gpg-pubkey-18b8e74c-62f2920f	Fedora (39) <fedora-39-primary@fedoraproject.org> public key
gpg-pubkey-xxxxxxxx-xxxxxxx	Proton Technologies AG (ProtonMail Bridge developers) <bridge@protonmail.ch> public key
`````

Now run the following command to remove the key:

```
sudo rpm -e gpg-pubkey-xxxxxxxx-xxxxxxx	
```

Confirm the key has been removed by running the list command again and you should now be able to install the RPM file.

**Comment by alexknop** [comment]
Yes, that worked. Thank you
