### ISSUE TITLE
Include vendored dependencies in the release tarball

### ISSUE THREAD

**Issue by MatMaul** [ProtonMail/proton-bridge#47]
To ease packaging, would it be possible to include the vendored dependencies in a tarball when doing a release ? Managing all those dependencies by hand is a nightmare.

cf https://github.com/flathub/ch.protonmail.protonmail-bridge/issues/28.

Thanks !

**Comment by cuthix** [comment]
I am not familiar with flatpack installation procedure, can you describe why is it needed to manage dependency by hand?

We are managing packages using go.mod. Following [BUILDS.md](https://github.com/ProtonMail/proton-bridge/blob/master/BUILDS.md) instructions should be enough to build and create package.

**Comment by MatMaul** [comment]
Network access is not available during the build on purpose, for reproducibility (I think it's the case for a lot of build systems no ?). Which means we would need to provide the vendor deps in a separate package, or define them one by one manually.

**Comment by MatMaul** [comment]
Basically there is 2 phases, one fetching the resources with network access, and then the actual build without it.

**Comment by A6GibKm** [comment]
Rpm builds for fedora are also built without network.

**Comment by cuthix** [comment]
As you might see in #72 there is internal ticket for this issue GODT-975
