### ISSUE TITLE
Proton Bridge opens from tray whenever a notification is opened.

### ISSUE THREAD

**Issue by SODDINGIT** [ProtonMail/proton-bridge#473]
Whenever I click on a notification in the panel, Proton Bridge pops up as a windows instead of staying minimized. The notifications have nothing to do with Proton Bridge (for example Signal messages or calendar reminders).

## Expected Behavior
Proton Bridge should remain minimized at all times.

## Current Behavior
Proton Bridge pops up and takes the focus.

## Steps to Reproduce
1. Start Proton Bridge
2. Minimize Proton Bridge
3. Receive Signal message
4. Click on Signal's notification

## Version Information
3.3.0 br 149
Linux Mint 2.1
Kernel 6.5.0-28

**Comment by LBeernaertProton** [comment]
This issue has been fixed in later version. The current version is out of date. 

If the bridge does not auto update, please install the latest version manually, as there was an issue with our key signing.
