### ISSUE TITLE
Sending from aliases when in combined inbox mode

### ISSUE THREAD

**Issue by nicksellen** [ProtonMail/proton-bridge#48]
I have various address aliases set up, but cannot send from them when in combined inbox mode. For me they are not meant as seperate mailboxes, so the split address mode isn't useful.

## Expected Behavior

When setting from address in my email client to a valid configured alias, the email sent out will have it's from header set to that value.

## Current Behavior

The email sent out has the from header from the main address.

## Possible Solution

Instead of setting the from header to be the main address, use the from header if it's set to a valid alias.

## Steps to Reproduce

1. send an email with a from header specified that is different to the main email address:

```
msmtp -a protonmail nstest@karrot.world <<EOF
To: nstest@karrot.world
From: talktome@nicksellen.co.uk
Subject: test4

test4
EOF
```

2. See headers in the email sent are different (I snipped the other headers):

```
To: nstest@karrot.world
From: hello@nicksellen.co.uk
Reply-To: hello@nicksellen.co.uk
Subject: test4

test4
```

## Context (Environment)

I use a terminal-based email setup with protonmail bridge, isync (mbsync), notmuch, alot, msmtp. I have a custom domain with various wildcard aliases that I want to send from. They are not supposed to be mailboxes in themselves though.

**Comment by horejsek** [comment]
Thanks for the report! We will look into it.

**Comment by Pete-Hamlin** [comment]
Just wondering, is there any movement on this one?

This is also an issue for me,as I have the same use case as above, and as a result am unable to reply to any email with anything other than the main email address when using combined mode.

This essentially means I can only use the Bridge as a means to receive email, but still have to use the web app for sending emails from my other aliases (which is about 95% of emails I send).

**Comment by araspik** [comment]
This is a necessary feature.

@Pete-Hamlin you may be able to use the split address mode and then combine the mailboxes together (e.g. in isync get all the mails dropped into the same maildir folder).

**Comment by andrzejsza** [comment]
this should be working fine now (1.5.6). the exception is Outlook, which does not support this and there is not much we can do about it at this stage.
