### ISSUE TITLE
Transparent GUI Window - (Plasma 6 - QT 6.7 - Wayland)

### ISSUE THREAD

**Issue by mrdev023** [ProtonMail/proton-bridge#481]
When i run proton-bridge on wayland i have a tranparent window

![bug_protonmail](https://github.com/ProtonMail/proton-bridge/assets/11292703/10075ce6-5442-4c34-b14c-44ed470583dc)

## Steps to Reproduce
1. flatpak install ch.protonmail.protonmail-bridge (3.11.1)
2. flatpak run ch.protonmail.protonmail-bridge (On wayland)

## Version Information

Operating System: NixOS 24.11
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.1
Kernel Version: 6.9.3-zen1 (64-bit)
Graphics Platform: Wayland
Processors: 64 × AMD Ryzen Threadripper 2990WX 32-Core Processor
Memory: 31.2 Gio of RAM
Graphics Processor: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
Proton bridge : 3.11.1

**Comment by theRealBassist** [comment]
I have the exact same issue. I've also tried installing the .deb package directly from the website, but it still runs into the same problem. 

I have also found that it leaves processes behind that will never close themselves.

**Comment by ginolegigot** [comment]
Same issue here:
Wayland
![image](https://github.com/ProtonMail/proton-bridge/assets/58557862/64fc2006-e67c-4ec2-ae69-ca70a770af99)

**Comment by ElectroNafta** [comment]
Hey guys, this is the same issue as in #448. 

As far as I remember its an Nvidia driver issue <-> Wayland <-> Qt. 

Could you guys try starting bridge with the following flag attached `protonmail-bridge  --software-renderer`. 

It should fix your issues.

**Comment by ginolegigot** [comment]
yep issue fixed thanks!
