### ISSUE TITLE
[Arch linux] CLI not displaying anything else than "qt.qpa.xcb: could not connect to display"

### ISSUE THREAD

**Issue by pierrepaap** [ProtonMail/proton-bridge#504]
Trying to use the bridge to forward system emails to my proton.me address from CLI using a non-interactive bridge
After installign the AUR (PKGBUILD based) package, nothing gets displayed beside the display error above
my `.forward `file contains my proton email address.

## Expected Behavior
```
protonmail-bridge -h
protonmail-bridge --help
protonmail-bridge -v
protonmail-bridge --version
protonmail-bridge -c
protonmail-bridge --cli
```
should be able to display something without any video driver being configured
A man page should be available somewhere to know the switched available

## Current Behavior
I always get the same output
```
$ protonmail-bridge -h
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: vkkhrdisplay, xcb, minimalegl, minimal, eglfs, linuxfb, offscreen, vnc.

Aborted (core dumped)
```

## Version Information
according to https://archlinux.org/packages/extra/x86_64/protonmail-bridge/
3.14.0-8

## Context (Environment)
Arch Linux (LTS kernel)

strace protonmail-bridge -c 2> strace1.txt
strace protonmail-bridge --cli 2> strace2.txt

[strace1.txt](https://github.com/user-attachments/files/17790738/strace1.txt)
[strace2.txt](https://github.com/user-attachments/files/17790739/strace2.txt)

**Comment by ElectroNafta** [comment]
Hey @pierrepaap, you're running the bridge launcher which ends up invoking the GUI. 

You should be able to start bridge via `./usr/lib/protonmail/bridge/bridge -c`
