### ISSUE TITLE
Error appending message: mime: invalid media parameter

### ISSUE THREAD

**Issue by JulienPalard** [ProtonMail/proton-bridge#51]
I'm using Evolution 3.36.2-1, I'm having two accounts (a local Maildir, and proton-bridge), and I'm trying to move a mail from my Maildir to protonmail.

My message is a `multipart/mixed`, the attachment looks like this in the eml:

```
--047d7bdcab7c6efaf604f6d9c256
Content-Type: application/octet-stream; name=copie CE2
Content-Disposition: attachment; filename=copie CE2
Content-Transfer-Encoding: base64
X-Attachment-Id: f_htx17pui0

[the base64 blob, redacted for privacy]
```

It's advised as application/octet-stream with a name without extension, but it's in fact a proper PDF file.

## Expected Behavior

I expect protonmail-bridge to accept the message, even if it does not recognize the attachment.

## Current Behavior

Getting an `invalid media parameter` error, but I see nothing in the logs, and evolution don't give me more details.

**Comment by skooda** [comment]
Hi Julien,

Problem is in `Content-Type: application/octet-stream; name=copie CE2`, respectively in the space used in token: `copie CE2`.

According to [RFC-2045](https://tools.ietf.org/html/rfc2045#page-31) it should be enclosed in quotes like this:
`Content-Type: application/octet-stream; name="copie CE2"`.

Hope this helps.

**Comment by JulienPalard** [comment]
@skooda Looks like Evolution ignores the trailing "CE2", I don't know whats the best (ignoring or accepting with a modification).

Explicit is better: I'm OK to say the current behavior is the good one (refusing the message instead of silently accepting it).
Explicit is better: The error, "invalid media parameter" could probably be enhanced a bit: it's obvious for an RFC reader than the `media parameter` is a part of the `Content-Type` header, but not for anyone. An error like:

    Error appending message "À imprimer": An error occured parsing the Content-Type header: invalid media parameter.

would be a bit more helpfull, mainly by giving the subject of the email, which is really helpfull when appending more than one message.

@skooda thanks!

**Comment by skooda** [comment]
That seams legit to me. I will create an internal feature request for that.

Thanks a lot!
