### ISSUE TITLE
support for Alpine/Aerc

### ISSUE THREAD

**Issue by sbinet** [ProtonMail/proton-bridge#58]
I am trying to make [alpine](http://alpine.x10host.com/alpine/) or [aerc](https://aerc-mail.org/) work with proton-bridge.
but both of them fail to display messages (they can fetch emails from the local IMAP server of proton-bridge, though).

Alpine fails with the most informative errors.

- when fetching new messages:
```
{localhost/novalidate-cert:1143/user=me@pm.me/tls}INBOX: Unexpected untagged message: FLAGS
```

- when opening a message:
```
 Unknown body disposition: "inline" NIL NIL) FLAGS (\Seen nonjunk))
[list message build: wrong section 1]
[Message size does not match expected size, continuing...]
```

could this be fixed?
anything I could do on my end to help with that?

**Comment by sbinet** [comment]
FYI, here is also some additional infos:
- https://todo.sr.ht/~sircmpwn/aerc2/343

(it seems hydroxide is handling this better)

**Comment by skooda** [comment]
Hi, thanks for telling us.

Unfortunately, neither AERC nor Alpine are among the supported clients, and although we intend to expand the list of supported clients in the near future, I don't think they will be among them.

by the way, [this patch](https://lists.sr.ht/%7Esircmpwn/aerc/%3C20200619160653.255355-1-reto%40labrat.space%3E) for [AERC](https://git.sr.ht/~sircmpwn/aerc) should be usefull.

**Comment by nfraprado** [comment]
I am currently using aerc with protonmail-bridge and everything works. The only thing I needed to do was to add protonmail's self-signed certificate as a trusted certificate as shown [in this blog post](https://iptq.io/setup/command-line-email-with-aerc/).
There's the occasional (very frequently actually) aerc crash with a segmentation fault, but it may be aerc's fault. I haven't investigated further.
