### ISSUE TITLE
Improve building information - need to build QT for golang

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#6]
You definitely need something like:

`export GO111MODULE=off; go get -v github.com/therecipe/qt/cmd/... && $(go env GOPATH)/bin/qtsetup test && $(go env GOPATH)/bin/qtsetup -test=false`

**Comment by jameshoulahan** [comment]
Simply doing `make build` should pull in and set up the required dependencies (including `qtdeploy`). Please ensure `~/go/bin` (or similar) is in your path. There should be no need for an explicit `qtsetup` call.

**Comment by omicron-b** [comment]
I have the same issue as #7 
Debian Testing
```
$ which go
/usr/bin/go
```

**Comment by cuthix** [comment]
I opened PR, can you check it is working for you? 

The setup instructions simply links to therecipe because keeping all the variations in here would be too crowded.

**Comment by omicron-b** [comment]
Thank you, it works now, but I needed to revert line 64 back to master
Until that, it was:
```
mv deploy cmd/Desktop-Bridge
rm -f linux main.go
rm: cannot remove 'linux': Is a directory
make: *** [Makefile:64: cmd/Desktop-Bridge/deploy/linux/proton-bridge] Error 1
```

**Comment by jameshoulahan** [comment]
Going back to the original comment by @exander77 , could you please explain why we need something like you suggested? Why doesn't `make build` (which does `go get` the necessary qt dependencies) suffice for you?

Or if your issue is resolved by my first reply, I'd like to close this issue.
