### ISSUE TITLE
Missing documentation for build dependency libsecret-1

### ISSUE THREAD

**Issue by ViRb3** [ProtonMail/proton-bridge#60]
The build documentation should mention that `libsecret-1` is required. Installation commands for reference:
- Debian/Ubuntu: `sudo apt-get install libsecret-1-dev`
- Red Hat-based: `sudo yum install libsecret-devel`
- Arch Linux: `sudo pacman -S libsecret`

**Comment by horejsek** [comment]
Thank you for your feedback. We have it ready and will be here soon.

https://github.com/ProtonMail/proton-bridge/pull/12
