### ISSUE TITLE
IMAP for the Archive folder is excruciatingly slow

### ISSUE THREAD

**Issue by elshize** [ProtonMail/proton-bridge#61]
I use `mbsync` (from isync 1.3.2 package) to sync the IMAP folders on linux. I use the config below. When the "Archive" folder is included in the config as below, it currently takes about 7 minutes to sync. Without the archive, it takes a few seconds.

As comparison, my gmail mailbox (including the all mail folder) takes about 2 seconds if there're no emails to sync. I use the same config for gmail except authentication and names of some folders.

My protonmail bridge version is 1.2.7.

```
IMAPAccount proton
SSLType None
Host 127.0.0.1
Port 1143
User my_user_name@protonmail.com
PassCmd "<pass command>"

MaildirStore proton-local
Path ~/.mail/proton/
Inbox ~/.mail/proton/Inbox
Subfolders Verbatim

IMAPStore proton-remote
Account proton

Channel sync-proton-default
Master :proton-remote:
Slave :proton-local:
Patterns "INBOX"

Channel sync-proton-archive
Master :proton-remote:"Archive"
Slave :proton-local:archive
Create Slave

Channel sync-proton-sent
Master :proton-remote:"Sent"
Slave :proton-local:sent
Create Slave

Channel sync-proton-drafts
Master :proton-remote:"Drafts"
Slave :proton-local:drafts
Create Slave

Channel sync-proton-trash
Master :proton-remote:"Trash"
Slave :proton-local:trash
Create Slave

Group proton
Channel sync-proton-default
Channel sync-proton-sent
Channel sync-proton-drafts
Channel sync-proton-archive
Channel sync-proton-trash
```

## Expected Behavior
I expect it to take much less to sync archive folder. Certainly not as long as it takes.

## Current Behavior
Currently it takes about 7 minutes in my case. This is in a situation when there're no emails to sync, that is, no changes on the remote nor the local folders.

## Possible Solution
I couldn't find a solution. A possible workaround is to exclude archive folder from the regularly scheduled updates, and sync archive separately, less frequently.

## Steps to Reproduce
1. Run protonmail-bridge and log in.
2. Install `mbsync` tool (on Artch/Manjaro, it is `isync` package.
3. Set up `~/.mbsyncrc` config file according to the listing above, changing necessary credentials.
4. Run `mbsync proton`.

## Context (Environment)
I use a systemd timer and service to sync mail periodically. The service also triggers [`notmuch`](https://notmuchmail.org/) mail indexer. I then use a frontend to the database such as [Astroid](https://github.com/astroidmail/astroid) or [alot](https://github.com/pazz/alot).

**Comment by jameshoulahan** [comment]
Thanks for the feedback. Could you describe roughly the size of your Archive mailbox? Is the symptom the same when you include the "All Mail" mailbox?

**Comment by elshize** [comment]
Thanks for a quick response.

My archive has 362 emails and takes 72 MB on disk. The situation is the same when I try All Mail instead. What I'm noticing is that it takes about the same time the first time I sync as any consecutive syncs. As if it copies all mail each time. But the files on disk in maildir don't get overwritten, so I don't know what is happening.

What would your expectation be for a mailbox of my size to sync? It's the smallest of my inboxes by a long margin, yet is by far the slowest one.

Let me know if there are any other question I could answer.

**Comment by jameshoulahan** [comment]
Off the top of my head, I'm also not too sure why these mailboxes in particular behave poorly. We'll have to investigate. Thanks for the report.

**Comment by dkabus** [comment]
I can confirm this. I just reinitialised my mail directory with [`mbsync`/`isync`](https://isync.sourceforge.io/mbsync.html). This "fresh" local copy synchronises very quickly using `mbsync`.

However, as soon as I move an email from Inbox to Archive, it will be redownloaded anew every time I sync my mails after that. Same for mails moved to Trash, other dirs, etc. On sync, I get a warning like:
`Warning: lost track of 35 pushed message(s)`

In those dirs, there will always be two copies of those emails I moved there.

It seems like there is an issue with identifying what happened to the moved emails, as some IDs change. Comparing two emails which should be identical (one moved by my mail client locally and one downloaded on sync), we see `diff ~/.local/share/mail/proton/Archive/cur/1603482406.348448_1.mypc,U=1289:2,RS
~/.local/share/mail/proton/Archive/cur/1603480712.R15262745458573712749.mypc,U=1281:2,RS`:
```
41c41,42
< X-TUID: fATo5yIuVO7J
---
> X-TUID: LOIRLyuy5zFl
> Content-Length: 10600
```

I hope this helps, to find the bug! Id really appreciate it if this would get fixed soon.

**Comment by dkabus** [comment]
The debug option `mbsync -D -a` gives a little more insight into the issue.

For each of the mails, it pushes my local changes first:
```
M: Called get_memory_usage, ret=0
pushing message 1220, TUID cfU82ElOL++U
S: [ 15] Enter fetch_msg, uid=1220, want_flags=no, want_date=no
S: [ 15] Callback enter fetch_msg, flags=S, date=0, size=6828
S: Called get_caps, ret=0
M: Called get_caps, ret=0x3
M: [ 16] Enter store_msg, flags=S, date=0, size=6921, to_trash=no
M: >>> 8 APPEND "Archive" (\Seen) {6921+}
M: [ 16] Leave store_msg
S: [ 15] Callback leave fetch_msg
S: [ 15] Leave fetch_msg
```

A little bit later, it complains that the TUID cannot be matched:
```
  pair(0,1220): lookup master, TUID cfU82ElOL++U
  -> TUID lost
```

**Comment by pbeliveau** [comment]
> However, as soon as I move an email from Inbox to Archive, it will be redownloaded anew every time I sync my mails after that. Same for mails moved to Trash, other dirs, etc. On sync, I get a warning like:
> `Warning: lost track of 35 pushed message(s)`
> 
> In those dirs, there will always be two copies of those emails I moved there.

For what it's worth, exact same issue.
Inbox to archive folder -> "Cannot find UID" in logs -> Sync emails -- the bridge brings back emails like before moving them. I now get the same warning again and again on sync:
```
Warning: lost track of 2 pushed message(s)
```

**Comment by andrzejsza** [comment]
@elshize @dkabus is this still and issue for you? we've implemented UID Expunge in the meantime and done a few other changes to Bridge-IMAP interactions, curious to hear if you've seen any changes.

**Comment by elshize** [comment]
Hi @andrzejsza I haven't been using the bridge lately, but I'll try to find some time to test it soon.

**Comment by ploum** [comment]
For me, this issue has clearly been solved for a few months.

**Comment by elshize** [comment]
Looks like it's solved for me as well. Thanks!

**Comment by andrzejsza** [comment]
glad to hear!
