### ISSUE TITLE
All Mail should not contain Trash and Spam

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#63]
Already reported to support and bridge. But the problem is still there.

It breaks the expectation of the mail clients by lying to them. When you remove emails from All Mail, it returns operation successfully proceeded, but the mail was not actually removed and pops back again. This leads up to the complete failure of your mail client's profile.

**Comment by horejsek** [comment]
See https://github.com/ProtonMail/proton-bridge/issues/62#issuecomment-669016059

**Comment by exander77** [comment]
@horejsek @bartbutler

> Spam and Trash emails are now automatically excluded from All Mail. [Change setting](https://account.proton.me/u/0/mail/general#messages)

Enough said.

**Comment by bartbutler** [comment]
We got it done. But those who want it can toggle the old behavior as well.

**Comment by exander77** [comment]
> We got it done. But those who want it can toggle the old behavior as well.

Yes, I am glad you finally came to Jesus! :) Sensible to enable this by default as the previous behavior breaks not only standard workflows, e-mail clients, but also expectations of new users (and sometimes even the seasoned ones).
