### ISSUE TITLE
Proton-bridge ignores GNOME proxy settings

### ISSUE THREAD

**Issue by Mr-Sheep** [ProtonMail/proton-bridge#64]
I noticed that when proton bridge is executed via `protonmail-bridge.desktop` entry, GNOME proxy settings are ignored by bridge. I suspect this is caused by the ignorance of org.gnome.proxy settings
But I can run bridge behind proxy with `http_proxy` in terminal

## Expected Behavior

bridge does check GNOMES proxy setting OR add proxy setting in bridge

## Current Behavior
    It's works with http_proxy when executed via shell
    It does not work via the protonmail-bridge.desktop file

## Possible Solution

GNOME does not set http_proxy env variables for programs run directly via .desktop files. So I guess adding a proxy setting in bridge would be helpful?

## Steps to Reproduce

fireup bridge using .dekstop entry

## Env

Ubuntu 20.04 LTS
ProtonMail Bridge v1.2.7

**Comment by Mr-Sheep** [comment]
I did find a temporary work around through a "shell wrapper"
https://gist.github.com/JPvRiel/4e3f6f055b4ac9c31a302450bfdf0758

**Comment by jameshoulahan** [comment]
Hi and thanks for the feature suggestion.

Bridge uses golang's [http.ProxyFromEnvironment](https://golang.org/pkg/net/http/#ProxyFromEnvironment), which, as you can see in the linked godoc, only responds to `the environment variables HTTP_PROXY, HTTPS_PROXY and NO_PROXY (or the lowercase versions thereof)`. Bridge can therefore be configured to run via a proxy but that can currently only be done via those environment variables.

Indeed, having a more easy to use proxy setting would be nice. We will take this into consideration.

**Comment by andrzejsza** [comment]
we didn't manage to look into this for more than a year and have no room anytime soon. we'll keep it in mind but I'll close the issue.
