### ISSUE TITLE
GUI improvement

### ISSUE THREAD

**Issue by Spixmaster** [ProtonMail/proton-bridge#65]
**My computer**
Operating System: Arch Linux
KDE Plasma Version: 5.19.4
KDE Frameworks Version: 5.72.0
Qt Version: 5.15.0
Kernel Version: 5.7.12-arch1-1
OS Type: 64-bit
Processors: 8 × Intel® Core™ i5-8265U CPU @ 1.60GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
ProtonMail Bridge v1.2.7

**Suggestion**
For me, the desktop environment settings like window decorations and swirling windows when moving them are completely ignored by ProtonMail bridge. It would be a great update if those setting from the OS would be considered by the applications.

**Comment by horejsek** [comment]
Thanks for the feedback. You could probably notice upcoming new design of all Proton services and Bridge will get it too. We will take your suggestion into consideration for new UI and UX.

**Comment by Spixmaster** [comment]
@horejsek One last thing that I noticed the window always open in the upper left corner after it was minimized. That is a little bit annoying. No other application does that. I thank you for reply.

**Comment by andrzejsza** [comment]
@Spixmaster we're in a process of a larger redesign and this issues will also be included.
