### ISSUE TITLE
No bridge version when compiling v1.3.3

### ISSUE THREAD

**Issue by nfraprado** [ProtonMail/proton-bridge#67]
When compiling from source from the .tar.gz archive from the 1.3.2 and 1.3.3 tags, the app doesn't have a valid version, since the version is obtained in the makefile from a git command, and the archive isn't a git repository.
This makes it unable to login and gives the error "Invalid app version".

## Expected Behavior

The app should have a valid version.

## Current Behavior

The app has an empty version, "v-git".

## Possible Solution

Either declare the version statically in the Makefile as it was on 1.2.8 and earlier, or make the tag archive also contain the .git folder.

## Steps to Reproduce

1. Download the source code archive from the 1.3.3 tag https://github.com/ProtonMail/proton-bridge/releases/tag/v1.3.3
2. Compile
3. Open the bridge
4. Try to login

## Context (Environment)

I'm compiling this in Archlinux 5.7.10-arch1-1.

**Comment by sergeyklay** [comment]
Just compiled from source.

```bash
$ proton-bridge --version
INFO[0000] Run app                                       appLong="Protonmail Bridge" appShort=bridge args="[proton-bridge --version]" build="2020-08-12T18:28:44+0300" pkg=main revision=01a8c9e9d7 runtime=linux version=v1.3.3-git
Protonmail Bridge version v1.3.3-git (01a8c9e9d7) 2020-08-12T18:28:44+0300
```

Note `v1.3.3-git`, but GUI says `vv1.3.3-git` (`vv` twice):
![image](https://user-images.githubusercontent.com/1256298/90036527-d3e9ad00-dccb-11ea-88bb-479aab12482b.png)

---

Steps to reproduce:

1. Clone repo
2. Checkout to tag: `git checkout v1.3.3`
3. Make: `make build`
4. Run: `make run`

**Comment by nfraprado** [comment]
Yes @sergeyklay , since you cloned the entire repo and then checked out to the v1.3.3 tag with git it works, since then the folder is a git repo.
The issue is compiling from the source included in the .tar.gz archive in the v1.3.3 tag: https://github.com/ProtonMail/proton-bridge/archive/v1.3.3.tar.gz .

**Comment by horejsek** [comment]
Hi, thanks for the report. We forget to change the version in Makefile few times so we decided to try doing it automatically by reading git tags. We will check out what we can do about it. As a workaround, you can clone the whole repository for now.

**Comment by sergeyklay** [comment]
@horejsek How about `vv` in GUI? :)

**Comment by jameshoulahan** [comment]
Issue should be resolved now; the makefile specifies the exact version again.
