### ISSUE TITLE
qtdeploy: Command not found despite having QT installed

### ISSUE THREAD

**Issue by newincpp** [ProtonMail/proton-bridge#7]
Hi,
I just cloned the repo and `make build` and I get this:
```
/usr/bin/go
go install -v -tags=no_env github.com/therecipe/qt/cmd/...
go mod vendor
ln -sf /home/newin/project/proton-bridge/vendor-cache/github.com/therecipe/env_linux_amd64_513 vendor/github.com/therecipe/env_linux_amd64_513
rm -rf deploy linux cmd/Desktop-Bridge/deploy
cp cmd/Desktop-Bridge/main.go .
qtdeploy -tags='pmapi_prod' -ldflags '-X main.Version=1.2.6-git -X main.Revision=409abba995 -X main.BuildTime=2020-04-16T00:03:59+0200' build desktop
make: qtdeploy: Command not found
make: *** [Makefile:62: cmd/Desktop-Bridge/deploy/linux/proton-bridge] Error 127
```
Even if it's not listed in the dependancies I have QT (5.14.2) installed on my machine but I don't have any `qtdeploy`. Also surprisingly I don't see any mention of a `qtdeploy` in the QT documentation. What am I missing ?

**Comment by exander77** [comment]
I already described the solution to this problem here: https://github.com/ProtonMail/proton-bridge/issues/6

I already built and run it.

**Comment by newincpp** [comment]
The command you proposed in your thread failed for some link error but I managed to get a qtdeploy anyway which made `make build` work. So I guess it's (kinda) solved.

**Comment by dhammel** [comment]
> The command you proposed in your thread failed for some link error but I managed to get a qtdeploy anyway which made `make build` work. So I guess it's (kinda) solved.

Can you explain how you got qtdeploy? I'm having the same issue as you did, and the command that exander77 posted was successful for me, but didn't resolve the issue (It was only successful, if I had qt5-default installed).

**Comment by jameshoulahan** [comment]
For the sake of completeness, `make build` should pull in and build all necessary Qt binaries including `qtdeploy`; they will be installed to `$(go env GOPATH)/bin` (by default, `~/go/bin`). To ensure `make build` works correctly, please ensure this is on your path.

E.g. this should build without issues:
```
PATH=$(go env GOPATH)/bin:$PATH make build
```
