### ISSUE TITLE
Import/Export Tool - bug reporting

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#70]
Where to report bugs to Import/Export Tool?

**Comment by horejsek** [comment]
Bridge and Import-Export apps are developed together, so this issue tracker is proper place. Note that issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or Import-Export app or contact bridge@protonmail.ch.
