### ISSUE TITLE
Choose between password managers (gnome-keyring and pass)

### ISSUE THREAD

**Issue by dkabus** [ProtonMail/proton-bridge#77]
I have both `gnome-keyring` and `pass` installed on my device.
ProtonMail Bridge automatically selected `pass` without giving any feedback.
I only found out about this when I looked at my `password-store` dir.

## Expected Behavior / Possible Solution
When logging in to a new account, Bridge should ask which password manager to use.
When selecting `pass`, it should tell me that its going to add entries that dynamically change.
It should suggest to gitignore them to prevent them from being pushed to another device.
Also it should give a bit more information about what is being done in the background.
See also this issue: https://github.com/ProtonMail/proton-bridge/issues/31

## Current Behavior
Magic happens in the background, everything works, but the user does not have a clue what happened and where the credentials are stored. The user is surprised by new entries in their password manager.

## Steps to Reproduce
1. Log in on Bridge on Linux with multiple password managers installed.
2. `pass ls`

## Context (Environment)
- Arch Linux
- Installed relevant packages: `gnome-keyring`, `pass`, `gpg`, `protonmail-bridge-bin`

**Comment by skooda** [comment]
Thank you for suggestion.

It definitely makes sense for the user to choose which keyring should bridge use.

I created an internal ticket and it should get into one of the future versions.

**Comment by TheLostWanderer** [comment]
Hi

If you could add `kdewallet` to the list of supported keyring, that would be great! At the moment, `protonmail-bridge` is the only program on my system using `gnome-keyring`.

**Comment by andrzejsza** [comment]
this is now done (from the early 1.6.5). as for kwallet, we will try to look into this separately in the future.

**Comment by dsommers** [comment]
Can you get the git repo pushed out, so we can start testing it?  Currently 

> this is now done (from the early 1.6.5). as for kwallet, we will try to look into this separately in the future.

So, how do we configure which backend to use?  I tried building a non-gui 1.6.5 from git, but I don't see any options for that.

**Comment by andrzejsza** [comment]
yes, this feature is only supported in gui at this stage. you can just edit the config file 
`~/.config/protonmail/bridge/prefs.conf`
where you'll find
`preferred_keychain`
and you can choose between
`pass-app
gnome-keyring`
