### ISSUE TITLE
Crash while using import-export mail app

### ISSUE THREAD

**Issue by dz0ny** [ProtonMail/proton-bridge#78]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

## Expected Behavior

I can run the app.

## Current Behavior

Crash on startup.

## Steps to Reproduce
<pre><font color="#6AB017"><b>➜</b></font><b> </b><font color="#005FD7">protonmail-import-export-app</font> 
<font color="#2AA7E7">INFO</font>[0000] Run app                                       <font color="#2AA7E7">appName</font>=&quot;ProtonMail Import-Export&quot; <font color="#2AA7E7">args</font>=&quot;[protonmail-import-export-app]&quot; <font color="#2AA7E7">build</font>=&quot;2020-09-09T17:33:13+0200&quot; <font color="#2AA7E7">pkg</font>=cmd <font color="#2AA7E7">revision</font>=bfdfc81d65 <font color="#2AA7E7">runtime</font>=linux <font color="#2AA7E7">version</font>=1.0.0
SIGABRT: abort
PC=0x7fa6a9a8418b m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x10882b0, 0xc0004d8cf0, 0x1)
	runtime/cgocall.go:128 +0x5b fp=0xc0004d8cc0 sp=0xc0004d8c88 pc=0x51575b
github.com/therecipe/qt/gui._Cfunc_QGuiApplication_QGuiApplication_Exec(0xc000000000)
	_cgo_gotypes.go:1498 +0x49 fp=0xc0004d8cf0 sp=0xc0004d8cc0 pc=0xd5e149
github.com/therecipe/qt/gui.QGuiApplication_Exec(...)
	github.com/therecipe/qt@v0.0.0-20200701200531-7f61353ee73e/gui/gui-minimal.go:1737
github.com/ProtonMail/proton-bridge/internal/frontend/qt-ie.(*FrontendQt).QtExecute(0xc000461200, 0x139c0a0, 0xc000461200, 0xc000461200)
	github.com/ProtonMail/proton-bridge@/internal/frontend/qt-ie/frontend.go:224 +0x161 fp=0xc0004d8d88 sp=0xc0004d8cf0 pc=0xeebd01
github.com/ProtonMail/proton-bridge/internal/frontend/qt-ie.(*FrontendQt).Loop(0xc000461200, 0x0, 0x0, 0x1, 0x1)
	github.com/ProtonMail/proton-bridge@/internal/frontend/qt-ie/frontend.go:117 +0x6e fp=0xc0004d8db8 sp=0xc0004d8d88 pc=0xeeae3e
main.run(0xc00032e160, 0x0, 0xc0001e02e0)
	github.com/ProtonMail/proton-bridge@/main.go:151 +0xef2 fp=0xc0004d91e0 sp=0xc0004d8db8 pc=0xfd2e02
github.com/urfave/cli.HandleAction(0x117db80, 0x13a0680, 0xc00032e160, 0xc00032e160, 0x0)
	github.com/urfave/cli@v1.22.4/app.go:526 +0xbe fp=0xc0004d9208 sp=0xc0004d91e0 pc=0x8e5c2e
github.com/urfave/cli.(*App).Run(0xc0002d8380, 0xc0000321e0, 0x1, 0x1, 0x0, 0x0)
	github.com/urfave/cli@v1.22.4/app.go:288 +0x5f8 fp=0xc0004d9550 sp=0xc0004d9208 pc=0x8e3b88
github.com/ProtonMail/proton-bridge/internal/cmd.Main(0x1302319, 0x18, 0x130f03c, 0x1c, 0x0, 0x0, 0x0, 0x13a0680)
	github.com/ProtonMail/proton-bridge@/internal/cmd/main.go:73 +0x919 fp=0xc0004d9f10 sp=0xc0004d9550 pc=0xfd0689
main.main()
	github.com/ProtonMail/proton-bridge@/main.go:48 +0x68 fp=0xc0004d9f60 sp=0xc0004d9f10 pc=0xfd1ef8
runtime.main()
	runtime/proc.go:203 +0x21e fp=0xc0004d9fe0 sp=0xc0004d9f60 pc=0x5433ee
runtime.goexit()
	runtime/asm_amd64.s:1357 +0x1 fp=0xc0004d9fe8 sp=0xc0004d9fe0 pc=0x56fae1

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
	runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	os/signal/signal_unix.go:29 +0x41

goroutine 38 [sleep]:
runtime.goparkunlock(...)
	runtime/proc.go:310
time.Sleep(0x6fc23ac00)
	runtime/time.go:105 +0x157
github.com/ProtonMail/proton-bridge/pkg/config.watchLogFileSize.func1(0xc00003cff0, 0x2f, 0xc000326400, 0x11)
	github.com/ProtonMail/proton-bridge@/pkg/config/logs.go:159 +0x30
created by github.com/ProtonMail/proton-bridge/pkg/config.watchLogFileSize
	github.com/ProtonMail/proton-bridge@/pkg/config/logs.go:153 +0x5d

goroutine 39 [chan receive]:
github.com/ProtonMail/proton-bridge/pkg/pmapi.(*ClientManager).watchTokenExpirations(0xc00032a1e0)
	github.com/ProtonMail/proton-bridge@/pkg/pmapi/clientmanager.go:466 +0x71
created by github.com/ProtonMail/proton-bridge/pkg/pmapi.NewClientManager
	github.com/ProtonMail/proton-bridge@/pkg/pmapi/clientmanager.go:119 +0x3ca

goroutine 40 [select]:
github.com/ProtonMail/proton-bridge/internal/users.(*Users).watchAppOutdated(0xc0002760b0)
	github.com/ProtonMail/proton-bridge@/internal/users/users.go:149 +0x115
github.com/ProtonMail/proton-bridge/internal/users.New.func1(0x152e240, 0xc0002f26c0, 0xc0002760b0)
	github.com/ProtonMail/proton-bridge@/internal/users/users.go:98 +0x5f
created by github.com/ProtonMail/proton-bridge/internal/users.New
	github.com/ProtonMail/proton-bridge@/internal/users/users.go:96 +0x226

goroutine 41 [select]:
github.com/ProtonMail/proton-bridge/internal/users.(*Users).watchAPIAuths(0xc0002760b0)
	github.com/ProtonMail/proton-bridge@/internal/users/users.go:163 +0xf7
github.com/ProtonMail/proton-bridge/internal/users.New.func2(0x152e240, 0xc0002f26c0, 0xc0002760b0)
	github.com/ProtonMail/proton-bridge@/internal/users/users.go:103 +0x5f
created by github.com/ProtonMail/proton-bridge/internal/users.New
	github.com/ProtonMail/proton-bridge@/internal/users/users.go:101 +0x262

goroutine 42 [select]:
github.com/ProtonMail/proton-bridge/internal/frontend/qt-ie.(*FrontendQt).watchEvents(0xc000461200)
	github.com/ProtonMail/proton-bridge@/internal/frontend/qt-ie/frontend.go:131 +0x659
github.com/ProtonMail/proton-bridge/internal/frontend/qt-ie.(*FrontendQt).Loop.func1(0xc000461200)
	github.com/ProtonMail/proton-bridge@/internal/frontend/qt-ie/frontend.go:115 +0x61
created by github.com/ProtonMail/proton-bridge/internal/frontend/qt-ie.(*FrontendQt).Loop
	github.com/ProtonMail/proton-bridge@/internal/frontend/qt-ie/frontend.go:113 +0x54

goroutine 9 [select]:
net/http.(*Transport).getConn(0xc0001ed680, 0xc0001a03f0, 0x0, 0xc0001d0100, 0x5, 0xc000326120, 0x12, 0x0, 0x0, 0x0, ...)
	net/http/transport.go:1239 +0x553
net/http.(*Transport).roundTrip(0xc0001ed680, 0xc0005a4600, 0xc0001a03c0, 0xc000265a1c, 0xc000265a10)
	net/http/transport.go:522 +0x603
net/http.(*Transport).RoundTrip(0xc0001ed680, 0xc0005a4600, 0xc0001ed680, 0xbfd3de7fbab50e0f, 0x1a34b32f038)
	net/http/roundtrip.go:17 +0x35
net/http.send(0xc0005a4500, 0x152fb40, 0xc0001ed680, 0xbfd3de7fbab50e0f, 0x1a34b32f038, 0x2171140, 0xc000011830, 0xbfd3de7fbab50e0f, 0x1, 0x0)
	net/http/client.go:250 +0x443
net/http.(*Client).send(0xc0001a02d0, 0xc0005a4500, 0xbfd3de7fbab50e0f, 0x1a34b32f038, 0x2171140, 0xc000011830, 0x0, 0x1, 0x12a6fe0)
	net/http/client.go:174 +0xfa
net/http.(*Client).do(0xc0001a02d0, 0xc0005a4500, 0x0, 0x0, 0x0)
	net/http/client.go:641 +0x3ce
net/http.(*Client).Do(...)
	net/http/client.go:509
net/http.(*Client).Get(0xc0001a02d0, 0xc0001d0100, 0x3d, 0x1, 0x1, 0x2b)
	net/http/client.go:398 +0xbb
github.com/ProtonMail/proton-bridge/internal/updates.downloadToBytes(0xc0001d0100, 0x3d, 0x3, 0x12e1a16, 0x1, 0xc0001d0100, 0x3d)
	github.com/ProtonMail/proton-bridge@/internal/updates/downloader.go:47 +0x1d1
github.com/ProtonMail/proton-bridge/internal/updates.(*Updates).getLatestVersion(0xc00032a0f0, 0x12e38aa, 0x5, 0x1510d40, 0x5, 0x1511b90, 0xa, 0x152d9a0, 0x18, 0x13433ab, ...)
	github.com/ProtonMail/proton-bridge@/internal/updates/updates.go:205 +0x17c
github.com/ProtonMail/proton-bridge/internal/updates.(*Updates).CheckIsUpToDate(0xc00032a0f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/ProtonMail/proton-bridge@/internal/updates/updates.go:145 +0x122
github.com/ProtonMail/proton-bridge/internal/frontend/qt-ie.(*FrontendQt).isNewVersionAvailable.func1(0xc000461200, 0x480ef00)
	github.com/ProtonMail/proton-bridge@/internal/frontend/qt-ie/frontend.go:399 +0x93
created by github.com/ProtonMail/proton-bridge/internal/frontend/qt-ie.(*FrontendQt).isNewVersionAvailable
	github.com/ProtonMail/proton-bridge@/internal/frontend/qt-ie/frontend.go:397 +0x48

goroutine 44 [select]:
net/http.setRequestCancel.func3(0x0, 0xc0001a03c0, 0xc0001b8050, 0xc000265a1c, 0xc00031e7e0)
	net/http/client.go:321 +0xcf
created by net/http.setRequestCancel
	net/http/client.go:320 +0x24b

goroutine 45 [chan receive]:
net/http.(*persistConn).addTLS(0xc000460c60, 0xc000326120, 0xe, 0x0, 0xc00032612f, 0x3)
	net/http/transport.go:1420 +0x1d3
net/http.(*Transport).dialConn(0xc0001ed680, 0x1577620, 0xc00003a0f0, 0x0, 0xc0001d0100, 0x5, 0xc000326120, 0x12, 0x0, 0x0, ...)
	net/http/transport.go:1493 +0x1c65
net/http.(*Transport).dialConnFor(0xc0001ed680, 0xc000276000)
	net/http/transport.go:1313 +0xdc
created by net/http.(*Transport).queueForDial
	net/http/transport.go:1282 +0x41d

goroutine 51 [runnable]:
reflect.name.tag(0x10c8de8, 0x1, 0xc000218e50)
	reflect/type.go:502 +0x82
reflect.(*structType).Field(0x1288080, 0x7, 0x10c8deb, 0x9, 0x0, 0x0, 0x158a600, 0x121e300, 0x0, 0x0, ...)
	reflect/type.go:1202 +0x104
reflect.(*rtype).Field(0x1288080, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	reflect/type.go:928 +0x7a
encoding/asn1.parseField(0x1288080, 0xc000574018, 0x199, 0xc00014bc04, 0x3bb, 0x3c8, 0x0, 0x0, 0x0, 0x0, ...)
	encoding/asn1/asn1.go:915 +0x1c85
encoding/asn1.parseField(0x123a880, 0xc000574000, 0x199, 0xc00014bc00, 0x3bf, 0x3cc, 0x0, 0x0, 0x0, 0x0, ...)
	encoding/asn1/asn1.go:919 +0x1e52
encoding/asn1.UnmarshalWithParams(0xc00014bc00, 0x3bf, 0x3cc, 0x112f200, 0xc000574000, 0x0, 0x0, 0xc00053b00b, 0xc000652220, 0x0, ...)
	encoding/asn1/asn1.go:1061 +0x1ad
encoding/asn1.Unmarshal(...)
	encoding/asn1/asn1.go:1054
crypto/x509.ParseCertificate(0xc00014bc00, 0x3bf, 0x3cc, 0xc00055b530, 0xc00053b54a, 0x0)
	crypto/x509/x509.go:1613 +0x7d
crypto/x509.(*CertPool).AppendCertsFromPEM(0xc000369e00, 0xc00053b000, 0x54a, 0x74a, 0x74a)
	crypto/x509/cert_pool.go:139 +0xef
crypto/x509.loadSystemRoots(0x5407fa, 0x203000, 0x17)
	crypto/x509/root_unix.go:75 +0x50a
crypto/x509.initSystemRoots()
	crypto/x509/root.go:21 +0x26
sync.(*Once).doSlow(0x218e4d8, 0x139b910)
	sync/once.go:66 +0xe3
sync.(*Once).Do(...)
	sync/once.go:57
crypto/x509.systemRootsPool(...)
	crypto/x509/root.go:16
crypto/x509.(*Certificate).Verify(0xc0000e4000, 0xc000326120, 0xe, 0xc000369b00, 0x0, 0xbfd3dcbdc50a2e53, 0x38c68a64, 0x2171140, 0x0, 0x0, ...)
	crypto/x509/verify.go:744 +0x765
crypto/tls.(*Conn).verifyServerCertificate(0xc0000bc380, 0xc000368c30, 0x2, 0x2, 0x19c4, 0x0)
	crypto/tls/handshake_client.go:834 +0x298
crypto/tls.(*clientHandshakeStateTLS13).readServerCertificate(0xc000343df8, 0x0, 0x0)
	crypto/tls/handshake_client_tls13.go:435 +0x15b
crypto/tls.(*clientHandshakeStateTLS13).handshake(0xc000343df8, 0xc0003f8480, 0x0)
	crypto/tls/handshake_client_tls13.go:85 +0x1ee
crypto/tls.(*Conn).clientHandshake(0xc0000bc380, 0x0, 0x0)
	crypto/tls/handshake_client.go:198 +0x49e
crypto/tls.(*Conn).Handshake(0xc0000bc380, 0x0, 0x0)
	crypto/tls/conn.go:1362 +0x12b
net/http.(*persistConn).addTLS.func2(0x0, 0xc0000bc380, 0x0, 0xc00010ca80)
	net/http/transport.go:1414 +0x42
created by net/http.(*persistConn).addTLS
	net/http/transport.go:1410 +0x1aa

rax    0x0
rbx    0x7fa6a71f8880
rcx    0x7fa6a9a8418b
rdx    0x0
rdi    0x2
rsi    0x7fffae94a150
rbp    0x0
rsp    0x7fffae94a150
r8     0x0
r9     0x7fffae94a150
r10    0x8
r11    0x246
r12    0x7fa6abcb4600
r13    0x31b6d80
r14    0x0
r15    0x2fd9c00
rip    0x7fa6a9a8418b
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

</pre>
## Context (Environment)
Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**Comment by cuthix** [comment]
This looks like some problem with Qt. Do you have problems with any other Qt apps? Are you able to install and run Bridge?

**Comment by andrzejsza** [comment]
@dz0ny if the issues reoccurs, please use a bug tracker or contact support.
