### ISSUE TITLE
[Linux] "sending was canceled by user" error during SMTP

### ISSUE THREAD

**Issue by sjhorst** [ProtonMail/proton-bridge#79]
When upgrading from v1.1.1 to v1.3.3 of the bridge I encountered an issue when trying to send mail using msmtp. After a delay of a few seconds, the send would error out with the message "sending was canceled by user" even though no such action had been taken by me, the user.

Running msmtp in verbose debugging mode, I found that there was no issue with TLS or authentication, the message was sent to the bridge, and just errored out and closed connection after everything was apparently complete.

From there I found the error message in the bridge source code in internal/smtp/user.go:368. It appears to occur if sending to unencrypted receipients. After more slamming my head into the wall, I found that changing the following setting in the configuration prefs.json file from true to false made the issue go away:

"report_outgoing_email_without_encryption":"false"

This certainly isn't documented behavior and seems like it should be more easily changed through the CLI or GUI rather than backdoor editing the config file. I'm not sure why I encountered the issue, and fortunately with the workaround I'm able to send emails again, but wanted to bring it to your attention.

**Comment by jameshoulahan** [comment]
Hi and thanks for the report.

This setting can be modified within the GUI: `Settings` -> `Advanced settings` -> 'Notification of outgoing email without encryption`.

The fact that this doesn't work correctly in the CLI is unfortunately a known issue for which we already have both a [github](https://github.com/ProtonMail/proton-bridge/issues/56) and an internal issue.

As to why the setting suddenly became true during the upgrade, I unfortunately can't say for sure and can only apologise for the inconvenience. This setting should default to false. Perhaps something funky happened during the upgrade from v1.1.1 to v1.3.3; there was a huge amount of code changed between those versions.

Given that the setting is modifiable from within the GUI, and that we already have an issue documenting the problems with the CLI, I will close this as a duplicate. Thanks for your understanding.
