### ISSUE TITLE
Subfolders not correctly getting through the Bridge and creating IMAP folder collisions

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#80]
Guys... come on...

I have created two folders:
`Test`
and
`Test` inside `Test`, so `Test/Test` in Web UI.

**Bridge gives me nice folder collision:**
```
b'(\\Noinferiors) "/" "Folders/Test"'
b'(\\Noinferiors) "/" "Folders/Test"'
```
Meaning folders are not sent with their path.

As the order from IMAP Bridge is random, I am randomly getting first or the second folder in my email client.

You are really trying to test the limits of mail clients...

**Comment by jameshoulahan** [comment]
Please note that subfolder support is still in beta.

As for bridge, preliminary support is already in QA testing and will be pushed out in the next release.

**Comment by exander77** [comment]
@jameshoulahan You are misrepresenting the facts.

The subfolders may be beta, but the problem reported is produced by non-beta ProtonBridge.
No use of beta should ever create a problem on non-beta otherwise it is a bug. 

This can easily lead to disastrous behaviour if the user creates folders like:
Work/Inbox
Work/Sent
Personal/Inbox
Personal/Sent

This would lead to both Inboxes and Send folders randomly assigned in mail client causing mail client corruption and possible data loss.

**Comment by jameshoulahan** [comment]
Preliminary support has passed QA testing and will be pushed out in the next release. Thanks for your continuing patience in this matter.
