### ISSUE TITLE
Import-Export cancel causes multiple tranfers in concurent go-routines

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#81]
Seems like Import-Export synchronization thread is running two times for me. I cancelled first run, to check if I did everything correctly. Then went back and restarted.

But now emails are being put into two labels simultaneously:
Imported Oct-02-2020 11:45
Imported Oct-02-2020 11:59

And the application window is switching between:
92 messages failed to be imported
34 messages failed to be imported

And between:
Importing messages {some other count} of 13887 (11%)
Importing messages {some count} of 13887 (10%)

Is seems like cancel did not cancel the synchronization and both synchronizing threads are fighting over progress bar and messages.

Seriously?

**Comment by exander77** [comment]
This will be a huge fucking mess.

**Comment by cuthix** [comment]
Thanks for report. We will take a look.

**Comment by andrzejsza** [comment]
there was definitely an issues with pausing, fixed in 1.2.2.
