### ISSUE TITLE
Import-Export tool failes to import large number of messages

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#82]
When this tool was released, I expected it would seamlessly migrate my message from Gmail.

So far it seems worse than my own migration with ImapSync. I am at 11% in and I already have 100 failures.

**Comment by exander77** [comment]
Summary: 397 errors.

This is just unacceptable. This is worse than my modified imapsync with reformime.

**Comment by exander77** [comment]
Errors:
```
    140 "failed to import: failed to create draft: too many retries: Invalid sender"
      3 "failed to import: failed to import message: Error while parsing message"
      3 "failed to import: failed to parse message: malformed MIME header line: --9929ef3793b8ac4f7afe31260fa69e6a--"
      2 "failed to import: failed to parse message: malformed MIME header line: --be2b4fba2ec876e0d6baea9120d5eabde--"
      3 "failed to import: failed to parse message: malformed MIME header line: --bed3fc21cebe086ca423bad0f7ed139b0--"
      3 "failed to import: failed to parse message: malformed MIME header line: Děkujeme za Váš zájem o produkty z internetového obchodu HyperMotoShop.cz. Vaše objednávka byla přijata a bude v nejbližší době vyřízena."
    249 "failed to import: failed to parse message: mime: invalid media parameter"
     55 "failed to import: failed to parse message: multipart: NextPart: EOF"
      1 "failed to import: failed to parse message: multipart: unexpected line in Next(): \".2011&utm_content=3DElektro&utm_campaign=3DListopad\\\"><img bo=\\r\\n\""
      2 "failed to import: failed to parse message: multipart: unexpected line in Next(): \"ansparent; text-decoration: =\\r\\n\""
      2 "failed to import: failed to parse message: multipart: unexpected line in Next(): \"idka&utm_campa=\\r\\n\""
      3 "failed to import: failed to parse message: multipart: unexpected line in Next(): \"-----Mail-Builder-Boundary-2796-1575026645-1\\r\\n\""
```
Has clearly problems with drafts where the sender is different than ProtonMail address.
Others are the same problems as were reported half a year ago!

**Comment by jameshoulahan** [comment]
> Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support.

This is an unacceptable github issue. Please contact customer support.

Furthermore, we have an issue template: use it.

**Comment by exander77** [comment]
@jameshoulahan  This contains quite technical details. Reopen immediately. I reported the same bugs half a year ago, here and to support (which is useless) and it is still not fixed.

What is wrong with you?

**Comment by jameshoulahan** [comment]
I kindly request you to either follow the issue template or to contact customer support.

**Comment by exander77** [comment]
@jameshoulahan I would like to request a contact for CTO of ProtonMail.
