### ISSUE TITLE
ProtonBridge does not delete emails when they are removed from Trash

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#84]
I had emails Labels/Label, I deleted them, they moved into Trash, I went to Trash, deleted all emails in there, but they stayed in All Mail. This is unusable. Now I have them in All Mails and how can I easily find them?

**Comment by exander77** [comment]
I tried to delete them from "All Mail", but I got "operation not allowed for "All Mail" folder.

**Comment by exander77** [comment]
I strongly recommend creating folder Rest I suggested in another thread, where all emails which are not in any other folder would reside.

**Comment by jameshoulahan** [comment]
> Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support.

This is an unacceptable github issue. Please contact customer support.

Furthermore, we have an issue template: use it.

**Comment by exander77** [comment]
@jameshoulahan How is this not technical enough?

> I had emails Labels/Label, I deleted them, they moved into Trash, I went to Trash, deleted all emails in there, but they stayed in All Mail.

Reopen.

**Comment by jameshoulahan** [comment]
I kindly request you to follow the github issue template. If you cannot do that, please contact support.
