### ISSUE TITLE
Import-Export tool does not correctly parse some Dates leading to missing X-Pm-Date and dateless email

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#85]
An email with this (and several) other emails ended up dateless:
```
Date: Wed, 17 Jul 2019 11:46:37 +0000 (GMT+00:00)
```

**Comment by jameshoulahan** [comment]
We have an issue template. Use it. Spammy reports just waste everyone's time.

App version?

**Comment by exander77** [comment]
I would recommend disregarding any characters after valid RFC5322 date. Implementations may put some weird things there.

**Comment by jameshoulahan** [comment]
Please note, the new parser will return an error if it fails to parse the date (or other such fields). As a customer, what would you prefer, an error signaling that the date (or other fields) could not be parsed, or silently stripping such bad fields (old parser behaviour), yet importing "what we can"?

**Comment by exander77** [comment]
I noticed you have your own field where you put parsed date X-Pm-Date.
I am against modifying an email so I would leave the original Date as it is:
- The email would not be modified.
- Any external client would be able to use this Date field and show the correct date if it can parse it.
- Users who export emails from ProtonMail to other services will not lose any information.

> As in, by default, we only import what we were confidently able to import
I would argue this a bit as you will not import emails which have missing media parameter (and is a most common error):
"failed to import: failed to parse message: mime: invalid media parameter"
And it is in no way a critical error. :)

I think the end goal should be to import all emails. Checkbox to cover non-critical errors seems ok to me, but I think you should try to get the number of such cases to a minimum. For example, the dates should be parsed without problems even though they have tailing characters.

Same goes for Subjects. You have stripped subjects from some of my emails and/or added (No Subject) Subject.
