### ISSUE TITLE
Persistent "Launch minimized" setting

### ISSUE THREAD

**Issue by JPenuchot** [ProtonMail/proton-bridge#87]
Just a persistent "Launch minimized" option so we don't have to close the window afterwards when Bridge is opened from the application menu

**Comment by cuthix** [comment]
Hi, thanks for suggestion.

  There is option to start bridge without rising window using `--no-window`.
Depends on your OS you can add this parameter to shortcut or alias when
starting Bridge.

I understand that is not what you asked for (i.e. in app settings) but we are
not planning to implement such feature.
