### ISSUE TITLE
Import-Export tool (probably ProtonBridge as well) destroys some Subjects

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#88]
Subjects:
empty string
missing
Hodnocení zakoupeného zboží

Were all replaced with
(No Subject)

Do not change emails.

**Comment by jameshoulahan** [comment]
> Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support.

This is an unacceptable github issue. Please contact customer support.

Furthermore, we have an issue template: use it.
