### ISSUE TITLE
Import-Export tool does not reload user addresses

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#92]
## Expected Behavior
New addresses are detected.

## Current Behavior
Addresses are not detected. Not even logout/login reloads them. I had to remove an account from the tool completely.

**Comment by horejsek** [comment]
Please, understand, this issue tracker is ONLY used for reporting bugs **with technical details**. Reports like this one should be sent directly to our customer support at bridge@protonmail.ch. They will give you a hand to solve your issue or find the details we need to fix the problem. Thank you.

**Comment by exander77** [comment]
@horejsek What technical details are you missing?
