### ISSUE TITLE
Import-Export tool does handle message forwarding through embeding of Content-Type: message/rfc822

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#93]
## Expected Behavior
Correctly embed message with
```
Content-Type: message/rfc822
```
## Current Behavior
Embedded message is turned into an attachment with the name `attachment.eml`.

## Possible Solution
Correctly embed message.

## Note
This does two things:
1. Message does not appear correctly.
2. Message is permanently modified and broken.
![Screenshot_2020-10-07_12-07-35](https://user-images.githubusercontent.com/2256039/95318653-1f1cd800-0897-11eb-8fc7-f31076694866.png)

**Comment by andrzejsza** [comment]
For internal reference - GODT-948.

**Comment by jameshoulahan** [comment]
Hi @exander77, i think this is more a problem of how messages are presented via bridge to the IMAP client. Thunderbird seems to not like that we base64-encode the embedded message.

Could you let me know if this patch solves the problem?

[patch.txt](https://github.com/ProtonMail/proton-bridge/files/5775498/patch.txt)

**Comment by exander77** [comment]
@jameshoulahan Will try the patch and report back. This should be easy to retest if it is just a Bridge encoding issue.

**Comment by andrzejsza** [comment]
Parser is now handling embedding of Content-Type: message/rfc822 (Bridge 1.6.9 early) - closing the issue.
