### ISSUE TITLE
Incorrect use of WordDecoder.DecodeHeader causing header corruption

### ISSUE THREAD

**Issue by exander77** [ProtonMail/proton-bridge#95]
You cannot decode header and then parse it. You have to parse it and then decode encoded words as encoding/decoding is word-based and knows nothing about header structure. Hence why it is called word encoding.

Consider this header:
```
=?ISO-8859-1?B?PEJlemUgam3pbmE+?= <somebody@somewhere.com>
```
When you decode it as a whole, you will get:
```
<Beze jména> <somebody@somewhere.com>
```
This is not correct. As symbols `<` and `>` which were part of the display-name have become part of the whole header and in turn parts of the angle-addr.

But if you parse it first, you will get:
```
display-name: =?ISO-8859-1?B?PEJlemUgam3pbmE+?
angle-addr: <somebody@somewhere.com>
```
Then you can decode it if it is needed.

Golang `"net/mail"` is actually doing this in a correct way and you are screwing with it be decoding header before passing it to 
 `parseAddressList`. This causes a lot of the headers to get incorrectly parsed or making them unparsable and in turn causing a lot of errors: https://github.com/ProtonMail/proton-bridge/issues/89

Why you are doing it baffling.

**Comment by exander77** [comment]
I have added a solution to my pull request: https://github.com/ProtonMail/proton-bridge/pull/94

**Comment by exander77** [comment]
I hope you are not trying to decode headers somewhere else. RFC5322 header is, in general, undecodable as it is not decoded as a whole, but parts of it may be encoded by word encoding. You can have fully compliant MIME header with parts of it encoded by word encoding, yet the header can never be fully decoded as a whole. You can only ever decode RFC5322 header using decodeHeader only if you know that it was encoded as a whole or decoding is indifferent to header structure.

**Comment by jameshoulahan** [comment]
Hi, many thanks for this interesting feedback -- this is a good catch! I suppose this bug is leftover from how the old parser worked; the old parser would first call `DecodeHeader(...)` and then pass the result into `mail.ParseAddressList(...)`. When writing the new parser, I wasn't aware that `mail.ParseAddressList(...)` internally does the decoding itself.

For further information,

I've taken a look at your pull request #94 and while I agree in general about the changes, there is one befe

**Comment by exander77** [comment]
@jameshoulahan I added AddressParser reuse to the second pull request: https://github.com/ProtonMail/proton-bridge/pull/98

**Comment by exander77** [comment]
This should be fixed with new parser.
