### ISSUE TITLE
[Linux] Version 1.3.3 ask for software update

### ISSUE THREAD

**Issue by JeffLabonte** [ProtonMail/proton-bridge#96]
Issue tracker is ONLY used for reporting bugs with technical details. "It doesn't work" or new features should be discussed with our customer support. Please use bug report function in Bridge or contact bridge@protonmail.ch.

Hey there!

I have packaged your software for Solus. I used version 1.3.3 from this repository.

It keeps telling me that it requires to be updated.

## Expected Behavior

Not ask the user to update `proton-bridge`

## Current Behavior

Ask user to update `proton-bridge`
![image](https://user-images.githubusercontent.com/9425955/95539537-a4e67380-09bc-11eb-8c61-8f6faf0218f6.png)

## Steps to Reproduce

1. Download version 1.3.3 of proton-bridge from Github release page
2. Compile & install proton-bridge
3. Run software

**Comment by exander77** [comment]
I can confirm that version from git asks about the update. I didn't consider it a bug. Also, I do not think will ProtonMail third-party builds.

**Comment by JeffLabonte** [comment]
@exander77 What would be the security concerns of packaging a piece of software? I mean, it is already packaged as an archive, a deb, isn't it?

I will create another issue cause the archive doesn't work once build.

**Comment by exander77** [comment]
@JeffLabonte That you modify it somehow during packaging.
